### ISSUE TITLE
ArgoCD preventing automatic GKE upgrade to 1.22

### ISSUE THREAD

**Issue by dry4ng** [argoproj/argo-cd#10003]
We are getting this warning on all GKE clusters:

> This cluster will not be scheduled for an automatic upgrade to v1.22, the next minor version, because your API clients have used deprecated APIs in the last 30 days that are no longer available in this version. Once the cluster reaches end of life on v1.21, it would then be automatically upgraded to v1.22, but upgrading the cluster before it’s migrated to updated APIs could cause it to break.

> Deprecated APIs called: /apis/extensions/v1beta1/ingresses
User agent: argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format
Total calls (last 30 days): 86146

**Comment by toVersus** [comment]
This is not a bug and is the normal behavior of the Argo CD application controllers. Please see the discussion in #9786, especially the comments [here](https://github.com/argoproj/argo-cd/issues/9786#issuecomment-1165907817), [here](https://github.com/argoproj/argo-cd/issues/9786#issuecomment-1166446845) and [here](https://github.com/argoproj/argo-cd/issues/9786#issuecomment-1179429531).
As described in the comments, you can manually upgrade those clusters to v1.22 or later.

**Comment by dry4ng** [comment]
Thanks for the links. I understand that I can manually upgrade the cluster. I already did so. I still get the above message even after upgrade. And I would like to have automatic updates for our non critical clusters. Any suggestions on how to achieve that with ArgoCD oauth enabled?

**Comment by toVersus** [comment]
> Any suggestions on how to achieve that with ArgoCD oauth enabled?

Sorry, I think there is no workaround at this moment. I believe this situation will be improved if we can manually disable the feature to block the automatic GKE upgrade because there are no faults on Argo CD. It dynamically gets list of available APIs on the cluster so it works fine after upgrading the cluster to the version removing the deprecated APIs. I think it would be better to consult with the GCP support and submit a feature request if needed.

**Comment by dry4ng** [comment]
Got it. I will explain the situation to GCP support.
