### ISSUE TITLE
All 2.4.x images have critical Vulnerbilites after Scanning it with Trivy

### ISSUE THREAD

**Issue by Mais316** [argoproj/argo-cd#10233]
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

We have been using ArgoCD for Prod env since Jan 2022, recently as its being used by more of our divisions we are caching and scanning all our tools images in Harbor via Trivy. 

We noticed that all 2.4.x have below critical vul, below is a snap from 2.4.3 & 2.4.8

![image](https://user-images.githubusercontent.com/8318308/183284350-ba0e0ab0-f2a5-477b-b6e4-57a05d3edd8f.png)

**To Reproduce**

Scan any of 2.4.x images

**Expected behavior**

Secure Image

**Screenshots**

![image](https://user-images.githubusercontent.com/8318308/183284411-950a83c2-477d-475c-8616-864a448322a4.png)

**Version**

2.4.x

Problem is we might be blocked of using ArgoCD if the images are having any critical vulnerability as this is not an image built by us so we might be hesitant to fix as we are not sure about ArgoCD behavior.

Please for any next release can you make sure images are secure.

**Comment by crenshaw-dev** [comment]
CVE-2022-1966 should be safe to ignore. go-restful is a transient dependency used in generating the swagger.json file, and it is not used at runtime.

CVE-2021-44716 should also be safe to ignore. Argo CD uses go 1.18 for the whole 2.4.x series. The scan is probably catching go versions for the bundled Kustomize and/or Helm binaries, neither of which should be handling HTTP requests on the Argo CD image.

CVE-2022-21698 will require some more investigation.

**Comment by cbl315** [comment]
CVE-2022-1966 is not relevant(related to CORS) but confusing, `client-go` and `kube-openapi` have already upgrade this module version, see [commit of client-go](https://github.com/kubernetes/client-go/commit/7e1edab3f7bc910b9e5f729d2b8a0b668995d87a) and [commit of kube-openapi](https://github.com/kubernetes/kube-openapi/commit/77c5a1ef51a049e07e19342b134205530a56776d), so I think upgade the `client-go` and `kube-openapi` version could avoid this confusion.

CVE-2021-44716 should be false positive I think.

CVE-2022-21698 should be fixed in `main` branch: https://github.com/argoproj/argo-cd/blob/master/go.mod#L64

**Comment by crenshaw-dev** [comment]
@alexmt is https://github.com/argoproj/argo-cd/pull/9932 the kind of thing that can be cherry-picked back? Looks pretty extensive.

**Comment by crenshaw-dev** [comment]
I'm thinking perhaps we can just go to 0.23.9: https://pkg.go.dev/k8s.io/client-go/kubernetes?tab=versions

**Comment by crenshaw-dev** [comment]
Please see https://github.com/argoproj/argo-cd/issues/16915#issuecomment-1899316046 in case there's any additional work to be done here.
