### ISSUE TITLE
CVE-2021-44906: insufficient fix for prototype pollution in setKey() 

### ISSUE THREAD

**Issue by keithchong** [argoproj/argo-cd#10386]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Argo CD indirectly pulls in minimist that has a security vulnerability

See https://github.com/substack/minimist/issues/164

The fix for that is in minimist v1.2.6.

It looks like the fix in Argo CD to specifically pull in minimist v1.2.6 went into the Argo CD v2.4.0 release via: https://github.com/argoproj/argo-cd/pull/8878

This issue is to backport the fix to the 2.3.x, and 2.2.x releases of Argo CD.

**Comment by keithchong** [comment]
FYI, @crenshaw-dev

**Comment by crenshaw-dev** [comment]
I'm hesitant to backport the fix for a [low-severity vulnerability](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795). Our policy recently has been to backport only critical- and high-severity vulnerability fixes. I think that level of support lines up with our current capacity to test and validate patches.

But if you feel strongly that this one needs a patch, I'm not opposed to trying to get it in!
