### ISSUE TITLE
Sync status is unkown and App Health is Healthy even with error

### ISSUE THREAD

**Issue by ltmleo** [argoproj/argo-cd#10682]
Hi Guys,

I just noticed that when sync status is unknown because it has some configuration errors (e.g. missing folder...), the health status is healthy, this is confusing because the app is not healthy, should be added a new condition, like **error**?. This is a little annoying when there are hundreds of apps. 

![image](https://user-images.githubusercontent.com/43857006/191983502-61a19cba-209c-4a9a-ad52-3d8868ae5da7.png)

```
ComparisonError
rpc error: code = Unknown desc = Manifest generation error (cached): k8s/app/overlays/prod: app path does not exist
```

```
{
    "Version": "v2.4.12+41f54aa",
    "BuildDate": "2022-09-16T00:45:01Z",
    "GitCommit": "41f54aa556f3ffb3fa4cf93d784fb7d30c15041c",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Comment by jessesuen** [comment]
> the health status is healthy, this is confusing because the app is not healthy

This is actually working as intended. Health assessments only require live resource (and not desired version in git) to ascertain the health because we can tell if a Deployment/Pod/etc... is healthy just by looking at it. It is valuable to know that all of the resources of an app is healthy, despite not being able to talk to git.

**Comment by RomanBats** [comment]
I have a similar issue. Though I understand this is designed behavior and quite logical in most cases, there is one case when such behavior is not good, at least for me 😄.

I use the app of app pattern, and rely on sync waves where with the first wave I install all common components, create namespaces and config maps, and the second wave deploys all applications that rely on the presence of components from the first wave. First wave application uses the argocd plugin, and sometimes it fails to connect to external service, leaving the application in a Healthy state but with an Unknown sync status. ArgoCD assumes that the first wave is complete (because the app is healthy) and starts wave 2 which spins until failed.

So, maybe, it would be nice to mark an application at least as "Progressing" if there are no child components created by the argo app and the sync status is unknown.
