### ISSUE TITLE
Statefullset cannot be updated 

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1068]
When updating labels in the statefullset argocd gives an error. this error comes from kubernetes itself. 

In the future also deployments do get these immutable specs, how doe we go about this problem?

This happens when renaming the argocd appname and trying to sync the application

spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**Comment by peterbosalliandercom** [comment]
We use version 0.11.1 and still not working:
![image](https://user-images.githubusercontent.com/9946020/52351283-c09cb800-2a2a-11e9-9660-91d8e96a3c2d.png)

**Comment by peterbosalliandercom** [comment]
With this command it worked. 
```
argocd app sync xxxx --force 
```

**Comment by Kamforka** [comment]
How is it possible to set autosync with force via the application manifest?

**Comment by ebuildy** [comment]
guys, force can delete your statefulSet ..........

**Comment by Kamforka** [comment]
And you can accidentally kill yourself while buttering bread, what's your point?

**Comment by ebuildy** [comment]
> And you can accidentally kill yourself while buttering bread, what's your point?

Try to explain you how kubernetes works:

argocd app --> statefulSet --> pod --> container --> application

You remove statefulSet == you remove pods (except if you specify dont cascade) == remove application 

"sync force" should be avoided as much as possible, this is bad practice.

Bye ^^

**Comment by Kamforka** [comment]
And yet many people have use cases to do so, that's why this issue is a thing.

Also pods are created and removed at this very moment all around the world, those are stateless entities.

What you should really worry about are probably persistent volumes or race conditions that might cause deadlocks during startup.

What I meant by my little commit is that if you don't know what you are doing don't do it, but if you do then you should be able to. The cli already allows you to do it, so why not replicate it in the application manifest.

**Comment by koslib** [comment]
Hello there, I won't continue the butter bread vs force StatefulSet discussion, I'm here just to say that I indeed have a use-case for it.

To give a bit more context, I'd prefer a new pod coming up first, which fits more to the `Deployment` type. Otherwise there is downtime, which is unacceptable.

For whoever else has a similar case, the way we solved it was by recommending to the application team to implement multiple replicas support.

**Comment by jojovem** [comment]
@ebuildy Could you please explain how someone can change the stateful immutable values without destroying it temporarily?

**Comment by switchboardOp** [comment]
> [@ebuildy](https://github.com/ebuildy) Could you please elaborate how someone can change statefulset immutable values without destroying it temporarily?

As I understand it, you cannot. They are **immutable**. If you want to "change" those fields on a statefulset you **must** create a new statefulset with new values for those fields. If you want the new one to be named the same as the old one it means first deleting the old one.
