### ISSUE TITLE
Question: Can ArgoCD function without access to a Git repo?

### ISSUE THREAD

**Issue by benjamingorman** [argoproj/argo-cd#1080]
If I'm right ArgoCD needs to be able to communicate with the Git repository where your Kubernetes manifests are stored.

I'm considering using ArgoCD at my company however we use an internal GitLab instance. There has been some concern about allowing ArgoCD to communicate with our internal GitLab, because it would require that the cluster network be peered with our internal network. This could be a big security hole if the cluster was compromised.

I see some potential solutions to this:
* On every commit, use a CI tool to push all the Kubernetes manifests directly to ArgoCD. This way routing between the cluster and a git repository wouldn't be needed.
* On every commit, use a CI tool to push all the Kubernetes manifests to a private GitHub repository. ArgoCD would be set up with the necessary credentials to pull from this repository.

Does ArgoCD already support either of these solutions? Or something else that would solve the issue?
Thanks

**Comment by jessesuen** [comment]
Short answer is no. Deploying from a git repository is fundamental to the way Argo CD works.

> On every commit, use a CI tool to push all the Kubernetes manifests to a private GitHub repository. ArgoCD would be set up with the necessary credentials to pull from this repository.

Yes this would work and is doesn't sound any different than the normal way how Argo CD works, and is what we [recommend](https://github.com/argoproj/argo-cd/blob/master/docs/ci_automation.md). However, this didn't seem like it was an option for you because you would still need to peer the two networks.

I'm not sure how you are solving the docker repository problem, but it seems to me that you would be facing the same issue in that:

CI needs to push images to a docker repo and the K8s cluster needs to pull from it. Similarly, CI would need to push manifests to a git repo, and Argo CD would need to pull from it. To me, the problems are basically the same.

**Comment by benjamingorman** [comment]
Thanks for the advice - much appreciated.
