### ISSUE TITLE
When adding hostport to daemonset, argo diff does not see drift

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1090]
Argocd diff (in the UI) shows:
         {
              "containerPort": 18080,
              "name": "stats",
              "protocol": "TCP"
            },
              
when in kubernetes the daemonset is like this:
        - containerPort: 18080
          hostPort: 18080
          name: stats
          protocol: TCP
          
 argocd app diff   doest not show any difference.

**Comment by peterbosalliandercom** [comment]
argocd: v0.11.0+71b646d
  BuildDate: 2019-01-10T23:17:31Z
  GitCommit: 71b646dfaedfdbab9e83d314f1b76287561a18e1
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v0.11.1+bdeecc2
  BuildDate: 2019-01-18T23:19:06Z
  GitCommit: bdeecc2ddb2fff4e3bd4153d68cb427166aa5838
  GitTreeState: clean
  GoVersion: go1.11.4
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1

**Comment by alexmt** [comment]
Hello @peterbosalliandercom ,

This behavior is expected. Argo CD uses the same logic as `kubectl diff`. If hostPort is not specified in git then it is ignored during the comparison. This is useful because kubernetes sets a lot of default field values but we need to report differences only in fields which are explicitly in git.

**Comment by peterbosalliandercom** [comment]
Clear thanx
