### ISSUE TITLE
CVEs on 2.5.0 docker image

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-cd#11152]
CVE-2021-46848
CVE-2021-20193
CVE-2022-3358
CVE-2018-1000021
CVE-2016-2781

![image](https://user-images.githubusercontent.com/33283496/199416305-a2f010d3-d1f0-4a1e-a8f9-bd4c7e1ed2b0.png)

**Comment by blakepettersson** [comment]
There's a [2.5.1](https://github.com/argoproj/argo-cd/releases/tag/v2.5.1) release now

**Comment by crenshaw-dev** [comment]
2.5.1 looks clear of critical/high vulnerabilities on our scan: https://argo-cd.readthedocs.io/en/latest/snyk/#v251

**Comment by tooptoop4** [comment]
2.5.1 has:

![image](https://user-images.githubusercontent.com/33283496/199629264-5660b5d3-c529-4ae2-8b27-094a1dc57b8a.png)


CVE-2022-3715 is new one on bash

**Comment by crenshaw-dev** [comment]
We cut releases to resolve high- and critical-severity issues as reported by Snyk.

If you have particular concerns about this bash vulnerability, please describe how it is a particularly dangerous one for Argo CD. Otherwise it'll either be automatically resolved when Ubuntu pushes a patch (and we cut a new release which includes the update) or it will remain unresolved.

Closing for now, lmk if you have particular concerns.
