### ISSUE TITLE
[docs] deploy to gh-pages?

### ISSUE THREAD

**Issue by chalin** [argoproj/argo-cd#11175]
The main site and other Argo docs are published via gh-pages:

- https://argoproj.github.io/
- https://argoproj.github.io/argo-workflows/
- https://argoproj.github.io/argo-rollouts/
- https://argoproj.github.io/argo-events/

In contrast, Argo CD docs are available from:

- https://argo-cd.readthedocs.io/

Have you considered publishing to gh-pages?

The main motivation to publishing to gh-pages would be uniformity, distinct page paths (making analytics easier to manage), and eventually a potentially smoother transition to the Argo domain, [argoproj.io](http://argoproj.io/).

/cc @alexmt

**Comment by agilgur5** [comment]
We've actually been doing the opposite and moving to RTD:
- Rollouts is on https://argo-rollouts.readthedocs.io/
  - (it's actually also on https://argoproj.github.io/argo-rollouts/ due to https://github.com/argoproj/argo-rollouts/issues/3287)
- Workflows recently moved to https://argo-workflows.readthedocs.io/

Per https://github.com/argoproj/argo-workflows/issues/11390, we specifically moved to RTD as it supports versioned documentation out-of-the-box.

> and eventually a potentially smoother transition to the Argo domain, [argoproj.io](http://argoproj.io/).

I don't know if this was planned, but we can probably add subdomains for each of the docs that use RTD.
I'm not sure if using subpaths would be the most appropriate either as there is no uniform headers or footers that link to the other Argo projects from each subproject's individual docs.
