### ISSUE TITLE
Enable password-protected Redis for HA

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#11387]
# Summary

Our HA manifests should support running Redis with password protection. The redis-haproxy config [doesn't currently support auth](https://github.com/argoproj/argo-cd/issues/3130).

# Motivation

Password-protecting Redis is https://github.com/argoproj/argo-cd/issues/3130. Adding password protection provides an additional layer of security to protect cached information (e.g. rendered manifests) from unauthorized access.

# Proposal

Modify the redis-haproxy manifests to support passing auth information.

**Comment by EdmondShtogu** [comment]
Is there any plan for adding this functionality any time soon?

**Comment by crenshaw-dev** [comment]
@EdmondShtogu in my mind, yes. 😄 I'm not precisely sure when I/someone will get to this though.

**Comment by jdoylei** [comment]
@crenshaw-dev - Thanks for capturing this issue.  We're running the HA Argo CD install, and our security team flagged the unprotected Redis as an issue.  If I understand it right, the only way right now to password-protect Argo CD Redis is to replace the HA install with the simple install, right?

**Comment by crenshaw-dev** [comment]
@jdoylei based on this comment, you might be able to modify your install manifests to get it to work with HA: https://github.com/argoproj/argo-cd/issues/3130#issuecomment-1055804547

**Comment by jdoylei** [comment]
@crenshaw-dev - Thanks for the tip!  If I translate that comment into changes applied to Argo CD's HA namespace-install.yaml, it looks like there are 4 "tcp-check send PING" commands in the haproxy.cfg configmap entry.  Would I need to replace each of the 4 occurrences, per that comment?

**Comment by jdoylei** [comment]
@jessesuen and @crenshaw-dev - Just revisiting this, because we had some other reason to override **haproxy.cfg** (see #15319), and I had some second thoughts about the **haproxy.cfg** ```tcp-check send AUTH``` command shown in https://github.com/argoproj/argo-cd/issues/3130#issuecomment-1055804547.  I was trying to decide whether there was some way to extract the password from **haproxy.cfg**, since embedding the password seemed to create more of a security issue.  Would you expect that the ```haproxy.cfg``` file specified in Argo CD's ```argocd-redis-ha-configmap``` should be able to reference [Environment Variables](https://docs.haproxy.org/2.6/configuration.html#2.3), like they're documented by HAProxy?

**Comment by todaywasawesome** [comment]
Closed by https://github.com/argoproj/argo-cd/commit/f1a449e83ee73f8f14d441563b6a31b504f8d8b0
