### ISSUE TITLE
Webhook secrets

### ISSUE THREAD

**Issue by StuartHarris** [argoproj/argo-cd#1142]
We would like to have ArgoCD sync its own config, and noticed that webhook secret for the git provider is lodged in the `argocd-secret` Kubernetes secret. We don't want to overwrite other keys in that secret (especially ones that are added at runtime by ArgoCD itself).
If you think it's a good idea, I'd be happy to raise a PR that moves the webhook secrets into their own secret, possibly called `argocd-webhook-secret`.

**Comment by StuartHarris** [comment]
Interestingly, I noticed that our GitHub webhook is accepted by argocd server even if the secret is not set, or does not match.

**Comment by jessesuen** [comment]
> We don't want to overwrite other keys in that secret (especially ones that are added at runtime by ArgoCD itself).

Argo CD is supposed to only auto-generate keys when it is missing. All keys of the Argo CD secret can be generated/maintained manually if you prefer, since there is nothing magic about how these values were generated. See:
https://github.com/argoproj/argo-cd/blob/master/manifests/base/argocd-secret.yaml

Given the ability to formulate the secret manually, I feel having a single secret is still desirable.

> I noticed that our GitHub webhook is accepted by argocd server even if the secret is not set, or does not match.

Yes, Argo CD will respond to webhooks, but the content of the webhook payload is considered untrusted (regardless if backed by the shared secret), and will only glean the git URL from it to refresh the app. See:
https://github.com/argoproj/argo-cd/blob/master/docs/security.md#webhook-payloads

**Comment by StuartHarris** [comment]
Hey Jesse, thanks for your quick response. Also big thanks for everything you guys are doing, it's amazing!
Does this mean that the webhook passwords don't actually serve a purpose? Should we remove them?

**Comment by jessesuen** [comment]
Thanks for the encouraging word!

> Does this mean that the webhook passwords don't actually serve a purpose? Should we remove them?

If your Argo CD is on the public internet, I would configure a webhook secret to prevent a DDoS attack. I can imagine an attack where a malicious script keeps posting fake webhook payloads to Argo CD, which causes Argo CD the controller to become busy refreshing applications over and over again. To do this, the attacker would need to know what git repo URL your app is using, and formulate the payload accordingly. The worst case is your applications get refreshed unnecessarily.

**Comment by StuartHarris** [comment]
Thanks Jesse. I'll close for now as no further action is required.
