### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by dairta** [argoproj/argo-cd#12072]
### Discussed in https://github.com/argoproj/argo-cd/discussions/12071

<div type='discussions-op-text'>

<sup>Originally posted by **dairta** January 22, 2023</sup>
I've got the sso login button on the login page but I see connection refused when I click on it. Trying to use dex config, saml with Azure</div>

**Comment by jannfis** [comment]
I have already moved the [original issue](https://github.com/argoproj/argo-cd/issues/12070) to a [discussion topic](https://github.com/argoproj/argo-cd/discussions/12071), because I think that's where it belongs. 

When this turns out to be a bug, please feel free to create a bug issue with enough information on our issue tracker.
