### ISSUE TITLE
Allow using any name for secrets which store cluster credentials

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1218]
Currently Argo CD expects that cluster secret's name follows `<host>-<port>` convention. This does not allow deploying to cluster behind rancher which acts as a reverse proxy for multiple k8s clusters.

Instead of enforcing name Argo CD should allow using any secret name and rely only on `server` field.

~Currently, each cluster secret must have `server` field. This field is redundant since the secret name itself has all the required information.~

~Unnecessary  `server` field also causes confusion: user thinks that it is enough to set `server` field but secret name is used internally to reconstruct target k8s server url.~

**Comment by alexmt** [comment]
This keep confusing users and should be prioritized.

**Comment by daanemanz** [comment]
The problem is that this will break any integration with Rancher (which is what we're using). Rancher acts as a reverse proxy for multiple k8s clusters and separates them by the request path in the URL. E.g. you can have two clusters `x-12345` and `y-67890` in the same Rancher setup, with kubeapi endpoint URLs `https://rancher.example.com/k8s/clusters/x-12345` and `https://rancher.example.com/k8s/clusters/y-67890`.

**Comment by alexmt** [comment]
Thank you for additional information @daanemanz !  We had to use the predefined cluster secret name for performance reasons. Starting v0.11 Argo CD uses informers to fetch cluster and repo secrets so there is no need for predefined name anymore! So instead of dropping `server` field we should keep it and allow using any secret name. Updating ticket accordingly.
