### ISSUE TITLE
Crashloop with v0.12-rc3

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1258]
I deployed the rc3 version and as soon as I open de argocd-server ui via de browser it crashes the running argocd-server pod and the argocd-repo-server pod. 

Repo server log shows:

fatal error: unexpected signal during runtime execution
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f93b29e71b9]

**Comment by peterbosalliandercom** [comment]
After installing I added --insecure to the argocd-server command. The rest was default

**Comment by alexmt** [comment]
@peterbosalliandercom can you please check if you have more logs ? The pod could've crashed due to nil pointer dereferences and logs should stack trace in this case. 

Also, did you upgrade from v0.11 to  v0.12-rc3. In this case, we are probably don't handle well some edge case during v0.11 settings upgrade

**Comment by peterbosalliandercom** [comment]
See logging : segmentation violation code=0x1 addr=0x47 pc=0x7fc0988901b9]

**Comment by peterbosalliandercom** [comment]
```
time="2019-03-18T07:59:18Z" level=info msg="Refreshing app status (comparison status unknown)" application=argocd
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7fc0988901b9]

runtime stack:
runtime.throw(0x19e7e1f, 0x2a)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 140 [syscall]:
runtime.cgocall(0x1544370, 0xc00071ee00, 0x29)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc00071edc8 sp=0xc00071ed90 pc=0x403bbe
net._C2func_getaddrinfo(0xc000489100, 0x0, 0xc0002692f0, 0xc00049e1a8, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:91 +0x55 fp=0xc00071ee00 sp=0xc00071edc8 pc=0x56a3f5
net.cgoLookupIPCNAME.func1(0xc000489100, 0x0, 0xc0002692f0, 0xc00049e1a8, 0x15, 0x15, 0xc00071eea0)
        /usr/local/go/src/net/cgo_unix.go:149 +0x131 fp=0xc00071ee48 sp=0xc00071ee00 pc=0x56fb21
net.cgoLookupIPCNAME(0xc0004890c0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:149 +0x153 fp=0xc00071ef38 sp=0xc00071ee48 pc=0x56b9b3
net.cgoIPLookup(0xc00048f380, 0xc0004890c0, 0x14)
        /usr/local/go/src/net/cgo_unix.go:201 +0x4d fp=0xc00071efc8 sp=0xc00071ef38 pc=0x56c06d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00071efd0 sp=0xc00071efc8 pc=0x45a231
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:211 +0xad

```

**Comment by peterbosalliandercom** [comment]
And when adding a repo to repositories:

Logfile:

[log-argocd-server.txt](https://github.com/argoproj/argo-cd/files/2977191/log-argocd-server.txt)

**Comment by alexmt** [comment]
It looks like go decided to use libc to resolve DNS name and failed. 

<details>
 <summary>net.cgoIPLookup(0xc00061b080, 0xc0006e6de0, 0x14) </summary>

```
goroutine 353 [syscall]:
runtime.cgocall(0x1629090, 0xc0004eb600, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0004eb5c8 sp=0xc0004eb590 pc=0x403bbe
net._C2func_getaddrinfo(0xc0006e6e00, 0x0, 0xc0008687b0, 0xc00000e540, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:91 +0x55 fp=0xc0004eb600 sp=0xc0004eb5c8 pc=0x538b95
net.cgoLookupIPCNAME.func1(0xc0006e6e00, 0x0, 0xc0008687b0, 0xc00000e540, 0x15, 0x15, 0xc000141471)
	/usr/local/go/src/net/cgo_unix.go:149 +0x131 fp=0xc0004eb648 sp=0xc0004eb600 pc=0x53e2c1
net.cgoLookupIPCNAME(0xc0006e6de0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:149 +0x153 fp=0xc0004eb738 sp=0xc0004eb648 pc=0x53a153
net.cgoIPLookup(0xc00061b080, 0xc0006e6de0, 0x14)
	/usr/local/go/src/net/cgo_unix.go:201 +0x4d fp=0xc0004eb7c8 sp=0xc0004eb738 pc=0x53a80d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0004eb7d0 sp=0xc0004eb7c8 pc=0x459c01
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:211 +0xad
```

</details>


As I understand `clib` should've not be used since with start building with `CGO_ENABLED=0` flag and C calls should not work at all.  

According to https://go-review.googlesource.com/c/go/+/11584/ the `-tags netgo` flag should force using golang implementation for DNS resolution. Adding it to Makefile.

@peterbosalliandercom since issue it only reproducible on your environment can you please help testing the change? I've pushed image which includes https://github.com/argoproj/argo-cd/pull/1286 to  `alexmt/argocd:v0.12.0-f588cbc`. Alternativelly you can set env variable `GODEBUG=netdns=go` in each Argo CD deployment.

**Comment by peterbosalliandercom** [comment]
It seems to work, I am able to add a repo now and create an application, will test further today
