### ISSUE TITLE
Not configured chat url results in chat button shown

### ISSUE THREAD

**Issue by woehrl01** [argoproj/argo-cd#12655]
@saumeya @crenshaw-dev This change introduced in #10417, now results in showing the chat button even though there is no url at all configured.

This is because the chat url is explicitly set to an invalid url, if it can't parse.

**Comment by saumeya** [comment]
Thanks for reporting @woehrl01 , will take a look and fix it

**Comment by KyleSanderson** [comment]
Any update on this? I'm still being asked to CHAT NOW!

**Comment by svonliebenstein** [comment]
Yeah, it would be great if a little bug fix was created for this.

In our scenario we deploy the argocd-cm without even specifying the 'help.chatUrl' key. Since 2.6.3 the chat button is showing up.
@saumeya are you aware of this behavior?

A not set chat url should never cause the button to show up. I think the URL validation and error reporting should only show up if the key is filled with anything other then null or "".

**Comment by KyleSanderson** [comment]
I can happily confirm I am no longer being asked to CHAT NOW!

**Comment by crenshaw-dev** [comment]
Argo CD has been trying to reach you about your car's extended warranty...
