### ISSUE TITLE
resource duplicate and flip/flop

### ISSUE THREAD

**Issue by jas01** [argoproj/argo-cd#12812]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I create a ConfigMap who was too big (a logo), so I change it. After that I've a duplicate same resource in the webui, who not stopping to be create and delete (the first one on the screenshot don't change, but the second are created/deleted/created/etc.).

When I check the content (very hard because this flip/flop) I can see the uid change. With oc get configmap I can see the configmap are deleted and recreated every 4 sec (the oldest)

**To Reproduce**

Don't know

**Screenshots**

![image](https://user-images.githubusercontent.com/11524096/224350912-ca2fc83d-a542-4938-95de-85a0c5e66f5d.png)

**Version**

Version argocd on server:
```shell
v2.6.4+7be094f
```

**Comment by reggie-k** [comment]
The problem is in how Openshift operator behaves, it copies your config map, along with ArgoCD tracking label, to another ns, and so ArgoCD thinks the cloned ConfigMap is his.
Since the cloned ConfigMap is not in Git, ArgoCD complains about a diff from the desired state.
I have worked this around by setting this anno on the original ConfigMap:
argocd.argoproj.io/compare-options: IgnoreExtraneous
argocd.argoproj.io/sync-options:  Prune=false
This way they get copied by openshift operator to the cloned resource and ArgoCD will ignore the resource. It will still appear yellow, but the app will show synced.
Another option would be a mutating webhook to delete the Argocd tracking label from the cloned resource, after it is created by openshift operator.
