### ISSUE TITLE
Argo BlueGreen Deployment Strategy with Auto sync issue

### ISSUE THREAD

**Issue by ajeya07** [argoproj/argo-cd#12897]
Hi Team,

We have Argo CD setup for our application and there we have auto sync enabled for git to sync changes, now we are enabling argo BlueGreen Deployment Strategy, we are facing below issue.

**New version update (new application image deployment)**
1. Once new changes are committed to our CD git repo and new version are deployed and auto prompted by BlueGreen Strategy.
2. If we rollback to previous revision using Argo rollout UI. the old revision is automatically sync to new images **(This should not happen)**. if disable auto sync is working as expected.  

**Config and secrete deployment**
1. Once new changes are committed to our CD git repo for config and secret and new version are deployed and auto prompted by BlueGreen Strategy.
2. I can see the changes of config map is reflecting in old replica set also **(This should not happen)**, but pods are not restated.

**Comment by todaywasawesome** [comment]
If I understand you correctly, you are committing a change which triggers a blue/green rollout then using the ui to rollback. An autosync from Argo CD happens overwriting the rollback and restarting the whole process. Is that right? 

Normally Argo Rollouts detecting a problem will revert the image deployed to previous. If you do a manual rollback to a previous revision, Argo CD would see this as drift and if auto sync is enabled, will overwrite it. This is expected behavior.

**Comment by Argelbargel** [comment]
Hi @todaywasawesome,

i've stumbled over the same "problem". We'd like to have AutoSync enabled in ArgoCD to ensure the deployments always match the state in our iac-git-repository. 

In our use case we're deploying an update-server providing updates for a fat-client running on our users machine. So beyond basic health-checks like "is the http-server running" and "is the update-index-file present" we cannot run analysis to check if the latest update is working correctly. 

To enable us (the devops team) and our testers to check an update-deployment, we use a blue/green rollout with manual promotion. It might happen that a problem is detected after the latest version got promoted and we need to rollback to the previous version (again manually).

What I do not quite understand: if Argo-CD "delegates" the promotion of the new version to Argo-Rollouts, why does it enforce the latest version after promotion due to AutoSync? My expectation was that Argo-Rollouts would have complete control over the blue/green deployments and which is connected to which service?

Would it be possible to enabled manual rollbacks by excluding some differences in the definition of the Application so that at least (most) other resources will be automatically synced?

Kind regards!

**Comment by romancin** [comment]
> What I do not quite understand: if Argo-CD "delegates" the promotion of the new version to Argo-Rollouts, why does it enforce the latest version after promotion due to AutoSync? My expectation was that Argo-Rollouts would have complete control over the blue/green deployments and which is connected to which service?

We have found the same behaviour here, but only with BlueGreen Strategy, Argo CD promotes the new version always. This behaviour don't happen with canary strategy, we can see with it the Argo CD App automatically makes the App state "Suspended", and delegates in Rollouts the operations to do.
