### ISSUE TITLE
ArgoCD doesn't diff on Volume and Volumemounts

### ISSUE THREAD

**Issue by xiboulay** [argoproj/argo-cd#13145]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Argocd is not showing diff for volume and volumemount 

**To Reproduce**

1- Create a deployment using volumes and volumesmount
2- Update the deployment manually (via kubectl for example) and and new volume and volume mount
3- Go to argocd and refresh the concerned app
4- Argocd sees no diff despite show the live manifest with the updates and desired manifest as it is in the repo

**Expected behavior**

Argocd must display a diff  

**Version**

```
v2.5.0+b895da4
```

**Comment by jaideepr97** [comment]
Hi @xiboulay I believe this is expected behavior
Argo CD behaves the same way as `kubectl diff` so resource modification methods such as using the Argo CD UI or `kubectl edit` are considered 'out of band' and argo-cd will not detect the diff 
My understanding is that these methods don't use `kubectl apply` under the hood

you can see more in this comment https://github.com/argoproj/argo-cd/issues/7611#issuecomment-963722356

and I also found this article helpful when I came across a similar issue 
https://blog.atomist.com/kubernetes-apply-replace-patch/
