### ISSUE TITLE
Deployment is always out of sync if resource limit is specified

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#132]
Kubernetes reformats resource limits values. E.g. is cpu is specified as `1.5` it will be changed to `1500m` . Because of that deployment will be shown as OutOfSync

**Comment by jessesuen** [comment]
I don't think there is an easy way to solve this. We would have to marshal to the appropriate concrete data structure to get the benefits of any custom MarshalJSON() implemented by the type. This is instead of dealing with unstructured.Unstructured objects. 

Can we just say that it should be a best practice to use use the format that k8s prefers to serialize their data as?
