### ISSUE TITLE
[ui] Add parent application links in header breadcrumb

### ISSUE THREAD

**Issue by ebuildy** [argoproj/argo-cd#13326]
# Summary

Add application hierarchy links in breadcrumb:

<img width="572" alt="Capture d’écran, le 2023-04-23 à 20 46 01" src="https://user-images.githubusercontent.com/1219817/233876527-d45157b6-509c-4179-80ac-601234875be2.png">

# Motivation

Make app of apps navigation easier

# Proposal

A simple annotation to indicate the argocd parent application

**Comment by teejaded** [comment]
How should this work?   I think it's possible right now to show the immediate parent based on the label `argocd.argoproj.io/instance`.

If you wanted to show further up the tree it would take more api calls, I think.  For me the `api/v1/applications/app` call takes 100-200ms so that would get unusable pretty quickly.

**Comment by ebuildy** [comment]
You are right, "argocd.argoproj.io/instance" of current argocd application give the parent name.

We could start a 1st version by a single level depth (aka only the "argocd.argoproj.io/instance"), then display all the hierarchy.

**Comment by ebuildy** [comment]
Duplicate of https://github.com/argoproj/argo-cd/issues/8472
