### ISSUE TITLE
GitLab Merge Request Webhook fails with: HTTP 400 Webhook processing failed: event not defined to be parsed

### ISSUE THREAD

**Issue by kaiburjack** [argoproj/argo-cd#13658]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When configuring the GitLab Merge Request Webhook integration in GitLab against ArgoCD https://our-server/api/webhook, and testing the webhook in GitLab with the "Test > Merge request events", GitLab responds with the error message:

> Hook executed successfully but returned HTTP 400 Webhook processing failed: event not defined to be parsed

**To Reproduce**

Create a GitLab repository, enable WebHook for merge request events and test the merge request.

**Expected behavior**

The webhook POST for Merge Request Events should also work, just like (already working) Events for Git Branch Push events.

**Version**

v2.7.2+cbee7e6.dirty

**Comment by httpdigest** [comment]
After investigation, it seems that the culprit is the value of the HTTP header `X-Gitlab-Event` in the POST request.
For Gitlab Merge Request Webhook Events, it has the value `Merge Request Hook`.
Requests with this header value will be rejected with HTTP 400 and the payload: `Webhook processing failed: event not defined to be parsed`.

The _only_ value for which this works, is for Git Push events: `Push Hook`, but this is only for Gitlab Branch Push events.
I want the Gitlab Merge Request Update webhook to work.

**Comment by kaiburjack** [comment]
Sorry, my fault/bad. I was using the _wrong_ service as the ingress/VirtualService endpoint. I was using the argocd-server and _not_ the argocd-applicationset-controller :(
