### ISSUE TITLE
Normalize git repo URLs

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#138]
Git repos can have .git or the .git piece could be missing. This makes it unfriendly to add applications. If we normalize the git repo URL (e.g. by removing .git extension, and lowercasing the repo URL), then there will be less user error.

**Comment by alexmt** [comment]
I've also encountered inconvinient behavior while creating app:

- repository was registered using lowercase 
- tried to create application using camel-case repo URL

app creation failed because argocd was unable to find repo password. I think argocd should correctly 
add app in this case case since URL points to the same repo regardless of case.

**Comment by merenbach** [comment]
Closed by 3f4ec0ab2263038ba91d3b594b2188fc108fc8d7
