### ISSUE TITLE
Floating hover items have transparent backgrounds

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#14067]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Tooltip boxes have no background

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?view=tree&page=0&untilTimes=&resource=name%3Aargocd-redis-ha-server%2Cname%3Aargocd-redis-ha-server-0&node=%2FPod%2Fargocd%2Fargocd-redis-ha-server-0%2F0&tab=logs
2. Hover over things

**Expected behavior**

Tooltip box like things should be opaque

**Screenshots**

https://github.com/argoproj/argo-cd/assets/2119212/c38dc032-f2db-4191-8a27-fef684bce4c3

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
{
    "Version": "v2.8.0+f63b856.dirty",
    "BuildDate": "2023-06-14T13:37:58Z",
    "GitCommit": "f63b856394e6c41d68ef3fb3f7cd99b3c2d1435a",
    "GitTreeState": "dirty",
    "GoVersion": "go1.20.4",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.12.0+gc9f554d",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by keithchong** [comment]
This appears to be an issue after we upgraded to Tippy 3.1.1 from 2.2.3. However, it was done 9 months ago so I'm surprised we are seeing this problem only recently.  It looks like we pulled in the latest version of argo-ui only 3 weeks ago via https://github.com/argoproj/argo-cd/pull/13836, so this explains it.

Most if not all the tooltips in the UI are affected since they use the tooltip component in Argo UI:

https://github.com/argoproj/argo-ui/blob/master/src/components/tooltip/tooltip.tsx

`export const Tooltip = ( props: any ) => <Tippy animation='fade' arrow='true' {...props} />;`

In Josh's video, each tooltip has the word 'true' at the top, and it is coming from the value of the _arrow_ attribute. So it looks like we need to migrate this implementation.

If we use the following instead, the tooltips look better...it's not perfect, especially the tooltips for sidebar and the commit details in the status bar, but it's better.

`export const Tooltip = ( props: any ) =>   <Tippy offset={'0,8'} theme='light' arrow={roundArrow} interactive={true} content={props.content} children={props.children}/>;`

**Comment by jsoref** [comment]
Not pictured, and perhaps not reported, but if you edit an application and click the target revision, the drop down does something similarly problematic:

![image](https://github.com/argoproj/argo-cd/assets/2119212/30411f04-940f-42d7-bccc-a9be88403ed4)

@keithchong: Is this the same problem / can you fix it too, or should I ensure there's an additional bug?

(If I haven't filed it, and I'm not sure I have/haven't, it's probably because I don't like posting bugs based on our own instances..., and I don't think I can use `edit` right now on the public cd instance.)

**Comment by keithchong** [comment]
@jsoref , that is a different problem and it relates to the Autocomplete component. There should be separate bug opened for that.

Interesting though that after adding a few repos in the settings, then, in the New App panel, the Repository URL field under the Source section works and looks ok.

**Comment by keithchong** [comment]
@jsoref , I have the fix for autocomplete. (Simply increase the zIndex so the dropdown will be above the other fields below. Here, the Path field is underneath)

<img width="766" alt="Screen Shot 2023-06-22 at 10 33 20 AM" src="https://github.com/argoproj/argo-cd/assets/7726022/8e47ba16-ddc0-42a6-ab56-68f52e803439">

**Comment by jsoref** [comment]
@keithchong fwiw the autocomplete is reported as #13067

**Comment by alexmt** [comment]
Created two PRs that fixes the issue
