### ISSUE TITLE
'apiKey' permission missing from default admin account

### ISSUE THREAD

**Issue by lknite** [argoproj/argo-cd#14679]
Admin account has all the other permissions, should it not also have 'apiKey'?

Here's where I checked to see if it has apiKey permission:
https://github.com/argoproj/argo-cd/blob/master/assets/builtin-policy.csv

```
$ argocd account generate-token 
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
FATA[0000] rpc error: code = Unknown desc = account 'admin' does not have apiKey capability
```

**Comment by morey-tech** [comment]
I don't think the `apiKey` permission is determined by RBAC; I think it's an account setting. When [creating a new user](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#create-new-user), you can define two capabilities, `login` and `apiKey`. It seems the `admin` user isn't granted the `apiKey` one.

This appears to be intentional:
> Please keep in mind that we don't encourage using admin for API access at all, and that's why (by default), the admin user has no apiKey capabilities. https://github.com/argoproj/argo-cd/issues/6687#issuecomment-878887020

**Comment by lknite** [comment]
Came across this when I needed it.  Sounds like it is by design.  Ok by me.
