### ISSUE TITLE
Pod/Node view

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#1483]
**Is your feature request related to a problem? Please describe.**

I'd like to understand how pods are packed onto my nodes. 

**Describe the solution you'd like**

A new UI view to surface this information.

**Comment by adrienjt** [comment]
How about connecting pods to nodes in an App's tree view:

![](https://argoproj.github.io/argo-cd/assets/guestbook-tree.png)

In the picture above, to the right of pods, there would be node boxes that pods would connect to.

**Comment by jessesuen** [comment]
Working on this in https://github.com/argoproj/argo-cd/pull/4497

**Comment by jessesuen** [comment]
Changes required:

1. Pod InfoItems need to be populated with Node information:
https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L968
https://github.com/argoproj/argo-cd/blob/master/controller/cache/info.go#L167

2. New endpoint in API server to return nodes associated with an application.

**Comment by jessesuen** [comment]
@rbreeze you will want to add a Node informer/lister like we do with application and projects:

https://github.com/argoproj/argo-cd/blob/master/server/server.go#L214-L218

And use the node lister in the new "nodes" endpoint, similar to:

https://github.com/argoproj/argo-cd/blob/master/server/application/application.go#L133

**Comment by jessesuen** [comment]
For the nodes endpoint, I don't think we should return the entire node object because it will be a security concern to expose all node information (which includes images being run on the node). We should redact the node object to only the information we are interested in presenting in the UI, such as:
* memory/cpu usage and capacity
* hostname
* os/version/architecture
