### ISSUE TITLE
Simplify whitelisting self signed cert of git server

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1514]
**Describe the bug**
It is unnecessarily difficult to connect the git repository using SSH url if git server uses self signed cert. Currently the user have to add git server host to known_hosts on client where `argocd` is running, and in all pods (argocd-server, argocd-repo-server and `argocd-application-controller`). 

This is happening because each component tries to validate is repo is accessible. Instead argocd-repo-server should expose an API to validate repo connectivity. The new API can be used by all other components.

**Comment by jessesuen** [comment]
> uses self signed cert

To clarify, for SSH repos, it's not a certificate issue (which has to do with with HTTPS URLs). It's the known hosts keys. Argo CD only adds the following well-known host keys (github, bitbucket, azure, gitlab). Any SSH host outside these four either need to use `--insecure-ignore-host-key`, or customize the deployment objects to volume map a custom known hosts file.

**Comment by jannfis** [comment]
I think it might be beneficial to outsource the SSH known hosts data into a ConfigMap object and mount that to the pods instead of having a custom built Docker image for adding custom SSH known hosts entries. In combination with something like ConfigMapReload, it would make maintaining the SSH known hosts much simpler. As an additional feature, argocd CLI could be enhanced to add or remove entries from the ConfigMap.

What do you think on this approach? Have you already considered it and made a decision against it in the past? If it's ok from an architectural point of view, I would volunteer for implementation.

**Comment by alexec** [comment]
It'd be good to get away from having to build your own Docker image.

**Comment by jannfis** [comment]
OK, I'm already hacking on it. Will send an initial PR soon. However, the changes are most likely a little broader scoped than I initially thought, if you don't mind. 

The change will probably introduce a more general way on how we can handle generic runtime configuration data that is likely to change, such as additional TLS CAs or self-signed TLS (https) certificates.

**Comment by alexec** [comment]
@jannfis can you shed more light on your approach please? E.g. are you running `ssh-keyscan` before each checkout and build?

**Comment by jannfis** [comment]
@alexec OK, let me try to describe my thoughts on this (I have an initial prototype already working):

- In the Docker image, I introduce a new top directory /app/config
- In Kubernetes, introduce a new ConfigMap object in argocd namespace. Currently I name this argocd-runtime-cm
- This ConfigMap gets mounted as a volume onto /app/config in the pods of argocd-server and argocd-repo-server (so far)
- The argocd-runtime-cm ConfigMap currently contains a data key, ssh_known_hosts. This will result in a file at /app/config/ssh_known_hosts in the container (and generally, be able to create files there with the same names as the key in the ConfigMap)
- Make a symbolic link for /etc/ssh/ssh_known_hosts pointing to /app/config/ssh_known_hosts when building the Docker image

Now, you can kubectl -n argocd edit cm argocd-runtime-cm to add/delete entries to the ssh_known_hosts file and it will propagate to all pods on all nodes automatically.

This is what already works so far. I modified the Kustomize files accordingly and introduced a new config map Kustomize file, which I pre-populated with the data from hack/ssh_known_hosts.

What I further think of is, that the argocd-runtime-cm can be modified more simple with the argocd CLI, either with a new option to "argocd repo add" or using a new command, whatever is more viable. The user would still have to know the correct SSH host key of the repo's server (i.e. fetch it by using ssh-keyscan), but would not have to rebuild/rollout a new Docker image to the cluster.

The same mechanism could go for HTTPS repositories, by adding a new key to the ConfigMap.

**Comment by jannfis** [comment]
To give you a better idea, the config map looks something like in this gist: [https://gist.github.com/jannfis/0d7e60f9a6bdf2730fbd8115fe6bd055](https://gist.github.com/jannfis/0d7e60f9a6bdf2730fbd8115fe6bd055)

**Comment by alexec** [comment]
@jessesuen ☝️

**Comment by jannfis** [comment]
I think the ConfigMap approach would also allow for something more sophisticated in the next steps, such as what @alexmt has proposed: Put in some functionality into the API to handle fetching, returning and storing SSH host keys certificates from remote repository servers, present them to the user and ask whether to accept it (and thereby effectively store it in the config map). But I also think this must be handled carefully, because it's next to "allow insecure connections" when users tend to accept most stuff presented to them.

We should also think about managing TLS Root CAs as such runtime configuration data, since many organisations use their own CAs to sign their internal TLS certificates, and once the CA is known to the ArgoCD components there is no need for accepting all single certificates for each server ArgoCD tries to access. However, managing is those is more difficult and strongly depending upon the underlying base image (i.e. RedHat based OS such as CentOS handle certificate management different from Debian based, etc. - it's quite a mess)

**Comment by jannfis** [comment]
I think this issue can be closed, because #1807 addressed everything in scope of this issue.
