### ISSUE TITLE
Allow users to disable the `default` project creation

### ISSUE THREAD

**Issue by henkka** [argoproj/argo-cd#15518]
# Summary

Allow users to disable the automatic creation of the default project in argocd-server.

# Motivation

To enhance Argo CD security, this feature offers an alternative to [#11058](https://github.com/argoproj/argo-cd/issues/11058), inspired by @12345ieee's comment [here](https://github.com/argoproj/argo-cd/issues/11058#issuecomment-1601845978). This would let us disable `default` project creation during runtime and either create a hardened version declaratively before argocd-server starts or omit the `default` project entirely.

# Proposal

See the initial proposed changes [here](https://github.com/argoproj/argo-cd/compare/master...henkka:argo-cd:master?w=1).

**Comment by blakepettersson** [comment]
Looks good to me! Could you open a PR with those proposed changes, so that other members can take a look? Also, if possible could you add some tests for that feature?

**Comment by henkka** [comment]
Great to hear! I'll submit a comprehensive PR with tests for further discussion and guidance on the feature's implementation. :)

**Comment by henkka** [comment]
Original issue #11058 turned out to be less severe than initially thought. We're satisfied with its current progress and won't proceed with this alternative initiative.

**Comment by jemag** [comment]
@henkka I think it still makes sense to grant end-users the flexibility to not create a default project. Unless I am missing something, there doesn't seem to be much disadvantage in doing so.

Personally, I find that disabling the default project and providing your own to be a cleaner approach, rather than having to dance around the behaviour of a programmatically created resource (e..g. needing to override the default project and having to keep in mind that if it ever gets deleted, it will be automatically re-created with default permissions)

**Comment by Chenthilraj** [comment]
Is this feature available in v2.11.2. Or is the PR still to be merged?
