### ISSUE TITLE
"Source" pane is jumpy when typing repo name for a new app

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#15961]
**Describe the bug**

When I create a new app, each keystroke in the repo URL field causes a backend call and jumpiness in the UI.

**To Reproduce**

Create a new app and manually type the repo URL.

**Expected behavior**

I'd expect the UI to remain calm. Ideally, I'd expect the UI to validate what I've typed and not make a backend call if the URL has no chance of being a valid repo URL.

**Screenshots**

https://github.com/argoproj/argo-cd/assets/350466/c079b880-fa82-44db-965d-062857a87b2c

**Version**

2.9.0-rc2

**Comment by surajyadav1108** [comment]
The jumpiness in the UI for keystrokes seems to be related to how the Autocomplete component in argo-ui is configured. To test this , I tried to set it up locally following the guidelines in the argo-ui repository. However, the build failed due to multiple compatibility issues with dependencies and versions listed in yarn.lock and package.json.

**Comment by surajyadav1108** [comment]
> Hi @crenshaw-dev, I've put up a PR to fix this issue
> 
> As git supports [many URL formats](https://stackoverflow.com/questions/31801271/what-are-the-supported-git-url-formats) (e.g., `ssh`, `http`, `https`, `git`), rather than validating the input is a valid repo URL, I've opted to use a debounce-based approach instead
> 
> Let me know if you have any feedback!

Simple and effective @david-wu-octopus 👏

**Comment by gomgomshrimp** [comment]
@david-wu-octopus 

After upgrading Argo CD from `v2.11.7` to `v3.1.1`, I'm experiencing an issue where Create Application can't retrieve repo information(branch and path).
Below is a video capture demonstrating this issue.

## Version `v2.11.7`
https://github.com/user-attachments/assets/47bd9ad8-d793-47a2-b153-c092f20125e2

## Version `v3.1.1`
https://github.com/user-attachments/assets/678a3624-f5cd-43fa-b960-864166b10990


Interestingly, the issue where `v3.1.1` fails to fetch repo information doesn't occur consistently; sometimes it fetches the information just fine.

While we can't pinpoint exactly what the problem is, testing versions before and after this code was merged makes us suspect this code.

**Comment by david-wu-aa** [comment]
@gomgomshrimp, thanks for your comment. Could you please create a new issue for this bug to facilitate triaging and progress tracking?
