### ISSUE TITLE
argocd helm chart is not performing auto subnet discovery

### ISSUE THREAD

**Issue by omkar-k3** [argoproj/argo-cd#16176]
### Discussed in https://github.com/argoproj/argo-cd/discussions/16173

<div type='discussions-op-text'>

<sup>Originally posted by **omkar-k3** October 31, 2023</sup>
Hello,

I am installing argocd helm chart version 5.48.0 using terraform on AWS EKS, however it is failing to provision loadbalancer with below error

Events:
  Type     Reason            Age                 From     Message
  ----     ------            ----                ----     -------
  Warning  FailedBuildModel  10m (x18 over 21m)  service  Failed build model due to unable to resolve at least one subnet (0 match VPC and tags)

All my subnets are correctly tagged as recommended.

Can anyone help?</div>

**Comment by omkar-k3** [comment]
can anyone help to resolve this issue

**Comment by blakepettersson** [comment]
This seems to be more of an issue with how your subnet and/or VPC is configured. Do you have any other ingresses configured on the same cluster (this would likely exclude the possibility of it being an Argo issue)? Otherwise I'd suggest for you to get help in either the [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) or in the [argo-helm](https://github.com/argoproj/argo-helm) repo (since Argo CD is not - yet - officially supported).

**Comment by omkar-k3** [comment]
thanks for responding @blakepettersson 
I have already installed aws-load-balancer-controller and it was a success, however argocd service is not getting deployed.
I have already tagged my subnets with the required tags

**Comment by blakepettersson** [comment]
Closing since this is not an issue with Argo
