### ISSUE TITLE
Enable Helm template `--dry-run=server` Feature for Template Generation in Argo CD

### ISSUE THREAD

**Issue by MoranWeissman** [argoproj/argo-cd#16367]
# Summary

This proposal suggests enhancing Argo CD by integrating the newly introduced --dry-run=server option in Helm's template feature (available from Helm v3.13.0). This integration would enable server-side template rendering in Argo CD, allowing access to real-time, cluster-specific data during the templating process. This feature broadens the scope of use cases and increases the flexibility of Argo CD in diverse Kubernetes environments.

# Motivation

Managing deployments across Kubernetes clusters with varying versions poses significant challenges, particularly in ensuring compatibility and customization. For instance, in environments with over 70 clusters having versions from 1.21 to 1.28, it is crucial to match deployments, such as add-ons, with the specific cluster version. The --dry-run=server feature in Helm's template command can empower Argo CD to access real-time data, such as the cluster version (through Helm's Capabilities.KubeVersion.Version), enabling more intelligent deployment decisions. This capability is not only advantageous for version-specific deployments but also enhances the overall deployment strategy, error-checking, and adaptability in complex Kubernetes scenarios.

# Proposal

1. Integration of --dry-run=server in Templating: Implement the --dry-run=server option from Helm's template feature in Argo CD. This enables server-side rendering of Helm templates, providing access to up-to-date, cluster-specific information during the templating phase.

2. Dynamic Deployment Strategy: Leveraging server-side data, Argo CD can make informed, dynamic decisions during deployment, such as selecting compatible add-on versions based on the Kubernetes version of the target cluster.

3. Improved Error Checking and Validation: The server-side dry-run capability can enhance error detection and validation by considering the actual state and configuration of the target cluster.

4. Configuration Syntax to Enable the Feature:
```yaml
helm:
  dryRunServerSide: true
```

A straightforward configuration option in Argo CD to enable the --dry-run=server feature.

This enhancement proposal aims to integrate a valuable feature from Helm into Argo CD, not only addressing specific scenarios like version-dependent add-on deployments but also significantly improving Argo CD's functionality and efficiency in managing diverse and complex Kubernetes environments.

**Comment by crenshaw-dev** [comment]
Let's consolidate the discussion here: https://github.com/argoproj/argo-cd/issues/5202

The main blocker is the fact that Argo CD runs as a superuser in the destination cluster. So there's currently no mechanism to limit lookups to the Application's permissible scope.

**Comment by crenshaw-dev** [comment]
More in general, I'm of the opinion that injecting runtime state should happen at runtime (via a controller or mutating webhook) and that manifest hydration should be deterministic, reproducible, and rely only on git state.

But folks want `lookup`, so we'll eventually make it work.

**Comment by Ornias1993** [comment]
> More in general, I'm of the opinion that injecting runtime state should happen at runtime (via a controller or mutating webhook) and that manifest hydration should be deterministic, reproducible, and rely only on git state.
> 
> But folks want `lookup`, so we'll eventually make it work.

It's not just that folks "want" lookup, it's the fact that ArgoCD is inherently incompatible with a significant portion of Helm charts out there, by, basically, parsing in a way that is in contrast to the standard set by both the Helm standard and some competing gitops solutions



> Let's consolidate the discussion here: #5202
> 
> The main blocker is the fact that Argo CD runs as a superuser in the destination cluster. So there's currently no mechanism to limit lookups to the Application's permissible scope.

This is also a problem, because helm-lookups by default also run quite permissive.
In fact it needs to be quite thoroughly documented in which ways the to-be-someday-released argocd lookups are affected by permission scope. To prevent basically the same disappointment (or chart creators having to compensate) all over again...

**Comment by crenshaw-dev** [comment]
> ArgoCD is inherently incompatible with a significant portion of Helm charts out there

It's true. I do think that secret refs are a better system and that over time more charts should adopt that system. But yes, the status quo is that many charts are incompatible with Argo CD.

> helm-lookups by default also run quite permissive.

My understanding of Helm lookups is that they occur client-side. So the lookup permissions are identical to the client permissions. In a situation where you're running Helm on a laptop, that's fine. The Helm user isn't empowered to do anything they wouldn't otherwise be allowed to do. But if Argo CD runs Helm on the user's behalf, I think it's reasonable to expect Argo CD to enforce the same permission boundaries that it does for other activities (like syncing, updating, and deleting resources). Otherwise Argo CD becomes a backdoor to exfiklrate arbitrary resources.

> In fact it needs to be quite thoroughly documented in which ways the to-be-someday-released argocd lookups are affected by permission scope.

Well certainly all features need to be well documented, especially those which involve security boundaries.
