### ISSUE TITLE
Azure DevOps webhook basic auth verification failed" security=3

### ISSUE THREAD

**Issue by AndriySidliarskiy** [argoproj/argo-cd#16590]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
time="2023-12-11T12:24:47Z" level=info msg="Webhook processing failed: basic auth verification failed".

When I try to setup AzureDevops webhook it does not immediately it can take some time like 10 minutes or disable and enable webhook in Azure DevOps to solve it
**To Reproduce**
Create a code push webhook event with perform action post via HTTP
<img width="471" alt="image" src="https://github.com/argoproj/argo-cd/assets/62854979/28a6f389-fcd6-4d71-9f91-8a769809fbc9">

 and configure helm chart inside terraform like 
<img width="651" alt="image" src="https://github.com/argoproj/argo-cd/assets/62854979/9413c984-6b5a-4458-a000-3395f8f4719e">

**Expected behavior**

Webhook must work immediately without a timeout.
**Screenshots**

**Version**
latest
```shell
argocd v2.9.2+c5ea5c4 
```

**Logs**
e="2023-12-11T12:24:47Z" level=info msg="Azure DevOps webhook basic auth verification failed" security=3
time="2023-12-11T12:24:47Z" level=info msg="Webhook processing failed: basic auth verification failed"
```
Paste any relevant application logs here.
```

**Comment by todaywasawesome** [comment]
So the issue is that the webhook _does_ work, but not immediately? At first, the webhook fails to create because of the wrong credentials? Is this related to new pod rollout or something? I think you need to provide more information here, for example you show logs where it fails but more logs showing when it starts working would be helpful too. 

I'm not convinced this is an Argo bug.
