### ISSUE TITLE
Repo and cluster need an error field

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#169]
If repo or cluster credentials are bad, it should be denoted in the object itself for ease of debugging.

**Comment by merenbach** [comment]
@jessesuen no problem to add a field to `Cluster` and `Repo` objects.  Looking into the creation process, what would this change?

  * Returning the partly-formed object, rather than returning `nil`?
  * Since we're returning the error, is there somewhere else I should be looking to make this easier?
  * Is this just the contents of the error that would be returned alongside?
