### ISSUE TITLE
Sync operation unnecessary waits for a healthy state of all resources

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#1715]
**Describe the bug**
Sync operation unnecessary waits for a healthy state of all resources even if user has a single "wave"

**To Reproduce**
1. Sync any deployment which consist of a single wave.
2. Sync operation stays in running state until all resources are healty or degraded.

**Expected behavior**
The last waive should not wait for a healthy state of all resources. This is changing sync operation behavior.

**Version**: 1.1.0 (unreleased)

**Comment by alexec** [comment]
We should brainstorm this. 

Sync waves change how the op status is determined. 

At any point during a sync op, including post-sync, we can end up with a situation where we cannot continue (everything is degraded) or progressing (e.g a pod in crash loop backoff). We don't' differentiate recoverable (`crashloopbackoff`) from unrecoverable (`invalidimagename`), it means we can't tell if a degraded resource will become healthy. Because these situations, therefore, may resolve, the wave could become healthy, and the op continues. 

This could happen a long time after the sync is requested. (By "long" I mean, there'' Git commit that changes the app. 

This op will remain in progress until it is terminated:

![Screen Shot 2019-06-10 at 11 45 56](https://user-images.githubusercontent.com/1142830/59218537-59784700-8b75-11e9-9aa2-c75e765236cf.png)
