### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by magzim21** [argoproj/argo-cd#18377]
![CleanShot-2024-05-22-22 57 48](https://github.com/argoproj/argo-cd/assets/46382297/cadfb298-79b3-4594-9bea-3f1ba52c724b)

From server logs
`rpc error: code = PermissionDenied desc = error getting resource: deployments.apps "external-secrets" is forbidden: User "system:node:ip-10-0-0-81.ca-central-1.compute.internal" cannot get resource "deployments" in API group "apps" in the namespace "kube-system"`

**Comment by pasha-codefresh** [comment]
Can it be that you installed your ArgoCD instance inside kube-system ?

**Comment by agaudreault** [comment]
@magzim21 Closing due to missing details. When opening an issue, use the [Bug Report](https://github.com/argoproj/argo-cd/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) template or [Question](https://github.com/argoproj/argo-cd/discussions/new/choose). You can reopen the issue and add the missing details and context.

**Comment by magzim21** [comment]
Sorry for the late reply. That was due the argocd-server did not have permissions to connect to the external cluster (lost due to misconfiguration). I am using local cluster as if it is external.
