### ISSUE TITLE
Expose kustomize image overrides in CLI

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1843]
I was trying to help someone get pull request preview environment pattern working for a kustomize based app. The idea is that an image tag would be an application override in the Argo CD app. However, it turns out we don't expose kustomize image overrides as part of the CLI, which made this difficult because it forced us to use `argocd app create -f some-app.yaml` instead of `argocd app create --dest-server XXX --dest-namespace YYY --etc....`.

This request is to expose kustomize images as part of CLI to `app create` and `app set`, just like we already do for kustomize namePrefix.

**Comment by alexec** [comment]
can you use `app patch` for this?

**Comment by jessesuen** [comment]
No, `argocd app patch` is for patching application resources (e.g. deployments). What we are trying to do is to modify the application spec during app creation. The `create -f` lets us workaround the limitation, but it would have been better to be able to do this through CLI flags alone.

**Comment by alexec** [comment]
Um. I’m pretty sure it patched the app spec?

**Comment by thejmazz** [comment]
This works (hardcoded to array element, which is fine for single image apps, for multiple I don't know if order will be preserved). Also depends on an image previously being set.

```shell
argocd app patch myapp \
--patch '[{"op":"replace", "path": "/spec/source/kustomize/images/0", "value": "ubuntu:18.04"}]'
```

**Comment by jessesuen** [comment]
> Um. I’m pretty sure it patched the app spec?

Sorry, you're right, we have both:

```
  patch          Patch application
  patch-resource Patch resource in an application
```

But `app patch` is still not a good solution because the images are an array, and the patch payload is not well suited for that.

**Comment by alexec** [comment]
ah - you want to append to the array? you can do this using JSON patch, e.g. 

```
argocd app patch myapp \
--patch '[{"op":"add", "path": "/spec/source/kustomize/images/-", "value": "ubuntu:18.04"}]'
``

**Comment by thejmazz** [comment]
Imagine a kustomize app with 2 configurable images, and let's say CICD is set up so that on 2 different PRs, each commit builds a container and then patches the app to update it.

Either you would have to assume the ordering of `spec.source.kustomize.images` is consistent and then each PR is hardcoded to replace `images/0` and `images/1` or you would need a prestep which grabs current array and replaces items correctly, then replaces entire array.

Now, I don't think it should be ArgoCD's job to support all these specific use cases. I mean of course, its a neat feature, and perhaps more popular tools should get these options (jealous of the ksonnet --param settings, but I'm personally skipping on Ksonnet since it's been sunsetted). But at the end of the day the argocd CLI is basically a convenience for kubectl commands (please jump in if I'm mistaken and theres more to it than that).

I'm leaning towards writing our own custom logic which grabs current manifest, does some edits, and applies it back - at least in our situation I can see this pattern come up a lot (not just for argocd, e.g. may also want to patch Ingress resources in a complicated way) and so am leaning towards the "just write some function that knows how to do a specific edit on a specific resource and reapply" pattern.

Plus this way can maintain complete GitOps by committing instead of apply.

Just my $0.02 :)

**Comment by jessesuen** [comment]
> ah - you want to append to the array? you can do this using JSON patch, e.g.

> Either you would have to assume the ordering of spec.source.kustomize.images is consistent and then each PR is hardcoded to replace images/0 and images/1 or you would need a prestep which grabs current array and replaces items correctly, then replaces entire array.

Right. @thejmazz gave a great detailed explanation what I meant when I said "app patch is still not a good solution because the images are an array, and the patch payload is not well suited for that"

**Comment by alexec** [comment]
Maybe we move this to v1.3 after discussion.

**Comment by alexec** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/commands/edit/set/setimage.go

**Comment by alexec** [comment]
So, if you create the following patch:

```json
[
  {"op":"add", "path": "/spec/source/kustomize", "value": {"images": ["alpine:3.8"]}},
  {"op":"add", "path": "/spec/source/kustomize/images/-", "value": "alpine:3.9"},
  {"op":"add", "path": "/spec/source/kustomize/images/-", "value": "alpine:3.10"}
]
```

You get the following app:

```yaml
project: default
source:
  repoURL: 'file:///tmp/argo-e2e/testdata.git'
  path: kustomize
  kustomize:
    images:
      - 'alpine:3.8'
      - 'alpine:3.9'
      - 'alpine:3.10'
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd-e2e-test-kustomize-images-dpqge
```

Which results in `alpine` becoming `alpine:3.10`. 

So you can update images one after another.

**Comment by alexec** [comment]
I quite like the idea of having tool-specific sub-commands. E.g.

```bash
argocd app edit kustomize setimage ...
```

**Comment by alexec** [comment]
You may now use `argocd app set APPNAME --kustomize-image IMAGE`.
