### ISSUE TITLE
After clicking the SYNC button on the ArgoCD Dashboard, Git changes are not being synchronized.

### ISSUE THREAD

**Issue by jungjuyoung2023** [argoproj/argo-cd#18885]
Checklist:

* [v] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `argocd version`.

**Describe the bug**

After clicking SYNC in ArgoCD, Git changes are not synchronized. The live state does not match the target state, and the changes are not reflected immediately. As a result, PODs are created but then revert to the previous state.

**To Reproduce**

1. Changes are made in Git.
2. SYNC is clicked in the UI.
3. A POD is created. -> Kubernetes Resource changes to the target state.
4. The manifest in the UI does not reflect the changes from Git.
5. The newly created POD immediately disappears.
6. When the refresh interval occurs, synchronization completes and the POD is created again.

What settings should be adjusted to resolve this issue?

**Expected behavior**
When SYNC is clicked, the current state should be compared to the target state, and changes should be applied accordingly.

**Version**

argocd version 2.5.0 

**Screenshots**
https://github.com/argoproj/argo-cd/assets/129713013/81fe1128-0f3f-48b6-84bf-7bfeb78059b4

**Comment by ChristianCiach** [comment]
Version v2.5.0 is almost two years old and has had multiple patch releases. Can you reproduce the issue with a recent version?

**Comment by jungjuyoung2023** [comment]
@ChristianCiach 
We have upgraded from version 2.0.0 to 2.5.0. In the previous version, when we clicked SYNC, it adjusted to the desired state as modified in Git.

After upgrading to 2.5.0, we tested version 2.0.0 on another cluster, and it worked fine. Currently, our Kubernetes version is v1.21.0, so we cannot upgrade to the latest version.

Is there any way to mitigate this issue through configuration settings?

**Comment by christianh814** [comment]
What you're describing is the expected behavior. You need to change the timeout in the Argo CD ConfigMap [as described in the docs](https://argo-cd.readthedocs.io/en/stable/faq/#how-often-does-argo-cd-check-for-changes-to-my-git-or-helm-repository). This is set to every 3 minutes and can be changed by setting the following in the `argocd-cm` ConfigMap

```yaml
data:
  timeout.reconciliation: 180s
```

Although I'd **HIGHLY** recommend clicking "Refresh" or "Hard Refresh" instead of "Sync" or set up. You can also automate this by either using the `argocd` CLI to do a sync/refresh when a change is made in git or use `kubectl` and annotate the Application resource with `argocd.argoproj.io/refresh` as described [HERE](https://argo-cd.readthedocs.io/en/stable/user-guide/annotations-and-labels/)

**Comment by andrii-korotkov-verkada** [comment]
You can also set up webhooks to inform argocd on updates in Git and trigger refresh quickly without waiting for 3 min.
