### ISSUE TITLE
Add `/home/ubuntu/.kube/cache` and `/tmp` mounts for the app controller

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#19474]
# Summary

Update the manifests to include mounts for `/home/ubuntu/.kube/cache` and `/tmp`

# Motivation

When the root file system is configured read-only for security purposes the cache can't be used and there are logs about inability to store things there when `gloglevel` is set to 6. Not sure about a need for `/tmp` but can add just in case too.

# Proposal

Update the manifests to add empty dir volumes and mount them to the app controller.

**Comment by ChristianCiach** [comment]
It may be worth mentioning that, when using the ["Security hardened images" by Akuity](https://akuity.io/blog/security-hardened-argocd/), the path would be `/home/argocd/.kube/cache` instead of `/home/ubuntu/.kube/cache`.

In fact, this PR would introduce the first and only mention of the word "ubuntu" in all of the installation manifests, and I don't know if that's desirable.

Maybe it would be better to add `KUBECACHEDIR` (see https://github.com/kubernetes/kubernetes/pull/109479) and set it to `/tmp/kubecache` oder something?
