### ISSUE TITLE
HA Manifest - error converting YAMLto JSON

### ISSUE THREAD

**Issue by xelab04** [argoproj/argo-cd#20532]
Checklist:

[* ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
[* ] I've included steps to reproduce the bug.
[   ] I've pasted the output of `argocd version`.

**Describe the bug**

Yaml file provided appears to be invalid.
```
error parsing https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml: error converting YAML to JSON: yaml: line 216: mapping values are not allowed in this context
```
**To Reproduce**

```
kubectl apply -n argocd -f https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml
```

**Expected behavior**

Manifest is applied properly and all resources are created.

**Version**

Not applicable

**Comment by MaroIT** [comment]
Is there any patch for this bug?

**Comment by andrii-korotkov-verkada** [comment]
I don't know the exact issue, but see some lines where there's a multiline statement without any special char like | or |> before the value, e.g. https://github.com/argoproj/argo-cd/blob/5d0a3e6e9abd7e922e72e27c992ed0cdc0824f99/manifests/ha/install.yaml#L219-L220. This seems like a rendering issue. Do you have some minimal repro?
If not, I can try to avoid this kind of rendering, since I guess different Yaml parsers can have an issue with that.

**Comment by andrii-korotkov-verkada** [comment]
There's this issue https://github.com/kubernetes-sigs/kustomize/issues/947

**Comment by andrii-korotkov-verkada** [comment]
I've found a way to fix it, following advice from https://stackoverflow.com/questions/45004464/yaml-dump-adding-unwanted-newlines-in-multiline-strings/45004775#45004775 and modifying the repr to also apply literal style if the length of the value is > 40. I'll send a fix soon.

**Comment by andrii-korotkov-verkada** [comment]
Ah, when I use kustomize it apparently uses a regular type of the formatter, so the combined manifests are not getting updated. I either need to fix kustomize or have a hacky script to normalize all manifests.

**Comment by andrii-korotkov-verkada** [comment]
Seems like ArgoCD repo doesn't have Python files as of now, so not sure adding that is a good idea. I'll try and see if I get rejected.

**Comment by andrii-korotkov-verkada** [comment]
Python used to be there, but got removed.

**Comment by andrii-korotkov-verkada** [comment]
Hm, though manifests update script are local only, so I think it'd be okay to use Python script.

**Comment by andrii-korotkov-verkada** [comment]
@xelab04, can you try to load my branch and apply the manifests, please?

**Comment by crenshaw-dev** [comment]
@xelab04 the problem is that you're applying the GitHub page for install.yaml, not install.yaml itself.

To demonstrate the problem, try this:

```shell
wget https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml
kubectl apply -n argocd -f install.yaml
less install.yaml
```

The first two commands should produce the same error as what you got. The last command should show that the file you're trying to apply is HTML rather than YAML.

Use the raw install.yaml link:

```shell
kubectl apply -n argocd https://raw.githubusercontent.com/argoproj/argo-cd/refs/heads/master/manifests/ha/install.yaml
```
