### ISSUE TITLE
Argocd app Sync is taking time

### ISSUE THREAD

**Issue by shnigam2** [argoproj/argo-cd#20786]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

 When we are simply syncing any apps it is taking lots of time. 

**To Reproduce**

 We just simply need to sync any app, it will take more than 20 mins for sure even if there is no change.

**Expected behavior**

 In other environment it is getting synced in not more than 2 mins.

**Screenshots**
<img width="833" alt="image" src="https://github.com/user-attachments/assets/5e53e09a-b93a-4630-afa0-0bd33d4f53a5">

 We just simply need to trigger the sync of any app, it is taking upto 1-1.5Hrs.

**Version**

```shell
argocd: v2.5.1+504da42
  BuildDate: 2022-11-01T21:14:30Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrii-korotkov-verkada** [comment]
What's your argocd server version?
What kind of sync are you talking about? If there are a lot of steps and for example Rollouts with long canaries, sync is expected to take a while. Does it get stuck?

**Comment by andrii-korotkov-verkada** [comment]
That might be a cli version. Do you have an output for argocd-server? Is it also old? If so, please, try upgrading.

**Comment by jimmy-daruwala** [comment]
Sure Andrii, PS the argocd-server version below:
jimmy_daruwala@M-TFX2T4PV62 ~ % argocd version --client
2024/11/13 22:04:52 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
**argocd: v2.13.0+347f221**
  BuildDate: 2024-11-04T15:30:50Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.2
  Compiler: gc
  Platform: darwin/arm64

**Comment by andrii-korotkov-verkada** [comment]
I see. Can you share the resources yamls you are syncing, please? In particular, if you have rollouts with long canaries.

**Comment by jimmy-daruwala** [comment]
Hi Andrii, was not quite sure which yaml's I should provide. So had to consult with my team. 

But PS the scrrenshots I attached that describe which repo we are using and what resources are being used in that repo for the issue at fault. Just to put issues forward again:
Issue 1 - App takes long time to SYNC. Especially "my-app-converge-12126". 
Issue 2 - When we select "my-app-converge-12126" Application in Argo. The whole Argo UI gets glitchy and after few seconds it gives "Page Unresponsive" Message. This issue is pretty consistent. PS the screenshot for this as well. But for all other apps Argo UI runs fine and we do not see "Page Unresponsive" error. Another note: it is happening only on this Cluster. 

I am also attaching resource usage screenshots below, that would tell us that this could not be a result of resource overload (For argocd and ns-converge-12126-prod both). 

Please let us know if we can arrange a quick meeting to discuss its resolution. Or if you need any more details. 

![Screenshot 2024-11-18 at 2 16 18 PM](https://github.com/user-attachments/assets/a1db497e-bb3e-4df6-9a62-e6c9313044b5)
![Screenshot 2024-11-18 at 2 07 55 PM](https://github.com/user-attachments/assets/ca3ee353-a619-4253-a106-8d82fc3f4c62)
![Screenshot 2024-11-18 at 2 08 08 PM](https://github.com/user-attachments/assets/53d1b7fc-920c-428f-a196-43d6ebb5a93f)
![Screenshot 2024-11-18 at 2 09 04 PM](https://github.com/user-attachments/assets/b0568e7e-b13a-42b5-a949-2ab2440e079f)


![Screenshot 2024-11-18 at 1 55 19 PM](https://github.com/user-attachments/assets/25527837-4875-4fa0-b159-18eb8db2bd50)
![Screenshot 2024-11-18 at 1 55 50 PM](https://github.com/user-attachments/assets/05b3b494-2b78-4f9a-9d9c-5a8bcf903d01)

**Comment by ibrarahmed1124** [comment]
Hi Andril. We are using argocd version 2.5.1
Please let me know what resources YAML files is required.

**Comment by andrii-korotkov-verkada** [comment]
The Yamls which define application resources.

**Comment by jimmy-daruwala** [comment]
Hi Andrii, the application team unfortunately can not allow to post the yaml files here in the open forum. 

To put issues forward again:
Issue 1 - App takes long time to SYNC. Especially “my-app-converge-12126”.
Issue 2 - When we select “my-app-converge-12126" Application in Argo. The whole Argo UI gets glitchy and after few seconds it gives “Page Unresponsive” Message. This issue is pretty consistent. PS the screenshot for this as well. But for all other apps Argo UI runs fine and we do not see “Page Unresponsive” error. Another note: it is happening only on this Cluster.
The resource usage for all the nodes as well as pods in question seems normal as well, that would tell us that this could not be a result of resource overload (For argocd and ns-converge-12126-prod both).
Please let us know if we can arrange a quick meeting to discuss its resolution. Or if you need any more details.

![Screenshot 2024-11-18 at 2 16 18 PM](https://github.com/user-attachments/assets/38f06771-ba02-4ca2-a9ba-7798eeb49e2f)

**Comment by jimmy-daruwala** [comment]
When trying to reproduce this issue, only thing I could find in the argocd-server pods logs was this error:

level=error msg="finished unary call with code Unknown" error="error getting cached app state: error getting application by query: application refresh deadline exceeded" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2024-11-20T04:58:28Z" grpc.time_ms=60000.188 span.kind=server system=grpc
2024-11-20T00:00:17-05:00 time="2024-11-20T05:00:17Z" level=info msg="received unary call /application.ApplicationService/ResourceTree" grpc.method=ResourceTree grpc.request.claims="{\"aud\":\"argocd\",\"email\":\"Karthikeyan_Sekar@mckinsey.com\",\"exp\":1732079857,\"iat\":1732078657,\"iss\":\"https://prod-login-con01.intranet.mckinsey.com/auth/idp/k8sIdp\",\"jti\":\"T9qDumUGC2KvnFvEx6LnTw\",\"name\":\" Sekar\",\"nbf\":1732078537,\"nonce\":\"4ba21011-3b96-406d-9d05-2f9773942d5e\",\"preferred_username\":\"x-48-xx-48-xufx-54-xgyrgngx-56-xnkx-50-xvbx-51-xx-53-xx-54-x\",\"sub\":\"00uf6gyrgnG8nK2Vb356\"}" grpc.request.content="applicationName:\"my-app-converge-12126\" appNamespace:\"argocd\" " grpc.service=application.ApplicationService grpc.start_time="2024-11-20T05:00:17Z" span.kind=server system=grpc
2024-11-20T00:00:17-05:00 time="2024-11-20T05:00:17Z" level=info msg="Requested app 'my-app-converge-12126' refresh"

Not sure if it's related.

**Comment by andrii-korotkov-verkada** [comment]
Can you try to enter the browser's developer mode and debug what's stalling the page?
One case where I saw this is when an app had like 5k old jobs. I manually cleaned up those and things started to load well again.

**Comment by jimmy-daruwala** [comment]
I did not find anything valuable in developer mode. PS the screenshot. 
  
  Interesting. How can we check on old (stale or stuck) jobs that do need cleaning up?
  Compared to other clusters, it takes long time to sync almost any app here, not just the one with issue. So we can try this option. 
  
![Screenshot 2024-11-20 at 1 46 11 PM](https://github.com/user-attachments/assets/813de138-9e0f-4e51-ba85-d768e3345d7d)

**Comment by andrii-korotkov-verkada** [comment]
> How can we check on old (stale or stuck) jobs that do need cleaning up?

You can use kubectl and query by label of resources belonging to the app. Something like
```
kubectl get jobs -l app.kubernetes.io/instance=my-app
```
But not sure what exact annotation you have for tracking belonging to the app.

**Comment by jimmy-daruwala** [comment]
Posting the same above comments without SS. 

Hi Andrii, the application team unfortunately can not allow to post the yaml files here in the open forum.
To put issues forward again:
Issue 1 - App takes long time to SYNC. Especially “my-app-converge-12126”.
Issue 2 - When we select “my-app-converge-12126" Application in Argo. The whole Argo UI gets glitchy and after few seconds it gives “Page Unresponsive” Message. This issue is pretty consistent. But for all other apps Argo UI runs fine and we do not see “Page Unresponsive” error. Another note: it is happening only on this Cluster.
The resource usage for all the nodes as well as pods in question seems normal as well, that would tell us that this could not be a result of resource overload (For argocd and ns-converge-12126-prod both).

As also discussed, we found nothing valuable in Developer mode when reproducing the issue.

I will check on the jobs as you requested above.

**Comment by jimmy-daruwala** [comment]
I actually tried finding all the jobs in all NS's in the cluster and only got this:
jimmy_daruwala@M-TFX2T4PV62 .aws % kubectl get jobs -A 
NAMESPACE                   NAME                              STATUS     COMPLETIONS   DURATION   AGE
argocd                      container-secret-sync-28868790    Complete   1/1           8s         40m
argocd                      container-secret-sync-28868805    Complete   1/1           7s         25m
argocd                      container-secret-sync-28868820    Complete   1/1           8s         10m
argocd                      splunk-sync                       Complete   1/1           7s         96d
namespace-operator-system   snow-registration-28785600        Complete   1/1           8s         57d
namespace-operator-system   snow-registration-28787040        Complete   1/1           7s         56d
namespace-operator-system   snow-registration-28788480        Complete   1/1           9s         55d
namespace-operator-system   snow-registration-28867680        Failed     0/1           19h        19h
openunison                  check-certs-openunison-28864920   Complete   1/1           10s        2d17h
openunison                  check-certs-openunison-28866360   Complete   1/1           11s        41h
openunison                  check-certs-openunison-28867800   Complete   1/1           10s        17h

**Comment by jimmy-daruwala** [comment]
Any next steps, or any other suggestions regarding this?
Happy to set up a call between us and the App team as well.

**Comment by jimmy-daruwala** [comment]
Hi Andrii, we tried enabling debug logs but could not find anything useful there as well. There were no "Reconciliation Completed" logs found.

**Comment by jimmy-daruwala** [comment]
Is it possible for us to get on a call tomorrow to troubleshoot this together?

**Comment by andrii-korotkov-verkada** [comment]
> There were no "Reconciliation Completed" logs found.

That's odd, the application controller should have a lot of those as info logs.

> Is it possible for us to get on a call tomorrow to troubleshoot this together?

Maybe not yet, but feel free to ping me on CNCF Slack, I'm Andrii Korotkov (Verkada) there. The thing is we need more data and some time gathering it. Try sharing all the logs related to the given application from application controller.

**Comment by andrii-korotkov-verkada** [comment]
Did you restart the controller after updating the cm?

**Comment by ibrarahmed1124** [comment]
After making changes into the configmap argocd-cmd-params-cm, we have restarted the ArgoCD components.
Now, we have enabled one more logging change into the sts argocd-application-controller YAML file to check if we get the right logs.


spec:
      containers:
      - command:
        - argocd-application-controller
        - --loglevel
        - debug

Do we need to enable any debug logging with argocd-applicationset-controller ?

**Comment by andrii-korotkov-verkada** [comment]
Thanks for confirming. You don't need 
```
- --loglevel
- debug
```
if you have cm changes.

Let's just try to get all the logs relevant for the given application.

**Comment by ibrarahmed1124** [comment]
We have below events in the log related to "Reconciliation completed" 

time="2024-11-27T09:52:05Z" level=info msg="Reconciliation completed" application=argocd/my-app-converge-12126 dedup_ms=0 dest-name= dest-namespace=ns-converge-12126-prod dest-server="https://kubernetes.default.svc" diff_ms=303 fields.level=2 git_ms=336 health_ms=9 live_ms=103 settings_ms=0 sync_ms=0 time_ms=1320168

**Comment by andrii-korotkov-verkada** [comment]
From discussions with two people, it seems like the reason is slow reconciliation. Please, upgrade to v2.13, which had drastic improvements to reconciliation performance, in particular for medium+ size clusters. Also, there's more timing information and debug logs.

**Comment by andrii-korotkov-verkada** [comment]
Check out these for more context of what the issue was:
* https://github.com/argoproj/argo-cd/issues/18500
* https://github.com/argoproj/argo-cd/issues/18217
* https://github.com/argoproj/argo-cd/issues/18929

**Comment by jimmy-daruwala** [comment]
Hi @andrii-korotkov-verkada ,

Wanted to update you on this. We performed Argo upgrade for this Cluster with issues mentioned above to v2.9.20. After few weeks of monitoring, we still see the same sync issues. And same below error from before:
_Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unavailable desc = error reading from server: EOF_

After more research and discussion from app team, They mentioned they have similar DEV env which is mirrored like Prod. But they see this issue only in Prod. Let me know if now would be a good time to get on a call after this upgrade.
