### ISSUE TITLE
Syncing sources in multi-source application depends on order of sources in spec.

### ISSUE THREAD

**Issue by mteodor** [argoproj/argo-cd#20791]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Getting errors when trying to sync multi source application depending on the order of sources specifed.

**To Reproduce**
Hi All,
I have a question regarding sync for multi source application, i have app defined as follows:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mirko-app1
spec:
  destination:
    namespace: mirko-app1
    server: https://kubernetes.default.svc/
  project: default
  sources:
  - ref: values
    repoURL: https://github.com/mteodor/argocd-example-apps
    targetRevision: multi-source
  - chart: nginx
    helm:
      valueFiles:
      - $values/helm-values/nginx-values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.0
  syncPolicy:
    syncOptions:
    - PrunePropagationPolicy=undefined
    - CreateNamespace=true
    - Validate=true
  ```
```shell
argocd app sync mirko-app1 --revisions multi-source --source-positions 1                                                                                          
FATA[0002] rpc error: code = FailedPrecondition desc = error resolving repo revision: rpc error: code = Unknown desc = invalid revision 'multi-source': improper constraint: multi-source  
```
For position 2 it works
```shell
argocd app sync mirko-app1 --revisions 18.1.2 --source-positions 2
TIMESTAMP                  GROUP                    KIND            NAMESPACE                  NAME    STATUS    HEALTH            HOOK  MESSAGE
2024-11-13T18:07:54+01:00  networking.k8s.io  NetworkPolicy        mirko-app1      mirko-app1-nginx  OutOfSync                           
2024-11-13T18:07:54+01:00  policy             PodDisruptionBudget  mirko-app1      mirko-app1-nginx  OutOfSync                           
2024-11-13T18:07:54+01:00                         Secret           mirko-app1  mirko-app1-nginx-tls  OutOfSync                           
2024-11-13T18:07:54+01:00                        Service           mirko-app1      mirko-app1-nginx  OutOfSync  Progressing              
2024-11-13T18:07:54+01:00                     ServiceAccount       mirko-app1      mirko-app1-nginx  OutOfSync   
.....
```
Now if i define application `mirko-app2` with sources in reverse order, where helm is now on 1st pos again I'm getting an error when trying to sync on 1st position
```shell
argocd app sync mirko-app2 --revisions 18.1.2 --source-positions 1
FATA[0003] rpc error: code = FailedPrecondition desc = error resolving repo revision: rpc error: code = Unknown desc = Unable to resolve '18.1.2' to a commit SHA
```

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd version
argocd: v2.12.4+27d1e64
  BuildDate: 2024-09-26T09:31:42Z
  GitCommit: 27d1e641b6ea99d9f4bf788c032aeaeefd782910
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T11:57:48Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.4.2 2024-05-22T15:19:38Z
  Helm Version: v3.15.2+g1a500d5
  Kubectl Version: v0.29.6
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by andrii-korotkov-verkada** [comment]
In the application, you specify `targetRevision: 18.2.0`, but in the cli you specify `18.1.2`

**Comment by andrii-korotkov-verkada** [comment]
However, I'm not sure, maybe it's supposed to override.

**Comment by mteodor** [comment]
@andrii-korotkov-verkada it should override
when looking in the history it clearly shows it synced to revision used in sync command
```
argocd app sync mirko-app1 --revisions 18.1.3 --source-positions 2
```
<img width="1711" alt="image" src="https://github.com/user-attachments/assets/9f1c8e74-ed83-4d35-a43f-50e3f7853ed7">


while source is in spec is set to 18.2.0
<img width="1697" alt="image" src="https://github.com/user-attachments/assets/7db27f95-43e9-4ecb-bb6c-98980f89564b">

**Comment by guillaume-roland-sre** [comment]
Hi there,

I have the exact same issue. I don't think the order matter, I think it's more that ArgoCD is validating the first `targetRevision` in each of the sources.
So it will try to validate that `multi-source` exist in `https://charts.bitnami.com/bitnami`.

When you do that:
```
argocd app sync mirko-app1 --revisions multi-source --source-positions 1                                                                                          
```
ArgoCD will try to find `multi-source` in both repo and that's failing.

When do you that:
```
argocd app sync mirko-app1 --revisions 18.1.2 --source-positions 2
```
It seems it force ArgoCD to look for the correct revision in the source 2 (without the override, it would look for `multi-source`)

When you do:
```
argocd app sync mirko-app2 --revisions 18.1.2 --source-positions 1
```
It override `18.2.0` with `18.1.2`, but ArgoCD is still looking for `18.1.2` in `https://github.com/mteodor/argocd-example-apps`, so it's failing.

The workaround here is the second command you ran, to force the revision on the source position 2, but it's not possible in the UI, so it's still a blocker.

Thanks.

**Comment by andrii-korotkov-verkada** [comment]
This commit might be relevant https://github.com/argoproj/argo-cd/commit/a624c9084582f4662a9c6919cdf055000b09fad0. Not sure it fixes this specific issue, but worth a shot. Can you upgrade to 2.13 and see if the issue still happens, please?

**Comment by andrii-korotkov-verkada** [comment]
There might be a bug with getting ambiguous revision here https://github.com/argoproj/argo-cd/blob/master/server/application/application.go#L2219-L2223, since positions start from 1 and I think indexes start from 0. Let me confirm, though not sure it's related.

**Comment by andrii-korotkov-verkada** [comment]
@ishitasequeira, can you check the above and see if it's indeed a bug, please?

**Comment by mteodor** [comment]
@andrii-korotkov-verkada same happens with v2.13.0

**Comment by andrii-korotkov-verkada** [comment]
I'll bring this up during contributors meeting at some point.

**Comment by mteodor** [comment]
@andrii-korotkov-verkada most probably fix is here https://github.com/argoproj/argo-cd/blob/master/server/application/application.go#L2232
built it localy and whenchanged it to
```
for i, pos := range syncReq.SourcePositions {
			if pos == int64(sourceIndex+1) {
				ambiguousRevision = syncReq.Revisions[i]
			}
		}
```
i wasnt getting errors on sync

**Comment by CefBoud** [comment]
I believe the code path is as follows:

1. [Sync](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L1905-L1906)
2. [resolveSourceRevisions](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L1937-L1938)
3. [resolveRevision](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L2030-L2031)
4. [getAmbiguousRevision](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L2255-L2256)

Step 3 (resolveRevision) is called for all the sources regardless of their presence in the `SyncRequest`.  The issue as unveiled by @mteodor previous comment is that there is a mismatch between the source-position (1-indexed) in the API and the actual source position (0-index). So whenever we try to sync source-position 1 (1-index i.e. actual 0) with a certain ref, it is source position 2 (actually 1) that ends up being tied to that ref and this is when the error occurs.

The command works for source-position 2 (1-indexed), because there is no actual position 2 (0-indexed) and we end up [defaulting to the TargetRevision](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L2237-L2238). Fortunately, the `TargetRevision` has the [correct desired ref](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L2022-L2023).

I think the suggested change in the previous comment should fix the problem. An alternative could be to set the `TargetRevision` in the single source case in `resolveSourceRevisions` as it is already done in the multi-source case and do away with `getAmbiguousRevision` and rely on `TargetRevision` instead.

**Comment by blakepettersson** [comment]
@mteodor or @CefBoud any of you mind creating a PR for this with tests?

**Comment by ishitasequeira** [comment]
@mteodor Apologies for getting a bit late to this. I was out of office for last week and was catching up with things.

You are right. The issue is that it is looking for the index instead of converting it to a position when checking `pos == int64(sourceIndex)` [here](https://github.com/argoproj/argo-cd/blob/83953fe276846924da95f997fc14ff07180fcd71/server/application/application.go#L2232C7-L2232C32).

The fix suggested by @mteodor above should fix the issue. 

```
if pos == int64(sourceIndex+1) {
    ambiguousRevision = syncReq.Revisions[i]
}
```

I have raised a quick PR to fix this https://github.com/argoproj/argo-cd/pull/21071
