### ISSUE TITLE
[SPIKE] Design API to create system users

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-cd#228]
Need an API to create users to deploy automatically from an external pipeline

**Comment by dthomson25** [comment]
Here is an overview of the design we are envisioning: 

- The CLI will support the following commands:
```
argocd proj token create <project> <token> [--expiresAt <epoch time>]
argocd proj token delete <project> <token>
argocd proj token create-policy <project> <token> --action <action> --object <object> [--permission permission]
argocd proj token delete-policy <project> <token> --action <action> --object <object> [--permission permission]
```
- A user will be able to create a project token by running `argocd proj token create <project> <token> --expiresAt <epoch time>` on the CLI.  This will send a request to the API server to sign and return a JWT token with a role `proj:<projectName>:<tokenName>` and an expiration time.  During the token creation, the server will also store the metadata of the token within the project CRD.  Each token metadata struct will store a string array of policies definition that can be used to allow access to resources with the project and a createAt field to track when the token was created.
 - A user will be able to add a policy to an existing token by running `argocd proj token create-policy <project> <token> --action <action> --object <object>`,  and the API server will update the project CRD's token metadata with that the policy string created from the inputs.  
- If a user calls the API server with the project token, the API server will generate a temporary casbin enforcer with all the policies from the tokens stored in the project CRD. The API server will detect that the request is a project token by checking the subject field for the `proj:` prefix and confirm that the token has the same createdAt time stored in the token metatdata to prevent a recreated token from having the same permissions.  Note: in order to generate the temporary casbin enforcer, we will to query the project CRD for every permission check we make with a project token.  We decided that the overhead was insignificant considering that we already are doing similar actions in other places.  The alternative was to have a background process tracking any changes to the project, but we decided adding that extra complexity was not worth the benefits.

I have a MVP with the create token and create policy for token functionality implemented so far.  You can take a look at https://github.com/dthomson25/argo-cd/tree/project-tokens to see the current implementation I have so far.
