### ISSUE TITLE
Make `group` optional for `ignoreDifferences` config

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#2298]
**Is your feature request related to a problem? Please describe.**

Got a warning when applying `ignoreDifferences` setting in `Application`

```
spec.ignoreDifferences.group in body is required
```

**Describe the solution you'd like**

Make `group` optional with default value `core`

**Have you thought about contributing yourself?**

Yes

**Comment by alexmt** [comment]
Good catch! Group definitely should be optional. I think the default should be empty string though, not `core`.  Empty string as default looks less surprising. @yujunz what do you think?

**Comment by yujunz** [comment]
Empty string looks good to me.

**Comment by yujunz** [comment]
It seems `group` is optional in protobuf as defined in https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L60

Where does the warning message come from. Could you please shed some light on it? @alexec @alexmt

**Comment by alexmt** [comment]
I think the error happens because of `group` field is marked as required in application CRD validation section: https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml#L637


The CRD definition is auto-generated using `controller-gen` from `sigs.k8s.io/controller-tools` package ( `make codegen` command ). It marks field as readonly unless json serialization annotation has `omitempty`.

So to fix the issue we need to add `omitempty` ( e.g. `json:"group,omitempty" protobuf:"bytes,1,opt,name=group"`) and run `make codegen` to regenerate CRDs
