### ISSUE TITLE
Print version in interface

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#2483]
## Summary

It's not possible when looking at screenshots to know what version of Argo CD someone is using.

## Motivation

I'd like to see the version when debugging problems.

## Proposal

Burn it into the UI.

**Comment by alexec** [comment]
@alexmt I'd like to include this in v1.4. Thoughts?

**Comment by alexmt** [comment]
Totally agree. I would print both UI and API version. Sometimes error happens because of backend and UI have different versions due to bad upgrade. The UI version is available via `SYSTEM_INFO.env.ARGO_VERSION`  global JS variable. It is injected by webpack plugin: https://github.com/argoproj/argo-cd/blob/ec142a1031359caaae3016fcf286d2f7c2cd7d3a/ui/src/app/webpack.config.js#L59
