### ISSUE TITLE
Remove `argocd (un)install` into argocd-util

### ISSUE THREAD

**Issue by merenbach** [argoproj/argo-cd#254]
Because they require direct access to Kubernetes, these commands should not be in `argocd`, but rather `argocd-util`.

**Comment by JazminGonzalez-Rivero** [comment]
Goals for this ticket:

1) move namespace and CRD generation to be handled by kubectl apply -f
- move manifest directory so it is no longer under install (for customer clarity
- uninstall will be handled by kubectl delete

2) handle secret / password generation at server startup
- use the pod name to create the password, this will make it more secure

3) create API endpoint (profile?) backed by server that allows for overwriting the admin password
- If we go with this model, this would also allow you to change the password of any other profile since admin will be treated like any other just with a special name

**Comment by jessesuen** [comment]
1 and 2 are completed. 3 is being handled in https://github.com/argoproj/argo-cd/issues/377
