### ISSUE TITLE
ArgoCD RBAC for a private repository may cause a permission violation. 

### ISSUE THREAD

**Issue by llamerada-jp** [argoproj/argo-cd#2647]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I think ArgoCD RBAC may cause a permission violation.
A user who isn't permitted to access a private repository can create or sync applications using the repository.

**To Reproduce**

* Enable SSO with GitHub.
* Add a private repository to resources.

```
$ argocd repo add https://github.com/<git user name>/<**NOT ALLOWED** repository> --username <user name>
```

* Remove default policy like below.

```
$ kubectl get cm argocd-rbac-cm -n <your namespace> -o yaml
apiVersion: v1
data:
  policy.csv: ""
  policy.default: ""
```

A user cannot see the repository by `argocd repo list` command in this situation.

```
$ argocd repo list
REPO                                      INSECURE  LFS    USER      STATUS      MESSAGE
(No output.)
```

* Create an application using the **NOT ALLOWED** repository with CLI.

```
$ argocd app create testapp --project <project name> \
    --repo https://github.com/<git user name>/<**NOT ALLOWED** repository>/ \
    --path <path> \
    --revision HEAD \
    --dest-server https://kubernetes.default.svc \
    --dest-namespace <namespace>
```

* Start sync by `argocd sync` command.

```
$ argocd app sync testapp
```

The status of the application will be `Synced`.

```
$ argocd app list
NAME         CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS                REPO                                                    PATH       TARGET
...
testapp      https://kubernetes.default.svc  <namespace> <project name> Synced     Healthy  <none>      <none>                    https://github.com/<git user name>/<**NOT ALLOWED** repository>                    argocd     HEAD
...
```

**Expected behavior**

Creating/synchronizing the application should be rejected because the user didn't have permission.

**Screenshots**

None.

**Version**

```shell
argocd: v1.2.2+1aaf76f
  BuildDate: 2019-09-24T19:19:32Z
  GitCommit: 1aaf76f2303507479a9087e35be2b813eef316f2
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.2.5+unknown
  BuildDate: 2019-10-31T09:55:54Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.13.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Please see the section 'To Reproduce'.

**Comment by alexec** [comment]
Let me get this straight:

* You add a repo to Argo CD and create an app pointing at that repo.
* You change RBAC to deny the user sync permission on that repo.
* The user can still sync?

**Comment by alexec** [comment]
@jessesuen can I get your thoughts on this? The suggestion here is that you should not be able to sync an app, if you do not have permission to read that app's source repo.

I wonder if this is to do with  does the 'repository' permission mean?

**Comment by jannfis** [comment]
I was under the impression that the RBAC rules only authorize the API requests, i.e. "Get" on repository controls whether you can get detailed repository information. There is no sync permission for repositories.

For actual usage of the repositories to sync an app from, the allowed source repositories list for a project would be where the permission to use a repository stems from.

**Comment by alexec** [comment]
I've discussed with @jessesuen and @alexmt and this is expected behavior.

That permission is specifically for whether or not you can edit repositories in settings. 

To control which repositories an app can use, you can use the projects feature.

**Comment by llamerada-jp** [comment]
Thank you for your reply.

In my situation, I using single ArgoCD with some teams(projects) on a Kubernetes cluster.
I want to deny create and sync using other team's private repository.
And every team is allowed using any other unlimited repositories. 

Currently, I should add entries to the white list for every repository using `sourceRepos`.
Does anyone have some simple way of excluding special repositories in each project like the blacklist?

**Comment by jannfis** [comment]
I think excluding repositories to sync from while allowing everything else is not possible in the current implementation.

What I imagine could be implemented is a new option for a project, "Only allow private repositories that are explicitly configured", so that you could have a whitelist as in

```
https://yourserver/repos/private/repo1
https://yourserver/repos/private/repo2
*
```
It would have to perform whitelisting matching against requested repo as follows:
- is requested repo configured in ArgoCD as private repository and knob mentioned above is true
- if yes, do not perform a glob match (i.e. do not match against patterns) but match on complete strings on the whitelist to figure out whether sync to this repo is allowed
- if no, perform standard glob matching (i.e. also match on `*` and the like)

Given three private repos `https://yourserver/repos/private/repo1`, `https://yourserver/repos/private/repo2` and `https://yourserver/repos/private/repo3` would be configured with ArgoCD, the first two would be allowed while the third one would not be. Also, every repository not explicitly configured as a private repository in ArgoCD (such as `https://github.com/argoproj/argocd-example-apps`) would match on the `*` wildcard and thus, would be allowed.

However, this would require an enhancement proposal and I'm unsure whether it makes sense from an architectural point of view.

**Comment by llamerada-jp** [comment]
Thank you for your reply, @jannfis .
I recognized it is not implemented blacklist of repositories currently.
I use the whitelist to control repositories and will try to operate the system.

**Comment by jannfis** [comment]
OK, thanks for the update. Closing the issue then. Feel free to open enhancement request.
