### ISSUE TITLE
namespace not respected when purge-syncing a project via app.kubernetes.io/instance

### ISSUE THREAD

**Issue by bbortt** [argoproj/argo-cd#2650]
**Describe the bug**

We tried syncing a project with the annotation `app.kubernetes.io/instance: a` in `deployment.yaml` into namespace x.

As we soon found out there was a pvc deployed via traditional `kubectl` into another namespace y also being annotated with `app.kubernetes.io/instance: a`. And `argocd` tried to purge it away. Lucky us, we had working permissions coming into action and `argocd` reported an error.

In fact, `argocd` did override the `app.kubernetes.io/instance` according to the project name, but that's not a matter of fact and we already learned about the possibility to override it.

**To Reproduce**

* Create different `delete` permissions for two namespaces named x and y. `read` is allowed for both of them.
* Deploy something (a pvc in our case) into namespace y, make sure it is annotated with `app.kubernetes.io/instance: a`. Do not use `argocd` for this.
* Create an `argocd` project named `a` (this will create the annotation `app.kubernetes.io/instance: a`) and try to sync it into namespace x.
* Choose `purge` as the method to resolve differences.
* Enjoy the error when `argocd` tries to access (purge) resources in namespace y.

**Expected behavior**

The target namespace is part of the project configuration and should definitely be respected. K8s namespaces are encapsulated and separate applications.

**Screenshots**

None

**Version**

`argocd version` in use: 1.24

**Logs**

None

*Let me know if you need further information or clarification.*

**Comment by jannfis** [comment]
I think this behaviour is "works as designed" and not necessarily a bug.

ArgoCD honours the explicit `namespace` setting in resources it syncs to the cluster, and doesn't overwrite it with the namespace given for the application. This is useful if it's required to sync certain resources from your app into other, fixed namespaces (such as `kube-system`).  And probably, these resources should also get pruned if they don't exist in the manifest anymore.

While I think mixing fully automated systems such as ArgoCD (who define themselve as "single point of truth") and manual cluster interaction is not quite the best practice (although I can understand that it happens), maybe a "restrict prune to application namespace" safety net feature (as an additional option) would be viable.

**Comment by zbindenren** [comment]
If this works as designed why is it needed to specify a namespace? 

If I run `kubectl apply -n <namespace>` I expect no changes in other namespaces.

In this regard argo-cd behaves very differently than kubectl.

**Comment by bbortt** [comment]
First of all, thanks for the quick response. Here are my thoughts on this:

> ArgoCD honours the explicit namespace setting in resources it syncs to the cluster, and doesn't overwrite it with the namespace given for the application

That's ok when it comes to a deployment. But not if it purges anything it hadn't even tracked before. That's fatal in my opinion! Why would it disregard the project configuration in this case?

> And probably, these resources should also get pruned if they don't exist in the manifest anymore.

Those resources have never been tracked. They matched via `app.kubernetes.io/instance` which one cannot control over multiple namespaces if his application is bound to it. A k8s namespace is definitely separating from this point of view.

> manual cluster interaction is not quite the best practice

It was not quit manual.. I just tried to simplify the steps to reproduce the problem ;)

**Comment by jannfis** [comment]
Hi, this is an interesting discussion and I really appreciate your input!

To answer some questions:

> If this works as designed why is it needed to specify a namespace?

I think there would be many reasons, but the most obvious IMHO is to deploy the same versions of manifests to different namespaces in the same cluster, as different applications (i.e. `app-test`, `app-preprod` or whatever).

> In this regard argo-cd behaves very differently than kubectl.

That's correct - kubectl upserts any `namespace` specification in the manifests, while ArgoCD only inserts it when there's none in the manifest. I agree that this is counter-intuitive when expecting kubectl-like behaviour, but I'm unsure whether kubectl-consistent-behaviour was a design goal of ArgoCD. But indeed, nasty surprises should not be part of the user experience. Maybe this should be made more clearer in the documentation.

> Those resources have never been tracked.

It's important to understand that ArgoCD is mostly stateless in this regard and tracks managed resources by the `app.kubernetes.io/instance` label. If you have an app named `test` and some "stray" resources with that label set, it will consider them part of that application with full consequences, such as deleting this resource when prune-syncing (resource is not in manifests) or cascade deleting the application.

You can restrict the namespaces ArgoCD can operate in by creating a Project and setting the explicit namespaces ArgoCD is allowed to sync to - please refer to https://argoproj.github.io/argo-cd/user-guide/projects/ for documentation. 

Once you create a project and restrict it to say namespace `nsa`, applications attached to this project it will still see "stray" resources in namespace `nsb`. But as soon as an operation, such as sync or prune, would have to be performed on resources in namespace `nsb`, synchronization will fail and the operation is aborted.

I hope that clarified it a bit, but of course, please feel free to further share your opinions!

**Comment by jannfis** [comment]
Just to ensure that we are aligned on terminology - I was assuming you mean "application" by "project".  I hope I didn't assume that wrong, because the application is what contains the manifests, is where the `app.kubernetes.io` label stems from and also is the entity that is synced to the cluster. 

A "project" in ArgoCD terms is another entity that carries all kind of restrictions for a set of "applications" that are attached to that very project.

**Comment by bbortt** [comment]
> Hi, this is an interesting discussion and I really appreciate your input!

Same thoughts on my side. I think, I'm slowly understanding it..

> Once you create a project and restrict it to say namespace nsa, applications attached to this project it will still see "stray" resources in namespace nsb. But as soon as an operation, such as sync or prune, would have to be performed on resources in namespace nsb, synchronization will fail and the operation is aborted.

I think that is exactly what happened to us (I'm the developer, not the system engineer tho :)). But now we're stuck with the argocd project not syncing at all e.g. failing. And as far as I understand there is no other solution than creating an argoc-only-cluster in order to avoid `instance` conflicts as we cannot force all of our devs to migrate to the tool (and the whole process coming with it) in one turn. This is a bit irritating.

> I was assuming you mean "application" by "project"

Yes, kind of. By application I meant more like all that one team manages. This will be synced into one namespace per cluster. And therefore can contain multiple applications from a server kind-of view. Where we have different clusters per stage, eg. test, int and prod, not separated using namespaces.

**Comment by jannfis** [comment]
> Yes, kind of. By application I meant more like all that one team manages. This will be synced into one namespace per cluster. And therefore can contain multiple applications from a server kind-of view. Where we have different clusters per stage, eg. test, int and prod, not separated using namespaces.

We need to be careful here to not mix up meanings of terminology, otherwise we will talk about different things I guess :) As a developer, you will most likely commit your manifest changes to a Git repository, which in turn is connected by ArgoCD through an _Application_ in ArgoCD terms. This _Application_ defines where these manifests are synced to, i.e. a combination of destination cluster and target namespace. The target namespace is only advisory, and will only affect resources not explicitly having a `namespace` tag in the manifest.

The engineers maintaining your ArgoCD installation will most likely have set up a _Project_ in ArgoCD, and your _Application_ is attached to this _Project_. The relationship between _Project_ and _Application_ is `1:n`. 

Each _Project_ defines restrictions, such as allowed namespaces and clusters for the _Application_, a list of resources that may be synced and resources that are explicitly forbidden. So, long story short, it can be broken down to the following core assumptions:

- The _Application_ defines where your manifests are actually synced to, and also how it is supposed to sync (i.e. automatic, with pruning enabled, etc)
- The _Project_ defines where your applications are actually allowed to sync to, and what they are allowed to sync

Does that make sense? It's quite early, and the coffee is just starting to kick in.

> But now we're stuck with the argocd project not syncing at all e.g. failing. And as far as I understand there is no other solution than creating an argoc-only-cluster in order to avoid instance conflicts as we cannot force all of our devs to migrate to the tool (and the whole process coming with it) in one turn. This is a bit irritating.

You don't have to separate clusters as a final consequence. But you should make sure that ArgoCD and the teams/people working with other mechanisms (such as pushing manifests to the cluster from i.e. a CI toolchain) do not use the very same values for the `app.kubernetes.io/instance`. ArgoCD sets this label's value to the name of the _Application_ as defined in ArgoCD, so if your _Application_ is named `a`, just make sure that a) no other resource in the clusters (regardless whether managed by another tool or humans) use the same value for this label and b) that ArgoCD "owns" the destination namespace exclusively. 

To fix your current sync problem, make sure you change the `app.kubernetes.io/instance` label of those "stray" objects in your cluster to a value that does not match any ArgoCD Application name. These resources will be shown as `OutOfSync (requires pruning)` in ArgoCD. Once you change that label on the resources, they should not be shown in your _Application_ anymore and the sync should be possible.

**Comment by bbortt** [comment]
Since my system guys are stuck at the coffee machine, I think all problems have been solved by now.

*`app.kubernetes.io/instance` overwritten*
-> solved by setting a custom argocd specific label as [documented](https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing) (in argocd deployment resources).

*argocd deleting unmanaged resources*
-> is not the nicest, but neutralized using kubernetes roles/permissions.

Only thing left at this point is that argocd could possibly also delete resources managed by other projects, but at least there will be the following warning message:
```bash
SharedResourceWarning [...] is part of a different application: [...]
```

Thanks for your help and the created issue, it describes the problem really well.
