### ISSUE TITLE
Support kubectl replace instead of apply

### ISSUE THREAD

**Issue by epa095** [argoproj/argo-cd#2730]
# Summary
Could it be possible to have argocd use `kubectl replace` instead of `kubectl apply` when applying/replacing resource? 

# Motivation
We have some custom resources which can be quite big, at least larger than 256Kb, which is the limit for the metadata in k8s, and `kubectl apply` puts the whole configuration into `last-applied-configuration` as explained for example [here](https://github.com/argoproj/argo-cd/issues/820). We use argocd to push all our other k8s resources to the cluster, so it would be nice if we could use it for these resources as well. 

# Proposal
A flag per project.

**Comment by alexec** [comment]
Could you use force mode?

**Comment by gnu300** [comment]
I have the same need of that feature in a different context.
i am trying to automate my OpenShift cluster configuration via ArgoCD. With cluster configuration i mean:

- IDP/oauth configuration
- RoleBindings
- Storage (PV) for image-registry and rook csi
- Resource allocation for kube-/system-reserved
- ....

I actually thought that this is a use-case for ArgoCD but if i am trying to sync as an example the oauth yaml i get the following error:
`Operation cannot be fulfilled on oauths.config.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again `
This error occurs when you are not referencing to the latest version (=resourceversion) within your yaml. This behaviour is equivalent to "oc apply -f oauth.yaml", therefore Kubernetes/OpenShift has the command "oc replace...".
Forcing this is not an option because then oc/kubectl/argocd would try to delete the resource first and create/apply it again. This might be useful for Pods/Deployments and so on, but not for IDP and other global cluster configuration, this would lead to instability within the cluster and probably degrade the availability.

**Comment by nickma82** [comment]
> Could you use force mode?

As this mode (at least in some cases) first deletes the resource just to add the new one, there are use cases where you cant do that.

**Comment by Cuball0** [comment]
A replace could probably also solve the issue where we have a wrong resourceVersion in our manifest in Git compared to the resourceVersion in the cluster.

When the resourceVersion gets changed (in this case because of a new automatic Deployment) it's not in sync with the version in Git and it blocks the sync process in ArgoCD.

See the error :

`
kubectl failed exit status 1: The deploymentconfigs "demo" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update`

**Comment by gnu300** [comment]
I got my use-case working, i documented it here https://www.reddit.com/r/openshift/comments/ew5de7/argocd_apply_openshift_cluster_config/fg4klk1?utm_source=share&utm_medium=web2x

**Comment by cabrinha** [comment]
I'm running into this issue when trying to apply large ConfigMaps that are JSONs for grafana:

```
ConfigMap "grafana-dashboard-my-dashboard" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

Using a pre-sync delete hook did not help.

**Comment by jessesuen** [comment]
@alexmt do we support annotating a resource to do `force=true` like we have for `validate=false` ? If so, I wonder if that would satisfy this use case

**Comment by cre8ivejp** [comment]
Any chances of this being implemented by this year?

**Comment by muzcategui1106-gs** [comment]
+1 on this issue. In my case --force did not help :/

**Comment by iyurev** [comment]
+ 1

**Comment by iyurev** [comment]
+1

**Comment by servo1x** [comment]
This would also be useful for CRDs that are very large.

**Comment by gymlt** [comment]
+1 on this issue. 
ConfigMap "grafana-dashboard-redis-haproxy" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Comment by gnu300** [comment]
+1

**Comment by qingkunl** [comment]
+1. This is a blocking issue for us.

**Comment by yydzhou** [comment]
+1, same issue here.

**Comment by rumstead** [comment]
@jessesuen @alexmt are there any docs around force mode? I brought this up on [slack](https://argoproj.slack.com/archives/CASHNF6MS/p1607617190389300) the other day. 

I want to be able to automatically “kubectl apply --force” my Kubernetes manifests so I don't have to force sync via the UI when a label or something immutable changes. I saw the [SyncOptions](https://github.com/argoproj/argo-cd/blob/3b67e91d558d4fea9442bb0550a55b6f73e77d20/pkg/apis/application/v1alpha1/types.go#L617) and tried adding “--force”, “force=true”, and “Force=true” but none seemed to work. I then stumbled across [SyncStrategy](https://github.com/argoproj/argo-cd/blob/3b67e91d558d4fea9442bb0550a55b6f73e77d20/pkg/apis/application/v1alpha1/types.go#L732). I was able to set this on the Application Resource and it seems to work but I want to make sure this is the best way to do it.

**Comment by perezjasonr** [comment]
> @jessesuen @alexmt are there any docs around force mode? I brought this up on [slack](https://argoproj.slack.com/archives/CASHNF6MS/p1607617190389300) the other day.
> 
> I want to be able to automatically “kubectl apply --force” my Kubernetes manifests so I don't have to force sync via the UI when a label or something immutable changes. I saw the [SyncOptions](https://github.com/argoproj/argo-cd/blob/3b67e91d558d4fea9442bb0550a55b6f73e77d20/pkg/apis/application/v1alpha1/types.go#L617) and tried adding “--force”, “force=true”, and “Force=true” but none seemed to work. I then stumbled across [SyncStrategy](https://github.com/argoproj/argo-cd/blob/3b67e91d558d4fea9442bb0550a55b6f73e77d20/pkg/apis/application/v1alpha1/types.go#L732). I was able to set this on the Application Resource and it seems to work but I want to make sure this is the best way to do it.

can you provide a snippet of how you did that/what the section looked like in the application object? theres no examples of how it looks in the docs.

**Comment by delamart** [comment]
@rumstead would also like to know how you did it.

Also +1 on this issue, would help handling immutable configMaps/secrets for example ( https://github.com/argoproj/argo-cd/issues/5394 )

**Comment by rumstead** [comment]
I have a controller that will help generate the ArgoCD applications for us (this was before the announcement of [Application Sets](https://github.com/argoproj-labs/applicationset)). In the code, I set the SyncStrategy as described above though I am not sure how those can be set on the Application CR itself.

**Comment by AmitBenAmi** [comment]
I'm using ArgoCD v1.8.1, and I have a very large secret and having the same issue.
Using force did not help @alexec (not from ArgoCD and not from `kubectl`).
Create/Replace should do the work.
Is this something going to be added so we can overcome this restriction.
Also, it will be even better if specific resources could be annotated with a value so only they would be created using `kubectl create`/`kubectl replace` and not every resource in the application.

**Comment by abdennour** [comment]
so the limit problem is actually because of the last-applied-configuration annotation
@AmitBenAmi  I didn't understand 
```
Create/Replace should do the work.
```
Nothing works from my side.
Can you point to which one ? 
![image](https://user-images.githubusercontent.com/1788384/110239809-06a20e00-7f5a-11eb-8f47-a9da742b14a3.png)

**Comment by AmitBenAmi** [comment]
@abdennour I stated that using `kubectl create`/`kubectl replace` did the work for me, since they do not add the `last-applied-configuration` annotation, so I do not pass the limit this way.

**Comment by abdennour** [comment]
Emm! and how did you continue with argoCD. 
did you mean that you initiate it locally,
then ArgoCD just sync subsequent changes ?
@AmitBenAmi  Thank you for quick response btw

**Comment by riccardofreixo** [comment]
This is also a big blocker for us, we'll have to implement a hacky workaround and stop relying on ArgoCD for one of our deployments. Support for `replace` would be amazing.

**Comment by AmitBenAmi** [comment]
@abdennour I didn't continue with ArgoCD in this use case.
I had to reduce the size of the content for it to be handled by argo.
If I create it manually with `kubectl create`/`kubectl replace`, and then ArgoCD tries to sync it, it will still fail since it tries to add the `last-applied-configuration` annotation

**Comment by AmitBenAmi** [comment]
@alexmt Do you know if it will be released as part of 1.8.X?

**Comment by abdennour** [comment]
@alexmt  same question as @AmitBenAmi .
Appreciate your assitance

**Comment by alexmt** [comment]
This is possible. The change is pretty isolated and should be easy to cherry-pick. Please let give us time to test 2.0 release to make sure that the fix itself has no bugs and will try to cherry-pick it to 1.8.

**Comment by abdennour** [comment]
This is fixed in the new phenomenal release v2 🎉 
![image](https://user-images.githubusercontent.com/1788384/125600073-68f59e09-5329-4ddc-8a13-711abddf1da7.png)

**Comment by automaticgiant-ml** [comment]
how is this done in the cli?
