### ISSUE TITLE
Locking "App Of Apps" to a single project and namespace

### ISSUE THREAD

**Issue by sadovnikov** [argoproj/argo-cd#2785]
# Summary

In AppProject we can limit Applications' possibilities using destinations, clusterResourceWhitelist and namespaceResourceBlacklist. For example, an Application can create any resources, as long as they are created within a particular namespace. However this does not allow creation of new Applications (App of Apps) because only Applications from `argocd` namespace are being managed. 

If we allow creation of Applications in 'argocd`, then other resources can be created there too. Pods and Jobs get access to a very powerful service account of ArgoCD.

# Motivation

We'd like to give development teams freedom to manage Applications, however 
* they should belong to the same ArgoCD project and 
* all applications' resources should be created in the same kubernetes namespace.

# Proposal

I would consider 
* letting ArgoCD to manage Applications, which are created by other Applications, regardless of their namespaces and 
* (optionally) enforcing sub-apps to inherit project from the parent

**Comment by chrisbulgaria** [comment]
Yes, this would indeed be an important enhancement for using argocd in a multitenant environment, i.e. giving project teams freedom in their own namespaces (and not always needing to resort to a central function when a new app is created).
Chris

**Comment by OmerKahani** [comment]
Why limit this to app of apps, and not just enable to create application objects in any namespace?
There might be a verification that the application uses a project that can deploy to the namespace, so we don't have application object in namespace a with project b that sync things to namespace c (project b is not allowed to namespace c)

**Comment by davidkarlsen** [comment]
This is the biggest weakness of argocd. Why not just stick to normal K8s rbac and control access to application resource - and let that deploy to the namespace it is definer within?

**Comment by sadovnikov** [comment]
@davidkarlsen, I can see this working if Project becomes like a "subject" in RoleBinding. Regular roles get assigned to projects. Argo could even create a service account for each Project and use that SA to render Applications

**Comment by davidkarlsen** [comment]
A far easier model would be to let argo act on `Application`s defined in _any_ namespace, but limit the resource created by the `Application` to that namespace - then the k8s RBAC would act as normal - limiting where folks can create `Application` resources.

**Comment by davidkarlsen** [comment]
Any thoughs on this - this would help a lot on the multi-tenancy.

**Comment by storm1kk** [comment]
Still relevant, it can help us to reinforce security in the multi-tenancy environments.

**Comment by davidkarlsen** [comment]
Related: https://github.com/argoproj/argo-cd/issues/3474

**Comment by davidkarlsen** [comment]
Also see https://blog.kintone.io/entry/production-grade-delivery-workflow-using-argocd#Multi-tenancy which describes the same problem.

**Comment by andrewm-aero** [comment]
My team has recently started bumping up against this as well. While not a perfect solution (and we must remember not to let the perfect be the enemy of the good), we had the following thought on how to fix this issue:

1. Allow "child" apps (i.e. apps created by apps) in a project to be restricted to a set of projects
2. Allow "child" projects (i.e. projects created by projects, or projects created by apps created by projects) to be limited to a set of permissions, including those set in (1)
3. Allow "child" apps and projects in a project to be restricted to a set of names (either a static list, prefix/suffix, or maybe even a regex)

The basic idea is to guarantee that as you descent the parentage tree of Applications and Projects, that no new privileges are added, only removed.

This would still work with the assumption that all Applications and Projects are in the argocd namespace, but would still have some measure of safety against name collisions between tenants (one could scan for all such top-level restrictions, and calculate if there is possible overlap), as well as allow tenants to freely create apps and even whole sub-projects without providing any access to the underlying cluster not granted by the original project.

**Comment by jemag** [comment]
I feel like this is an essential feature for proper self-service with multiple tenants. Currently ApplicationSets are too limiting and not as practical.

Seems like there is some work being done here : https://github.com/argoproj/argo-cd/pull/6409
Hopefully it gains traction in the near future.

**Comment by karol-cybul-bis** [comment]
It's still relevant for multi teams configuration.
We want to let the teams to manage themselves, but they can deploy applications to another projects, not so good isolations.
Of course they have to know all details like repo and namespace, but still it's an issue.

**Comment by crenshaw-dev** [comment]
Discussion of a similar limitation for AppSets:  https://github.com/argoproj/argo-cd/pull/9016#discussion_r844369097

**Comment by andrewm-aero** [comment]
@crenshaw-dev  Here's an approach that might work for a short-term band-aid fix: Add a field to AppProject called, something like, `.spec.appOfAppsSandboxed`. Its a bool, defaults to false (or maybe make it a breaking change and default to true to be secure by default, or maybe make the default configurable via cmd arg), and if set to true, if an Application in that AppProject creates another Application, it must be in the same AppProject . This way, there's no need for propagation rules, just filter all of the output for Applications, check that the sandbox field is either false or the project field matches, and reject the reconciliation otherwise. Under this scheme, you'd have an "admin" AppProject whose Application creates other projects, and other Apps-of-Apps, recursively, down until you get to an AppProject that's sandboxed, and a "Terminal" App-of-Apps that points to a tenants directory containing Application resources, which can themselves create other Applications in the same AppProject, but can't "Escape". From there, its just a matter of ensuring those "Terminal" AppProjects have the correct allowed set of resources/cluster scope whitelists. Even if those "sandboxed" Applications can create AppProjects, they can't even create Applications in them. I think there is room for more complex rules like you described, but I'm thinking that this issue has been around for so long, something is better than nothing at this point.

Thoughts?

**Comment by crenshaw-dev** [comment]
@andrewm-aero yep, I'd be in favor of a very-limited feature like that, just to get the basic problem solved.

Maybe the field could be nested to allow future expansion:

```yaml
spec:
  appOfAppRules:
    appMustUseThisProject: true
```

**Comment by andrewm-aero** [comment]
I like the nested field idea. I've got some time this weekend, this seems simple enough that I can start on a PR if you'd like me to.

**Comment by crenshaw-dev** [comment]
@andrewm-aero that would be awesome! lmk if you need help with the dev environment or anything else.

**Comment by meln5674** [comment]
I've switched to my personal account (and time) just to ensure no complications with the DCO. PR is up, which I think you saw. Wasn't able to run the e2e tests locally, both the start-e2e and start-e2e-local targets fail in different ways w/ go package installs, despite working in the CI, not sure if that's a known issue or if I just have an unsupported setup.

**Comment by crenshaw-dev** [comment]
Thanks for putting that up! Yeah tbh e2e has always been annoying for me locally too, so I just rely on CI.

**Comment by krayne** [comment]
The childAppProjectAllowList approach fits much better than appMustUseThisProject in my opinion.

As long as Applications must be created within the argocd namespace, you always need to grant argocd namespace as destination as well in the appProject. But with appMustUseThisProject you can't restrict the resourceWhitelist for argocd namespace independent to the other namespaces.
This causes, that many other resources than Applications can be deployed to argocd namespace, which allows to deploy malicious stuff into argocd namespace (e.g. something which gets you access to the argocd serviceaccount token).

The childAppProjectAllowList would adress this issue: 
You can create top-level appProjects/apps for each tenant. Those top-level appProjects are only able to create Applications within argocd namespace and nothing else.
Their childApps can use complete different appProjects with independent restrictions.

Example:
```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: top-level-tenant-a
  namespace: argocd
spec:
  childAppProjectAllowList:
  - apps-of-tenant-a
  namespaceResourceWhitelist:
  - kind: "Application"
    group: "argoproj.io" 
  destinations:
  - namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://git.example.com/scm/tenant-a/apps-of-tenant-a.git'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-of-tenant-a
  namespace: argocd
spec:
  destinations:
  - namespace: 'tenant-a-*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://git.example.com/scm/xxxx/'
---
```

**Comment by jannfis** [comment]
As @crenshaw-dev mentioned, I'd favor implementing this with the features introduced by #9755 instead of introducing a new setting in the `AppProject` spec for something that is also achievable in another way. 

For example, you will be able to setup an application namespace for tenant A (let's call it `tenant-a`), then setup an `AppProject` like this:

```
metadata:
  name: tenant-a
spec:
  sourceNamespaces:
  - tenant-a
```

Now, someone able to use AppProject `tenant-a` can create `Applications` in namespace `tenant-a` (either declarative, or with proper Argo CD RBAC in place also imperative), and as long as the `Application`'s project is set to `tenant-a`, Argo CD will reconcile it.

This `Application` will also be allowed to create further `Applications` in the namespace `tenant-a`, given the project allows this. But these `Applications` in turn must also set their `.spec.project` to `tenant-a` in order for Argo CD to allow their reconciliation.

**Comment by crenshaw-dev** [comment]
@meln5674 would the solution Jann is describing be sufficient, or do you see additional value in the "lock" feature you've written? 

I'm annoyed at myself that I didn't think of Jann's suggestion first. Might have saved you some time.  :-)

**Comment by krayne** [comment]
Thanks a lot for your feedbacks. Unfortunately I wasn't aware of https://github.com/argoproj/argo-cd/pull/9755 but this one fits
 perfect for our needs.

**Comment by crenshaw-dev** [comment]
@krayne that's my bad. I'm glad this will work! I'll close your PR, and then we can reevaluate if namespaced apps don't solve all the problems.

**Comment by crenshaw-dev** [comment]
I think this is solve by apps-in-any-namespace, but I'm holding off closing the ticket until we have docs for the feature (and specifically how it solves this use case).
