### ISSUE TITLE
Argocd failing upon processing BitBucket webhooks

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argo-cd#2803]
BitBucket's payload for the "refs updated" event contains date in the following format:
2019-12-04T11:59:03+0200
When BitBucket posts the payload to argocd server with such an event, 502 is received from argo

When I performed the curl myself, and changed the date to be in the format of
2019-12-04T11:59:03
I received 200, but Argo's logs showed this : 
"level=info msg="Webhook processing failed: parsing time \"2019-12-04T11:59:03\" as \"2006-01-02T15:04:05Z0700\": cannot parse \"\" as \"Z0700\""

So support for such a timezone format is needed, and further surprises might be down the road, so it is better to test the full scenario of webhook from BitBucket, rather than just adding the support for this particular timezone

**Comment by alexec** [comment]
Would you like to submit a PR for this?

**Comment by reggie-k** [comment]
Yes, I will work

**Comment by reggie-k** [comment]
Yes, I will work on this issue

**Comment by chihaiaalex** [comment]
Any news on this one?

**Comment by reggie-k** [comment]
Unfortunately, did not have the chance to work on it yet. For me, the issue
is low priority

**Comment by haandude** [comment]
Any update on this?

**Comment by reggie-k** [comment]
I will not be able to work on this issue, sorry.

**Comment by crenshaw-dev** [comment]
@chihaiaalex it looks to me as if that payload will always be ignored anyway since it does not contain links. https://github.com/argoproj/argo-cd/blob/17c6daa9ea897936bb5f472455b520c1de41fc2b/util/webhook/webhook.go#L204-L207

I can fix the nil reference error, but I'm not sure that it would solve the problem of the webhook not being handled.

@haandude do you have another example payload?

**Comment by todaywasawesome** [comment]
Should have been closed with #7963
