### ISSUE TITLE
Login cookie clash on two ArgoCD instances sharing same domain

### ISSUE THREAD

**Issue by johnmarcou** [argoproj/argo-cd#3005]
**Describe the bug**

When running two ArgoCD instance on the same domain name, the login is misbehaving.
Login to ArgoCD-A works, then ArgoCD-B login is refused.

**To Reproduce**

The best way to reproduce is to run 2 ArgoCD instances, and use `kubectl port-forward svc/argocd-server X443:443` to redirect the connections locally. The two connection will share the same domain: `localhost`. (This is the only case I am actually using).

But this scenario would be similar to multiple instances of ArgoCD running behind a reverse proxy with subpaths like `mycompany.org/argocd-prod/` and `mycompany.org/argocd-test/` or `mycompany.org/argocd/` and `mycompany.org:4443/argocd/`.

**Expected behavior**

We should be able to login on the ArgoCD-A on `localhost:1443`, then ArgoCD-B on `localhost:2443`, and browse the UI without issue.

**Version**

```shell
argocd: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:48:19Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
```

**Investigation**

It appears that the login JWT is stored in a session cookie. The domain set on that cookie is the default, which is the domain name of the request (without the port number!).

The two opened web pages are sharing the same cookie to find the JWT. This makes the website of ArgoCD-B constantly redirecting to the login page, since it is using the JWT generated by and only valid for ArgoCD-A, so it receives return code 401.

Note: https://tools.ietf.org/html/rfc6265#section-8.5
> Cookies do not provide isolation by port.  If a cookie is readable by
   a service running on one port, the cookie is also readable by a
   service running on another port of the same server.  

**Workaround**
Edit /etc/hosts to point `argocd-prod` and `argocd-test` to localhost, and use those ones.

**Comment by jannfis** [comment]
I suppose you are using `--basehref` to server ArgoCD from another path than `/` to accomplish your two instances setup and use rewrite rules for the API as described in https://argoproj.github.io/argo-cd/operator-manual/ingress/#ui-base-path - am I supposing this right?

A possible solution could be to populate the `path` field of the JWT cookie with the value given in `--basehref`, so that cookies will only be sent with requests to that instance.

**Comment by johnmarcou** [comment]
Hi @jannfis,

I am using only the `kubectl port-forward` way, without basehref or reverse proxy setup.

**Comment by jannfis** [comment]
I think then the behaviour is at least technically correct, and by quoting the RFC above you already provided the technical reason behind it. 

Do you expect to be able to use both instances at the same time, or to replace instance A with instance B after a new login?

**Comment by amarrella** [comment]
Hi @jannfis I am also having this issue when exposing 2 ArgoCD instances on the same domain (using `--basehref`) and i think your proposed solution would work for this use case (not localhost tunneling though).

**Comment by alexmt** [comment]
We've started working on https://github.com/argoproj/argo-cd/issues/3005. It suggests introducing a new flag which changes UI base href as well as API server root path.  It is safe to use the new flag to set path in JWT token cookie

**Comment by mayzhang2000** [comment]
This is fixed. See documentation: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/ingress.md#argocd-server-and-ui-root-path-v153

**Comment by larsks** [comment]
For other folks who find their way here, as I did, because you are using `kubectl port-forward` to expose two argocd instances on different ports on localhost (as was @johnmarcou in the original description), there's a better solution that mucking about with the API server root path.

This is true for Linux and *may* be true for other operating systems: any `127.*` address maps to the loopback interface, so you can easily expose your multiple argocd instances on different localhost addresses.

In this example, we assume I have argocd running on two different clusters (that we select using the `--context` flag to `kubectl). We expose the first on `127.0.0.1:8080`:

```
kubectl --context server1 -n argocd port-forward service/argocd-server \
  --address 127.0.0.1 8080:80
```

And the second on `127.0.0.2:8080`:

```
kubectl --context server1 -n argocd port-forward service/argocd-server \
  --address 127.0.0.2 8080:80
```

You can now access one instance at http://127.0.0.1:8080 and the second at https://127.0.0.2:8080. Because the host addresses are different there will be no conflict between the JWT tokens.
