### ISSUE TITLE
Better log UI

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-cd#3123]
# Summary

It's unusable right now because I can't highlight/copy/view without things moving around. Maybe we can copy the UI of Kubernetes Dashboard logs.

# Proposal

- Faster log UI when streaming huge amount of log
- Ability to download log
- Improve copy/highlight experience

**Comment by tastypackets** [comment]
I'd like to add on to this that current log view copy/past is kind of weird and varies between browsers and OS, for example on Windows `ctl+c` doesn't copy the select line in the logs and scrolls the user instead to the bottom of the logs.

This happens because it's being connected from observable into JS xterm, which thinks the user is trying to send input into the terminal.  The xterm lib was designed to be a full xterm solution in the browser, so it expects things like `ctrl/cmd + c` to be sent to the terminal. In order to work around this we can attach a custom key handler, like the reply in this issue mentions: https://github.com/xtermjs/xterm.js/issues/2478#issuecomment-543246347

However I don't think this would respect users remapping copy/past keys, while uncommon it does bring up the question of is this the right solution?

I think the root issue is that xterm may be a huge hammer to drive a rather small nail, since in ArgoCD there is no terminal it's just streaming logs. Perhaps it'd be best to rework this without using xterm?

**Comment by alexmt** [comment]
Agree about xterm. Point 1 and 3 are done already - logs viewer now uses pagination and don't use xterm. https://github.com/argoproj/argo-cd/pull/5803 allows downloading all logs.
