### ISSUE TITLE
OutOfSync / Redeploys of helm charts using Release.Time.Seconds

### ISSUE THREAD

**Issue by jkleinlercher** [argoproj/argo-cd#3263]
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

We had a huge outage of lots of applications because argocd restarted most of the pods of our applications. This was after a short network error when argocd was not able to communicate with its redis server.

**To Reproduce**

1) delete redis endpoint: kubectl delete endpoints argocd-redis -n argocd
2) delete argocd-repo-server pod and argocd-application-controller

**Expected behavior**

argocd should do nothing with the applications, however argocd started to restart lots of application pods permanently, which ended in application outages and high cpu on the worker nodes

**Screenshots**

...

**Version**

v1.4.2+48cced9

**Logs**

here are the application-controller logs: 
[controller_log.txt](https://github.com/argoproj/argo-cd/files/4364064/controller_log.txt)

**Comment by jkleinlercher** [comment]
I can easily reproduce the problem now. I found out that only this two steps are necessary:

1) kubectl delete endpoints argocd-redis -n argocd
2) kubectl delete pod argocd-repo-server-5f584b6f78-pfc6c -n argocd   (replace repo-server pod name)
3) wait some minutes, with "kubectl get pods --all-namespaces -w" you will then see pods get terminated/restarted

Interesting: not all applications get resynct/restarted, but it is always the same set of applications. Maybe it is specific to some applications, but we didn't find the similarity of these applications yet. So if you can't reproduce it, it might be due to some specific configuration.

**Comment by jkleinlercher** [comment]
we were able to find the similarity of all failing applications. in those applications we use the following deployment annotation in our helm charts:

`arz.at/releasetime: "{{ .Release.Time.Seconds }}"`

So we assume, when argocd is not able to connect to the cache, argocd runs "helm template" and checks for a diff between the life deployment and the output of "helm template". Since ".Release.Time.Seconds" is the current time, there is a diff each time the sync runs.

So it seems that using " .Release.Time.Seconds " is an anti-pattern, or should argocd be aware of this special annotation?

**Comment by jessesuen** [comment]
> Since ".Release.Time.Seconds" is the current time, there is a diff each time the sync runs.

Yes this is the behavior of argo-cd. See our notes on randomly generated data:

https://github.com/argoproj/argo-cd/blob/857ce87f004f41031d05f12af4097b4bf49bd2d7/docs/user-guide/helm.md#random-data

**Comment by jkleinlercher** [comment]
First and foremost thank you so much for your immediate response in that issue (here and on slack). That gives so much confidence!
Concerning randomly generated data: since this was such a big issue in our company, we think about it, how to prevent developers of using randomly generated data in their helm chart. Also, we need to check external helm charts if they use randomly generated data.
How do you deal with that? Do you "just" have documentation concerning this bad-practice? Do you have OPA policy checks where you check for these kind of things? is this feasible? which process do you have for external helm charts to check if they are "argocd compliant" ?

**Comment by jessesuen** [comment]
Argo CD doesn't have protections on this, because we effectively do the equivalent of `helm template . | kubectl apply -f -`, with no understanding of the capabilities used in chart. I also doubt that OPA could do anything because it is way too late in the data path, and only deals with fully-rendered applied manifests.

Generally speaking, the randAlphaNum feature in helm charts are used as a convenience for automatic password generation. These charts invariably have the option to specific an existing secret (instead of generating a password), which is how I feel most people deal with this problem.

The `"{{ .Release.Time.Seconds }}"` is new pattern to me which I was unaware of. It does rely on very specific lifecycle understanding of helm. I just did a cursory search in helm/stable and do notice quite a bit of usages. All of these charts would have problems with Argo CD, just as the `randAlphaNum` would have problems.

I do feel Argo CD could do better job about Helm compatibility. The primary reasons we went with a `helm template . | kubectl apply -f -` approach were:
1. the avoidance of helm tiller
2. the ability to diff/preview manifests before applying
3. the ability to reject deployments when there are unsanctioned resources in the project whitelist/blacklist

If we could leverage tillerless helm 3, while still achieving the above requirements, I think we would be open to changing the implementation to better support helm charts.
