### ISSUE TITLE
API server --diable-auth flag does not properly disable RBAC

### ISSUE THREAD

**Issue by JazminGonzalez-Rivero** [argoproj/argo-cd#332]
Currently have to..

 run kubectl edit cm argocd-rbac-cm

update 

  policy.default: role:readonly

to

  policy.default: role:admin

This should be setup by default not something we have to do manually as part of the dev setup.

**Comment by alexmt** [comment]
one possible way to improve it:

- add optional flag `defaultPolicy` to argocd api server. Default value should be `role:admin` (since we want such behavior in production)
- API server should check field `policy.default` if `argocd-rbac-cm` and fallback to  `defaultPolicy` flag value if field `policy.default` is missing in config map
- Procfile should start api server with `defaultPolicy` flag set to `role:admin` to improve dev experience

**Comment by merenbach** [comment]
@alexmt the field isn't missing and needing a fallback, as far as I can tell: it actually gets set by default to `role:readonly`.

**Comment by jessesuen** [comment]
I think this may be an issue with our dev setup where --disable-auth does not properly disable RBAC. I see from logs that rbac checks are happening even when `--diable-auth` is specified.

**Comment by jessesuen** [comment]
I verified this is the case. In the rbac library, I re-assign the enforcer and lose the enabled/disable preference during startup.

```
// SetUserPolicy sets a user policy, augmenting the built-in policy
func (e *Enforcer) SetUserPolicy(policy string) error {
	sa := scas.NewAdapter(fmt.Sprintf("%s\n%s", e.builtinPolicy, policy))
	enf, err := casbin.NewEnforcerSafe(e.model, sa)
	if err != nil {
		return fmt.Errorf("failed to update enforcer: %v", err)
	}
	e.userDefinedPolicy = policy
	e.Enforcer = enf // preference is lost here
	return nil
}
```
