### ISSUE TITLE
Disabling TLS between controller and repo-server

### ISSUE THREAD

**Issue by lindlof** [argoproj/argo-cd#3389]
# Summary

The gRPC connection between `application-controller` and `repo-server` is a non-validated TLS connection. Giving the option to turn TLS encryption off between these cluster services would give more transparency and security when using a service mesh.

# Motivation

We're using istio for securing and managing connections between services in our cluster. We have a TLS connection between all services in our cluster by default. ArgoCD making its own TLS connection only complicates things for us and reduces control we have over the connection. ArgoCD's TLS connection doesn't verify the certificate which is much more insecure than using istio where we are using mutual TLS verification.

Also, issue https://github.com/istio/istio/issues/16282 makes it very difficult to install ArgoCD with istio. Ability to turn off the TLS connection would have saved us weeks.

# Proposal

Currently we're setting up `argocd-server` with the `--insecure` flag in order to secure the frontend connection using istio. We could have similar flags for `application-controller` and `repo-server`.

Alternatively, these could be configured through environment variables which would look nicer in k8s manifests.

**Comment by jannfis** [comment]
I like this idea. Ideally, the enhancement would also include the possibility to provide valid TLS certificates and keys for `argocd-repo-server` and `argocd-controller` endpoints via a K8s secret, using standard keys `tls.crt` and `tls.key` instead of the behaviour you described and a mechanism to inject the corresponding CA certificate for validating the connections between components.
