### ISSUE TITLE
error: code = Unimplemented desc = unknown method ListRepositories

### ISSUE THREAD

**Issue by neilharris123** [argoproj/argo-cd#3402]
**Describe the bug**

I'm logged into argocd via the cli. I can list/sync/create applications. but I'm receiving an error when I try to list the repos via the cli.

When I run:

`argocd repo list`

I'm receiving:

`FATA[0001] rpc error: code = Unimplemented desc = unknown method ListRepositories`

version:
v1.5.1+8a3b36b

**Expected behavior**

A list of the repositories which I can see are available and authenticated in the GUI.

**Comment by jannfis** [comment]
Hi @neilharris123, what's the full output of `argocd version` please?

**Comment by neilharris123** [comment]
full output of argocd version:

argocd: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:59:42Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.3.6+89be1c9
  BuildDate: 2019-12-10T22:47:48Z
  GitCommit: 89be1c9ce6db0f727c81277c1cfdfb1e385bf248
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0

**Comment by jannfis** [comment]
Thank you. There was indeed a change in the CLI introduced in `v1.4` that is causing this error, because the CLIs from `v1.4` upwards use an API method not available in servers version lower than `v1.4`. I agree that this is a bug, and should be fixed. However, as a workaround you can use the CLI for the corresponding server version.

On a side note, with the release of `v1.5.0`, I would suggest to upgrade your ArgoCD server to a more recent version.

**Comment by alexmt** [comment]
Looks like we forgot to update min CLI version after introducing backward incompatible change in 1.4. Created PR to fix it: https://github.com/argoproj/argo-cd/pull/3413
