### ISSUE TITLE
application resource can be applied in any namespace

### ISSUE THREAD

**Issue by artbegolli** [argoproj/argo-cd#3474]
# Summary

We would like the ability for argoCD to recognise any `application` resource that has been applied across the cluster and not just within the namespace where ArgoCD has been deployed.

# Motivation

We are working on producing a multi-tenant implementation in our cluster and to do this, we have implemented a controller for handling all of these tenants. There is the use case where the same application will be applied in multiple different tenants (which will generally be a grouping of namespaces). Currently, as all application CRs are present in the argocd namespace, these cannot share the same name. 

If applications were picked up from all namespaces, we could begin to store the application CR in the relevant tenants namespace instead of having to rename the application.

# Proposal

How do you think this should be implemented?

In the ArgoCD spec allow specifying a `scope` field which allows argo to scan the entire cluster or just the namespace.

I'm sure you guys have a justification as to why you are limiting the application resource to only the namespace where argocd has been deployed and I'm curious as to why.

Cheers,

Art

**Comment by rumstead** [comment]
This was briefly discussed today at the Argo CD & Rollouts Community Meeting during the [Application Set proposal](https://github.com/argoproj-labs/applicationset).

**Comment by george-angel** [comment]
https://github.com/argoproj/argo-cd/issues/2557#issuecomment-653436244

Thank you

**Comment by peterbosalliandercom** [comment]
I would like to add the following suggestion. If you set a sort of scrape label like prometheus has on the namespace i.e. `argocd-scrape: true` then it is fully customizable.

**Comment by yhaenggi** [comment]
@rumstead any update on this? We also need it...

**Comment by rumstead** [comment]
> @rumstead any update on this? We also need it...

Last I heard the app set hasn't been moved into AroCD yet. Though I am not the best person to give an update.

**Comment by mvbakker** [comment]
Is there any progress? Similar to @yhaenggi we would also really like to have this implemented. Centrally we're controlling the `AppProject` resources, but we'd like to give developer teams control over their own `Application` resources, within their `AppProject`. This can now only be done if we also give them access to the `argocd` namespace, which is something we wouldn't like to do.

**Comment by peterbosalliandercom** [comment]
@yhaenggi @mvbakker What risk is involved if we allow developers to deploy application objects in argocd if we allow then via the project destination? Do they have permission to delete other applications?

**Comment by sbose78** [comment]
Hi @alexmt ! I've started taking a look at this.

In the upcoming milestone , I'm planning to make an enhancement proposal ( we can all feel free to +1/-1 it :) ) on this area. We may not get to implementing it, but I'd like to get a design going. Could we mark it for the upcoming milestone as 'design only' effort ?

**Comment by alexmt** [comment]
Hello @sbose78 , I also think this is important.

The next milestone already got few important tickets related to multi-tenancy (https://github.com/argoproj/argo-cd/issues/5283 and https://github.com/argoproj/argo-cd/issues/2251 ). It is good to tackle the issue described in this ticket at well.

**Comment by juv** [comment]
Can someone explain why the current behaviour was implemented as it is? 
What are the benefits of keeping all of those resources within the argocd namespace?

**Comment by alexmt** [comment]
@juv, Argo CD provides a single control plane that manages resources in multiple clusters. Having Applications CRDs in control plane cluster in one namespace allows us to implement UI/API that presents the state of all managed resources at once. 

If we store applications CRDs in multiple managed clusters it will be really difficult to fetch application status information. However I totally agree with the use case described in this ticket: it would be very nice to let end users create "apps" in target namespaces and "self service" argocd management. I've been working on PoC that resolves that issue for couple weeks. Hope to finish it this weekend and will present to the community.

**Comment by sbose78** [comment]
There are two distinct areas :

* Watch Application CRs in the remote cluster instead of the cluster being specified as a `destination`. I like what we do today.
* Application CR in non-ArgoCD namespace : This is the current issue at hand.

> What risk is involved if we allow developers to deploy application objects in argocd if we allow then via the project destination?

Here's how I see it :) 
If ArgoCD reconciles an Application CR and AppProject CR in namespace `foo` that had been created using `kubectl`, ArgoCD has no good way of determining whether the user is allowed to created the derived kubernetes objects :)

**Comment by jannfis** [comment]
I had some thoughts on this as well, and I think some of the major problems to solve are pointed out below:

**The relationship between AppProject and Application.**

 The AppProject provides governance to what an Application is allowed to do in the cluster, which repositories it may access etc. In the current state, Application CRs can be created in the cluster without enforcing what values the `.spec.project` field may hold. So basically, any Application can define to use any project when created via the K8s control plane, effectively circumventing any RBAC and governance provided by Argo CD. We assume that some who can create Application CRs in the `argocd` namespace is an Argo CD admin. So we would need a way to limit what values are allowed in an Application's `.spec.project` field. 

One possible solution would be to either enhance the AppProject CRD with a new field, e.g. `.spec.applicationSources` (or maybe even `.spec.sources`) that defines possible *sources* where Application CRs may exist and specify this AppProject as `.spec.project` value. For example,

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  applicationSources:
    - cluster: '*'
      namespace: '*'
```
would allow Applications from each namespace in each cluster to specify the `default` project as value in `.spec.project`. We could argue to re-use the `.spec.destinations` field of AppProject CR for this purpose (so, Application CRs may exist where Applications are allowed to be deployed), but I feel that would open up too much of a hole for people not wanting to have Application CRs exist outside `argocd` namespace.

Also, all that being written, I think we should really have the `AppProject` CRs to exist only in the `argocd` namespace and not allow them to exist in arbitrary locations. These are central to governance of Argo CD after all.

**Missing connection to a remote cluster.**

What happens when the connection to a remote cluster that holds Application CRs goes away? I think this is what @alexmt is tackling right now, and I believe this could be mitigated using some caching mechanisms on the Argo CD control plane side. However, since we consider Argo CD stateless, and the cache to be rebuildable at any time, this could pose some very nasty surprises imho and Applications to temporarily disappear.

**Comment by sbose78** [comment]
From my perspective, the experience I'm looking for is :

1. User logs in to namespace `foo`.
2. User creates an `Application` CR with a reference to the Git repo where the user has manifests
3. Application Controller reconciles it and ...
4. that triggers creation/sync of the resources in namespace `foo`/ outside namespace `foo` / cluster-scoped.

What determines whether (4) is allowed ?
User's existing permissions. Example, if the user wasn't allowed to create `pods` in the first place, she still doesn't get create to one!

**Comment by jannfis** [comment]
> What determines whether (4) is allowed ?
> User's existing permissions. Example, if the user wasn't allowed to create pods in the first place, she still doesn't get create to one!

I'm wondering how that could possibly work. I think there are a multitude of constraints that prevent that from working:

* Once a resource is created, how do you find out by whom it was created? What if another user modifies that resource? What if the Kubernetes RBAC of that user change?
* What about applying *least privilege* concept? With GitOps, possibly you don't want any "interactive" SA to have permissions to actually create application related workloads, such as Pods. Maybe you want them to only have required permissions to gain read-only visibility into the cluster, and deploy everything else using Argo CD
* What if the `Application` CR is coming from Git, deployed via Argo CD? Or through some kind of CI solution?

**Comment by sbose78** [comment]
> But what if the organization doesn't even want to have users with those kind of privileges?

Agreed, the existing model solves the problem for organizations that don't necessarily want their users to be exposed to Kubernetes.
However, I'm talking about the scenario where a user already has access to a cluster and one or more namespaces there.


> From my point of view, the CI would have the right to create an Application CR in a namespace. Not more. Again, why should the CI's user be granted privileges to create anything else?

The CI already has access to create other things, not by itself, rather via ArgoCD Application CR. So, effectively the permission management is not the native Kubernetes one, rather the ArgoCD one.

> Not only would it require additional privileges for users that they wouldn't need in the first place, but also would add a whole lot of complexity as far as I understood (like, an additional admission controller, etc).

As an example, I have allowed to do everything on three namespaces in a cluster - I need something that would sync manifests within the realm of the namespaces I already have access to. :)

**Comment by mvbakker** [comment]
Great to see that this thread has gotten some traction! I really like the discussion. To come back on the question from @peterbosalliandercom:

> @yhaenggi @mvbakker What risk is involved if we allow developers to deploy application objects in argocd if we allow then via the project destination? Do they have permission to delete other applications?

Yes, right now developers of different teams/products, and therefore different namespaces, all have essentially the power to modify the `Application` CRs of another team/product. Of course, us being all friends, this is unlikely to happen, but from a _least privilege_ point of view, ideally you'd restrict teams to only control their own `Application` CR.

From @sbose78:
> Application CR in non-ArgoCD namespace : This is the current issue at hand.

Exactly, and to provide some more context why we would like to see this, let me explain our use-case. Centrally, from the Platform/Admin team, we control the Argo CD installation/configuration. However, we try to give as much 'do-it-yourself' control to teams to control their own deployments using Argo CD. We control centrally what a team is allowed to synchronize (i.e. the repo, the namespace, specific non-namespaced resources, or even blacklist namespaced resources) with an `AppProject` CR. In this way, teams can deploy their own Application resource, triggering the deployment of their product whenever and however they would like, within the boundaries controlled centrally. Allowing them to deploy their `Application` CR in their own namespace will avoid the need to give them permissions to the `argocd` namespace. 

> From my point of view, the CI would have the right to create an Application CR in a namespace. Not more. Again, why should the CI's user be granted privileges to create anything else?

100% agreed. In our set up, generally users only have `view` and `list` rights to the cluster. The CI has the privilege to deploy `Application` CRs. Argo CD is allowed to deploy resources as described by the `AppProject` CRs.

What I have been wondering though, is there a reason why `AppProject` resources are namespaced? If `Applications` CRs are allowed to be deployed in other namespaces, then the `AppProject` would also need to be there? Or should it remain in the `argocd` namespace? Or would it be possible to make an `AppProject` a cluster-wide resource? Especially looking at the new 'Global AppProject' feature, which sounds like a cluster-wide resource (though these could also just be deployed in the `argocd` namespace of course, as long as other `AppProject` CRs can still inhered from it).

Another point to consider, imagine that `Application` CRs are also picked up from other namespaces other then `argocd`. If a team is only allowed to deploy `Application` CRs in their own namespace (controlled via K8s RBAC or CI), and they do not have permissions to the `argocd` namespace. Then they are not able to use the `default` `AppProject` CR to deploy anything and there must be an `AppProject` deployed for their namespace, am I right? It is something to consider, but I would like this behaviour.

**Comment by jannfis** [comment]
> Another point to consider, imagine that Application CRs are also picked up from other namespaces other then argocd. If a team is only allowed to deploy Application CRs in their own namespace (controlled via K8s RBAC or CI), and they do not have permissions to the argocd namespace. Then they are not able to use the default AppProject CR to deploy anything and there must be an AppProject deployed for their namespace, am I right? It is something to consider, but I would like this behaviour.

I think the `AppProject` would still live in a central namespace (i.e. `argocd`), and that users should not be able to create, modify or delete them. As you already pointed out, AppProjects will define what kind of resources an Application is allowed to deploy, and where it is allowed to deploy them. I see no reason why an Application created in namespace `foo` should not be able to use an AppProject created in namespace `argocd`, because the connection between the two is made by Argo CD, not K8s. But as already discussed in this thread, it would be really awesome if we could map an AppProject to K8s RBAC instead of configuring its restrictions using a possibly redundant method in Argo CD.

**Comment by mvbakker** [comment]
What do you guys think about an `AppProject` not being namespaced at all? Any major reasons why it should be namespaced? Couldn't it be, and wouldn't it make sense, to make it a cluster-wide resource? From a permissions point of view an `Application` CR wouldn't be able to sync non-namespaced resources already any way by default, unless whitelisted. So in that case, dev teams managing their own `Application` wouldn't be able to sync and/or adjust their own `AppProject` resource, unless explicitly whitelisted.

Additionally, it would be awesome if Argo CD builds upon native K8s RBAC. Though I think that is a topic to discuss outside of the issue at hand regarding the namespacing of `Application` CRs and `AppProject` CRs, wouldn't you agree?

**Comment by dimitarKiryakov** [comment]
Hi @mvbakker 
I think that making Application and AppProject cluster wide is not a good option, at least in our case. Currently we are using namespace installation of argocds in the same cluster (https://github.com/argoproj/argo-cd/tree/master/manifests). This way we achieve tenant isolation for our stakeholders and at the same time managing only one cluster.
I think that we are not the only ones using it this way, there is also argocd operator which you could use to create argocd instances in the same cluster.

**Comment by yydzhou** [comment]
> @juv, Argo CD provides a single control plane that manages resources in multiple clusters. Having Applications CRDs in control plane cluster in one namespace allows us to implement UI/API that presents the state of all managed resources at once.
> 
> If we store applications CRDs in multiple managed clusters it will be really difficult to fetch application status information. However I totally agree with the use case described in this ticket: it would be very nice to let end users create "apps" in target namespaces and "self service" argocd management. I've been working on PoC that resolves that issue for couple weeks. Hope to finish it this weekend and will present to the community.

@alexmt Any progressing on this? This becomes a main pain point for our use case. We have tested that users can easily destroy or crush others' service by creating an application with same name and setup auto-sync policy.  In a multi-tenant environment, It's a big risk and also it's hard to prevent without sacrificing user experience/flexibility.   

We need either global naming mechanism or allowing the application CR to be in different namespaces. So that users' impact/interaction are isolated.

**Comment by jannfis** [comment]
@yydzhou There is an ongoing proposal being discussed at https://github.com/argoproj/argo-cd/pull/6409
