### ISSUE TITLE
Helm applications leak values and parameters into the logs which includes sensitive information.

### ISSUE THREAD

**Issue by Voziv** [argoproj/argo-cd#3479]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Helm values and parameters get logged, revealing sensitive secrets. This is especially an issue when logs are sent to a 3rd party ( new relic / logdna )

**To Reproduce**

Deploy a helm app that has sensitive information in the values provided, or in the parameters. 

Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leaky-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: echo-server
    repoURL: https://ealenn.github.io/charts
    targetRevision: 0.3.0
    helm:
      parameters:
        - name: myOtherApiKey
          value: 'tinysecret'
      values: |
        mySuperSecretApiKey: 'supersecret'
```

**Expected behavior**

Values and parameters to not be logged. Would also be nice to be able to control log levels via an environment variable.

**Version**

```shell
$ argocd version
argocd: v1.5.2+c2c19f4
  BuildDate: 2020-04-15T16:41:59Z
  GitCommit: c2c19f42ad78ed7a6fb70e86aed117be484feb50
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.2+c2c19f4
  BuildDate: 2020-04-15T16:43:12Z
  GitCommit: c2c19f42ad78ed7a6fb70e86aed117be484feb50
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Logs**

```
$ k -n argocd logs argocd-repo-server-5b8c7b98d-p9khx | egrep "supersecret|tinysecret"
time="2020-04-24T13:58:22Z" level=info msg="manifest cache miss: &ApplicationSource{RepoURL:https://ealenn.github.io/charts,Path:,TargetRevision:0.3.0,Helm:&ApplicationSourceHelm{ValueFiles:[],Parameters:[]HelmParameter{HelmParameter{Name:myOtherApiKey,Value:tinysecret,ForceString:false,},},ReleaseName:,Values:mySuperSecretApiKey: 'supersecret'\n,FileParameters:[]HelmFileParameter{},},Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:echo-server,}/0.3.0"
time="2020-04-24T13:58:22Z" level=info msg="helm2 template . --name leaky-app --namespace argocd --kube-version 1.16 --set myOtherApiKey=tinysecret --values /tmp/values-395141004.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions kubernetes-client.io/v1 --api-versions monitoring.coreos.com/v1 --api-versions argoproj.io/v1alpha1 --api-versions snapshot.storage.k8s.io/v1alpha1 --api-versions vault.banzaicloud.com/v1alpha1 --api-versions acme.cert-manager.io/v1alpha2 --api-versions cert-manager.io/v1alpha2 --api-versions etcd.database.coreos.com/v1beta2 --api-versions cilium.io/v2 --api-versions metrics.k8s.io/v1beta1" dir=/tmp/helm135502497/echo-server execID=k1MMS
time="2020-04-24T14:02:09Z" level=info msg="manifest cache hit: &ApplicationSource{RepoURL:https://ealenn.github.io/charts,Path:,TargetRevision:0.3.0,Helm:&ApplicationSourceHelm{ValueFiles:[],Parameters:[]HelmParameter{HelmParameter{Name:myOtherApiKey,Value:tinysecret,ForceString:false,},},ReleaseName:,Values:mySuperSecretApiKey: 'supersecret'\n,FileParameters:[]HelmFileParameter{},},Kustomize:nil,Ksonnet:nil,Directory:nil,Plugin:nil,Chart:echo-server,}/0.3.0"
```

**Comment by jannfis** [comment]
Hm, I'm not sure if I'd consider this a bug. Passing sensitive informations this way seems like a bad idea to me. The Application manifest is possibly stored unencrypted in Git, same goes for possible value files. I think for the audit trail of ArgoCD, it is necessary to log out complete command executions. 

However, I can understand the concern - I'm just not sure whether redacting them from the log output would really solve the problem. Even when redacted, they are still stored unencrypted in the application manifest, which is most likely residing in Git, or is otherwise considered a non-confidential resource.

We have methods for redacting sensitive information from text before further processing them (i.e. when displaying the contents of secrets using the CLI or UI), so basically, these could be applied to Helm parameters and/or value as well. Question is, which of these should be considered confidential?   Obvious parameter names that contain the string `password` or `key` could be a good start, but then what if the parameter `--password-from-key` refers to any key of a `Secret` which holds the actual password -- should this be redacted, or is this valuable auditing information?

So you see, I think it's not that easy. But I'm happy to discuss it further!

Btw, you can modify the log level of the ArgoCD components by passing `--loglevel <LEVEL>` parameter to the container startup options.

**Comment by Voziv** [comment]
>  Passing sensitive informations this way seems like a bad idea to me.

I totally see where this is coming from. I'm a bit concerned that using sops + helm secrets will yield in encrypted values being logged as well. We'll be investigating more options on this front for sure.

> The Application manifest is possibly stored unencrypted in Git, same goes for possible value files.

In our case the repo is private and restricted to only certain members of our team. While not ideal we know that exposure of this information is limited for now. Even if it was encrypted it'd still be a bad idea to have those things logged as our logs are available to more team members than the git repo.

>  which is most likely residing in Git, or is otherwise considered a non-confidential resource.

On this note, is a private git repo (with potentially encrypted values) considered non-confidential?

>We have methods for redacting sensitive information from text before further processing them

Another option here would be to have a `secretValues` key that doesn't get logged, but merged with `values:`.

It may also be a good idea to note in the [documentation](https://argoproj.github.io/argo-cd/user-guide/helm/) that these potentially sensitive values will be logged if entered via `values:` or a values file. This way it's less of a surprise.

**Comment by jannfis** [comment]
I think if you cannot work-around storing sensitive information directly in any value to be used by Helm, a viable workaround would be to store those values in a separate values file. Then set up the application so that it uses the values file instead of explicitly setting the parameters (which end up in command line parameters for Helm) in the `Application` resource. The values inside any values file won't get logged anywhere.

An example of this can be found [here](https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency). However, this would mean to set up the application from a Git repository and defining an umbrella chart with a dependency to your real chart. A plus for this approach would also be that it follows the GitOps pattern better and that it would be easier to integrate with helm secrets plugin or something similar later on :)

Don't get me wrong please, and I don't mean it any way offensive, but I think introducing things like `secretValues` or similar would be a half-baked workaround for problems that should not exist in the first place, or are everything else but good practice. It could encourage people to use it, while they shouldn't. And it might give a false sense of security, because the arguments including possible secrets can still be seen in the process table of any node the process is executed on and the parameters will end up in the Redis cache, too.

But I agree that the documentation should stress that the values for an application will be logged, and that they should not be used for sensitive values.

**Comment by Voziv** [comment]
No offense taken in any way. I think these are all good and valid points. Thanks!
