### ISSUE TITLE
Confusing description for API endpoint

### ISSUE THREAD

**Issue by der-eismann** [argoproj/argo-cd#3495]
**Describe the bug**

In the Swagger UI there is a seemingly duplicate entry in the application service called 
> Get returns an application by name

However only one of these is returning an actual `application` object, the other is referring the `example.com/api/v1/applications/{name}/syncwindows` endpoint.

I don't know which part of the code is auto-generated, but I guess the cause is in the [application.proto](https://github.com/argoproj/argo-cd/blob/master/server/application/application.proto#L233:L233) or [application.pb.go](https://github.com/argoproj/argo-cd/blob/master/pkg/apiclient/application/application.pb.go#L2015:L2015).

**To Reproduce**

Open the Swagger UI and search for `returns an application`

**Expected behavior**

The name of the second entry should be something like 
> Get returns sync windows of the application

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/10406217/80374947-c254d480-8897-11ea-96b0-11dd0dc506ff.png)

**Version**

```shell
v1.5.1+8a3b36b
```

**Comment by jannfis** [comment]
Hi @der-eismann - yes, I agree, this is confusing. 

The reason is as you mentioned in the protobuf source files (`*.proto`), due to C&P and forgetting to adapt the comments. But the comments for the definitions in the source will actually be taken to the documentation of the methods, which will then end up in the swagger specs. Guess QA failed here :)

Our API needs a little love to be actually useful and well-document for the general public. Thanks for bringing this up!
