### ISSUE TITLE
Add field "LIVE For:" to show how much time the Revision was LIVE

### ISSUE THREAD

**Issue by vjpie2002** [argoproj/argo-cd#3513]
# Summary
Add field/label "LIVE For:" to show how much time the Revision was LIVE. Currently when a user clicks on the "History and Rollback", it shows all past Revisions and when it was triggered and completed and also displays the amount of time for which that Revision was LIVE.  But it does not mention what these timings/durations are for (as shown in the attached screenshot where it shows duration without field/key name). It will be good to have a clear label for these timings. 

![image](https://user-images.githubusercontent.com/22686326/80658961-6bd4cb00-8a3c-11ea-96fc-e6722d9fb0e1.png)

What change you think needs making.
Add field/label name in front of the time/duration the Revision was LIVE for. 

# Motivation
It will clearly show customer that a particular Revision was LIVE for so much duration. 

Please give examples of your use case, e.g. when would you use this.
To view all previous Revision history. 

# Proposal

How do you think this should be implemented?
Add field/label name in front of the time/duration the Revision was LIVE for.

**Comment by jannfis** [comment]
Hi @vjpie2002, this seems like a good idea. Thanks for bringing it up! 

Actually, I would refrain from using all CAPS in any of the text (except for abbreviations), and instead of "LIVE for", maybe "Active for" would be a more appropriate choice? Anyway, I'm only thinking loud here, I'm not very opinionated about the wording.

Would you like to submit a PR for this?

**Comment by vjpie2002** [comment]
@jannfis - Yes, "Active for:" is more appropriate. Thanks.

**Comment by rachelwang20** [comment]
Implemented in https://github.com/argoproj/argo-cd/pull/3563
