### ISSUE TITLE
.Capabilities.APIVersions is wrongly evaluated

### ISSUE THREAD

**Issue by olevitt** [argoproj/argo-cd#3631]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD seems to wrongly pass the capabilities to helm so `{{- if .Capabilities.APIVersions.Has "apps/v1beta2" -}}` returns `true` instead of `false`.  

**To Reproduce**

* Use a `1.16+` kubernetes cluster (the bug probably exists on other versions but for this example, it's observable on `1.16+`)
* Create a project deploying this repository : https://github.com/olevitt/bug-argocd-capabilities  (this is a basic minio helm chart with distributed mode enabled)
* Sync will fail with `
the server could not find the requested resource` on `apps/v1beta2/`  

Additional steps :  
* Clicking on the statefulset will confirm that argoCD is expecting a `apps/v1beta2` instead of `apps/v1`  

![image](https://user-images.githubusercontent.com/3159134/82617298-ee7e1f80-9bcf-11ea-98f3-823bd4166f8e.png)

**Expected behavior**

* This repository should deploy fine.  
* `{{- if .Capabilities.APIVersions.Has "apps/v1beta2" -}}` (https://github.com/helm/charts/blob/4124bcd/stable/minio/templates/_helpers.tpl line 60) should return `false`, not `true` on a `1.16+` cluster (see https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).  

**Version**

```shell
v1.5.4+36bade7
```

(not using the argocd CLI, using the UI installed with the latest helm package)

**Logs**

```
time="2020-05-21T23:00:56Z" level=info msg="adding resource result, status: 'SyncFailed', phase: '', message: 'the server could not find the requested resource'" application=minio kind=StatefulSet name=minio namespace=minio phase=Sync syncId=00003-PbBqj
```  

This seems close to #3594

**Comment by jannfis** [comment]
Thanks for this excellent and easy-to-reproduce bug report, @olevitt!

I can reproduce the issue reliably on my K8s v1.18 cluster, but I'm unsure yet about the root cause.

It seems at first glance that `helm template` is indeed correct parametrized, because this is the command used to run the template:

```
helm template . --name-template test-app \
--namespace test \
--api-versions v1 \
--api-versions apiregistration.k8s.io/v1 \
--api-versions apiregistration.k8s.io/v1beta1 \
--api-versions extensions/v1beta1 \
--api-versions apps/v1 \
--api-versions events.k8s.io/v1beta1 \
--api-versions authentication.k8s.io/v1 \
--api-versions authentication.k8s.io/v1beta1 \
--api-versions authorization.k8s.io/v1 \
--api-versions authorization.k8s.io/v1beta1 \
--api-versions autoscaling/v1 \
--api-versions autoscaling/v2beta1 \
--api-versions autoscaling/v2beta2 \
--api-versions batch/v1 \
--api-versions batch/v1beta1 \
--api-versions certificates.k8s.io/v1beta1 \
--api-versions networking.k8s.io/v1 \
--api-versions networking.k8s.io/v1beta1 \
--api-versions policy/v1beta1 \
--api-versions rbac.authorization.k8s.io/v1 \
--api-versions rbac.authorization.k8s.io/v1beta1 \
--api-versions storage.k8s.io/v1 \
--api-versions storage.k8s.io/v1beta1 \
--api-versions admissionregistration.k8s.io/v1 \
--api-versions admissionregistration.k8s.io/v1beta1 \
--api-versions apiextensions.k8s.io/v1 \
--api-versions apiextensions.k8s.io/v1beta1 \
--api-versions scheduling.k8s.io/v1 \
--api-versions scheduling.k8s.io/v1beta1 \
--api-versions coordination.k8s.io/v1 \
--api-versions coordination.k8s.io/v1beta1 \
--api-versions node.k8s.io/v1beta1 \
--api-versions discovery.k8s.io/v1beta1 \
--api-versions ceph.rook.io/v1 \
--api-versions crd.projectcalico.org/v1 \
--api-versions monitoring.coreos.com/v1 \
--api-versions argoproj.io/v1alpha1 \
--api-versions bitnami.com/v1alpha1 \
--api-versions objectbucket.io/v1alpha1 \
--api-versions snapshot.storage.k8s.io/v1alpha1 \
--api-versions rook.io/v1alpha2 \
--api-versions metrics.k8s.io/v1beta1 \
--include-crds"
```
I don't see it passing the incorrect API version. Running this command manually on a clone of your repo, after running `helm dependency build` results in the same (broken) manifests, with the `StatefulSet` in the `apps/v1beta2` API.

However, I've seen that your Chart is actually a Helm v3 chart (`apiVersion: v2`), and that the dependency is a Helm v2 Chart. When converting your Chart to a Helm v2 Chart (i.e. moving the dependency specification to `requirements.yaml` and changing `apiVersion` to `v1`), then running `helm2 dependency build` followed by `helm2 template ...` (without `--include-crds`), the manifests get rendered correctly.

So I believe that this is rather a compatibility issue between Helm v2 and Helm v3.

**Comment by olevitt** [comment]
Thanks for your reply !  

I made further tests (most of which you already did) and I also conclude that the bug arise when using helm v3 on a helm v2 chart.  
It is not related to chart dependency / inclusion.  
It can be reproduced using the stable/minio chart : `helm template stable/minio --set mode=distributed [--api-versions=theListYouProvided]` produces  `apps/v1beta2` (wrong) statefulsets when using helm `v3` but `apps/v1` when using helm `v2`.  

Anyway, I think this is a bug in helm and not in argocd. I think we can safely close this issue. I will open an issue there.

Thanks for your time !  

PS : if I may, how did you get the helm template command used by argoCD ? I set logLevel=debug on applicationController but could not get much more logs.

**Comment by jannfis** [comment]
> PS : if I may, how did you get the helm template command used by argoCD ? I set logLevel=debug on applicationController but could not get much more logs.

Actually, all manifest operations are executed in `argocd-repo-server` pods, so it's in their logs :)

**Comment by pburgisser** [comment]
Just for my information, is this a bug or a limitation?
The harbor chart is trying to deploy a  `apiVersion: networking.k8s.io/v1`  ingress on a k8s 1.18 where the apiVersion is  `apiVersion: networking.k8s.io/v1beta1` due to the a wrong evaluation of ` .Capabilities.KubeVersion.GitVersion` which always return 1.20 when deploying the chart on ArgoCD. 
https://github.com/goharbor/harbor-helm/blob/81fb1ee3b804e94b63d3c32da60677d604172f8b/templates/ingress/ingress.yaml#L31-L37
