### ISSUE TITLE
Warning logs related to CustomResourceDefinition (CRD)

### ISSUE THREAD

**Issue by sorinjulean** [argoproj/argo-cd#3670]
**Describe the bug**
argocd-application-controller logs periodically:

`level=warning msg="Failed to convert resource: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30\""`

**To Reproduce**
Deploy ArgoCD with with argo-cd helm chart from https://argoproj.github.io/argo-helm version 2.3.5
Deploy Argo Workflows with argo helm chart from https://argoproj.github.io/argo-helm version 0.9.4

**Expected behavior**
Not having these warning messages

**Screenshots**

**Version**

```shell
argoproj/argocd:v1.5.4
argoproj/workflow-controller:v2.7.6
```

**Logs**

```
level=warning msg="Failed to convert resource: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30\""```

**Comment by tehho** [comment]
Got the same error after an upgrade from 1.16.7 to 1.16.9. @sorinjulean what k8s version are you using?

**Comment by aimbot31** [comment]
Got the same error, using k8s 1.16.8.

**Comment by sorinjulean** [comment]
I can reproduce it also on v1.18.3

**Comment by aimbot31** [comment]
I think #3670 is related

**Comment by sorinjulean** [comment]
> I think #3670 is related

3670 ?

**Comment by sorinjulean** [comment]
If CRDs are created before Argo Workflows and set installCRD=false for the Argo Workflows helm chart, warning messages are not logged any more

**Comment by aimbot31** [comment]
#3663 seems to be related ?

**Comment by alexmt** [comment]
This error message does not indicate any issue. We need to remove it to stop confusion.

**Comment by jannfis** [comment]
We should also take into account that an explicit convert is deprecated in K8s since a couple of versions (see https://github.com/kubernetes/kubectl/issues/725). Internally, we use the `ConvertToVersion()` method from the `kubectl` package, which might (or might not be) affected.

Running `kubectl convert` on the command line produces a warning such as

```
kubectl convert is DEPRECATED and will be removed in a future version.
In order to convert, kubectl apply the object to the cluster, then kubectl get at the desired version.
```

So maybe, we should remove the explicit convert as well: https://github.com/argoproj/gitops-engine/blob/7d3da9f16e353692824a6e83fc31de113b6a9251/pkg/cache/cluster.go#L730
