### ISSUE TITLE
Track pre-release versions of a packaged helm chart

### ISSUE THREAD

**Issue by fransguelinckx** [argoproj/argo-cd#3671]
# Summary

Atm argocd can track wildcard versions, e.g. `1.2.*` or `1.*`
It can be useful to be able to track pre-release versions, as defined in [semver 2.0.0](https://semver.org). E.g. `1.0.0-alpha.*`, which would track `1.0.0-alpha.1`, `1.0.0-alpha.2` etc.

Extra 1: add an option to fall back on another version if no match can be found for the first range wildcard. E.g. `1.2.0-alpha.* || 1.2.*`

Extra 2: when no match can be found for `1.2.*`, argocd could fall back on pre-release versions like `1.2.0-alpha.1`, taking the version number matching `1.2.*` with the highest precedence.

# Motivation

* Example 1: `1.2.0-alpha.* || 1.2.*`
This would make it very easy to track feature branches in a microservice environment.
E.g.: microservices A and B have versions that match `1.2.0-alpha.*`, containing a new feature in progress. Microservices C and D don't contain a part of that work in progress, so they fall back to `1.2.*` for example.

* Example 2: `1.2.*`
This would allow argocd to track pre-release version up until a stable release.

# Proposal

The [semver spec](https://semver.org/#spec-item-11) defines the concept of precedence, which can be used to resolve the wildcards in pre-release labels.

**Comment by david-l-riley** [comment]
It is worth noting that Helm already has some special semver rules for pre-release versions: it will not use pre-release charts unless explicitly instructed to do so either by including a prerelease component in the semver spec (e.g. `~1.2.0-0` for all in `1.2` including all prereleases, since they are lexically sorted) or with the `--devel` flag (which implicitly sets the version to `>0.0.0-0`). This is not part of the semver specification, it is Helm-specific behavior.

Note also that in semver, `1.2.0-alpha.n` would be the fallback if `1.2.0` cannot be found, as release versions always supersede prerelease versions (annoyingly, semver 2.0.0 does not include the concept of "post" release versions such as distribution patches, etc., which means any small modifications need to increment the version number in order to provide such things). Semver precedence rules also get pretty sticky when it comes to the prerelease versioning, as the tilde operator operates on the main version, not prerelease (thus `~1.2.0-alpha.1` will match `1.2.0-alpha.99` but also `1.2.1`). 

I think it would be a good idea to mostly use Helm's existing machinery to do this, since there are a lot of valid reasons not to include prerelease charts by default (which would conflict with the proposal for example 2 here). Perhaps if we're parsing the wildcards and generating semver (e.g. `1.2.*` becomes `~1.2.0`), it would be good to include a boolean to include prereleases if they're not already specified. Otherwise, I believe Argo already supports using straight semver ranges to specify them directly.

**Comment by kevinnoel-be** [comment]
Maybe I misunderstand the request, but today you can already specify a `targetRevision` with ranges like: `>=1.2.0-0` which will include pre-released versions. It seems that [this package](https://github.com/Masterminds/semver#checking-version-constraints) is used behind the scenes and covers most if not all possibilities?

**Comment by fransguelinckx** [comment]
Indeed, I'll close the issue.
