### ISSUE TITLE
Create integration with cdk8s

### ISSUE THREAD

**Issue by cweidinger** [argoproj/argo-cd#3691]
# Summary

I would like to provide a cdk8s application specification (similar to how I can provide a helm chart from a git source) and have argocd run it to generate the yaml that gets applied to kubernetes.

# Motivation

Because cdk8s only generates k8s yaml and not helm templates, it is not possible to optionally create a cdk8s generated resource based on parameters provided through the ArgoCD Application CRD when argo is deploying it. I'd like to have my logic in cdk8s to be able to use the values provided to it by the ArgoCD application CRD.

# Proposal

There is talk in cdk8s about doing this using argo's plugin functionality https://github.com/awslabs/cdk8s/issues/162. I don't know if that would be enough. I'm not really sure who's work this would be but a collaboration seems likely.

**Comment by dmizelle** [comment]
We're thinking about using cdk8s for some stuff in our org, and we 100% solely use ArgoCD for deployments. Some thoughts I wanted to ask the group about before I took a swing at this one:

1. It looks like this is going to require nodejs in order to run cdk8s. Its going to bloat the image slightly.
2. For projects generated with cdk8s, they can either be "written" in Javascript, Python, or Java. This is sort of a weird spot for me, because then in order to support 100% of the functionality of generating projects with cdk8s, the argocd image would bloat to contain Node, Python3.7/3.8, and Java. Which seems.... less than ideal, no?
3. We can do some autodetection around which language a cdk8s project is using by parsing cdk8s.yaml and looking at the language attribte.

**Comment by TomaszSzusterTR** [comment]
Hey @dmizelle

The image will be bigger obviously, but from my point of view a lot of K8s clusters sits on fast storage thus loading container with ArgoCD shouldn't take sooo much time.
Even if we follow a security rule of thumb to kill container every 24 hours then this will be a blip to recreate new pod.

There are options to mitigate slower startup time... from top of my head:
* create dedicated containers for every language which cdk supports (one for python, one for java etc)
* configure container to use volumes in which the runtimes will be provided (python runtime, java etc) - this way the Argo container would need node installed.

**Comment by blakepettersson** [comment]
Seems like this should be possible with a [CMP](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) nowadays.
