### ISSUE TITLE
Progressing Health status for Bitnami SealedSecret

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#3707]
# Summary

In Bitnami SealedSecrets  v0.12, SealedSecrets now has a status field which we can key off to decide if a SealedSecret is fully deployed

https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#status-field

> Now the sealed secrets controller updates the Status field of the SealedSecrets resources. This makes it easier for automation like ArgoCD to detect whether (and when) the controller has reacted to changes in the SealedSecret resources and produced a Secret. It also shows an error message in case it fails (many users are not familiar with k8s events and they may find it easier to see the error message in the status).

We should implement a Health check to place a SealedSecret in a Progressing state, if the controller has not yet "reacted to changes in the SealedSecret resources and produced a Secret".

**Comment by sbose78** [comment]
Hi!

Is this something that you would expect to be added to https://github.com/argoproj/argo-cd/tree/master/resource_customizations , assuming I'm reading the right docs :)

**Comment by astein-te** [comment]
@jessesuen I'd be interested in taking a crack at this (unless @sbose78 wants it - he certainly has first dibs :) )

**Comment by sbose78** [comment]
Go ahead @astein-te ! :)

**Comment by jangraefen** [comment]
Hello @astein-te. Did you made any progress on this one? Otherwise I would like to take shot 😄.

**Comment by jangraefen** [comment]
Since I did not get any feedback until now, I will go ahead and start on this tomorrow 🙂.

**Comment by jannfis** [comment]
This feature was implemented by https://github.com/argoproj/argo-cd/pull/5503 - however, the default behavior of `sealed-secrets` controller has changed again and now the administrator has to explicitly enabling status updates using either `--update-status` command line parameter or `SEALED_SECRETS_UPDATE_STATUS` environment. Apparently, there is high CPU consumption when this feature was enabled (see https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#v0122).

So, with #5503 merged, and a `sealed-secrets` controller with default configuration is running in the cluster, the `SealedSecret` resources will stay endlessly in progressing state. I have already discussed with @chetan-rns about possible solutions to this. I suggested to just return `HEALTHY` if no `status` field is found in the resource, but as @chetan-rns correctly pointed out, this can also be the state if there is a general problem with the availability of the `sealed-secrets` controller.

I guess we could point this out in the FAQ (e.g. "Why are my sealed secrets resources always in progressing state?") and point the user on instructions on how to enable status reporting for the `sealed-secrets` controller, but in my initial tests I found that CPU consumption bug to be still valid (the controller went up to use about 0.7 CPUs for a cluster with maybe 20 `SealedSecrets` resources).

**Comment by jangraefen** [comment]
I agree with the idea of returning `HEALTHY` if no `status` field is set. In my opionion, the default ArgoCD configuration should be compatible with the default SealedSecrets configuration. 

That no status might stem from a misbehaving SealedSecrets controller is very valid point, but since there is no clean solution here, I think we should make a 80-20 decision here. Marking the `SealedSecret` as healthy if no status is set will be the correct call in +80% of the situation and only in the absolute manoritiy of situations this will be wrong. Also, the ArgoCD UI will show no secret generated from the `SealedSecret`, which already tells me something is off.

**Comment by jannfis** [comment]
FWIW, I've sent a PR to sealed secrets to fix the high CPU consumption due to constant status updates. Maybe they'll re-enable status updates by default again :)

https://github.com/bitnami-labs/sealed-secrets/pull/525

**Comment by chetan-rns** [comment]
Thanks for the fix @jannfis . I hope they include this in the next release. For folks who would use an older version, should we update the script to return healthy if there's no status field?

**Comment by jannfis** [comment]
@jangraefen I think in this scenario, the 80/20 here would be that within the 80% of use-cases would be cluster bootstrapping. User fires up a sync that might include `sealed-secrets` controller (with the private key possibly already existing in the cluster), along with several other resources that rely on unsealing the sealed secrets. So, `sealed-secrets` controller might take a while to start up, but sync would still be progressing through the waves. And I think this was also the main use case for actually including status on this by default.

@chetan-rns We should wait a little on what `sealed-secrets` will do. When they merge the patch (or fix the issue otherwise in a timely manner), and re-enable status by default, I think we should do not much more except updating our documentation with some bits and pieces. If user will be unable to update to sealed secrets controller with status reporting and fix included, we may give them a snippet like this to include with `resource.customizations` to disable progressing state all together then:

```yaml
  resource.customizations: |
    bitnami.com/SealedSecret:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Controller doesn't report resource status"
        return hs
```

What do you guys think of that? 

I will leave this issue open and attach it to v1.9 milestone, so we'll not forget about it before we're actually releasing v1.9.

**Comment by jangraefen** [comment]
@jannfis I am not sure if I understand health checks correctly then, which easily might be the case here 😄.

In my understanding, having the health check as it is currently implemented with the defaults the sealed secrets controller currently has, a `SealedSecret` will always display as progressing, no matter if it provisioned a `Secret` or not. That would not only affect cluster bootstrapping, but also all applications which contain a `SealedSecret` throughout their whole life-cycle.
If this is not the case however, I fully agree with your point! Otherwise, I think we should rethink the decision.

**Comment by chetan-rns** [comment]
@jannfis Thanks for adding this to v1.9. After the status is made default, we can add a section under FAQ for users who don't have this fix to get rid of progressing state.

**Comment by jangraefen** [comment]
@jannfis @chetan-rns Since it seems likely that the sealed-secret-controller soon has a fix for the CPU issue and the status condition get enabled by default again (Thank you @jannfis for fixing this!), I created a PR adding a section to the FAQ for users that might still run into the discussed issue of `SealedSecrets` being stuck in the Progressing state.
