### ISSUE TITLE
PostSync hook triggered on repo sync, no deployment was applied

### ISSUE THREAD

**Issue by CurryWurry** [argoproj/argo-cd#3751]
**Describe the bug**
We have a PostSync hook that sends out emails when a deployment is performed. ArgoCD monitors a "deployments" directory of our GitOps repo for updated manifests and will deploy them to our Openshift cluster. We have noticed that this PostSync trigger is being executed when we push changes to the HEAD of our GitOps repo, but no new or updated manifests were committed to the "deployments" directory. 

**Expected behavior**
The documentation states "During a Sync operation, Argo CD will apply the resource during the appropriate phase of the deployment". We would expect that the PostSync hook is only triggered during an actual deployment, not when syncing a repo. It is perfectly possible that commits were done to a GitOps repo, without actually performing a deployment (which is only triggered by application changes by default.)

We never noticed this behavior before, but that being said, ArgoCD reports the deployment status as "outofsync" as there's a slight difference in a cpu limit ('2' vs 2 in the live manifest). Maybe this triggered the PostSync trigger?

**Version**
ArgoCD v1.4.2+48cc

**Comment by jessesuen** [comment]
We believe this is happening because your Application is perpetually OutOfSync due to the difference in the cpu limit. This OutOfSync condition will cause a new operation to happen on every commit. To prevent this, the resources must remain Synced which will prevent an operation to automatically get invoked on a new commit.

Please try with v1.7 which has better diffing capability to prevent detecting the cpu limit difference as a diff.
