### ISSUE TITLE
Deploy multiple microservices

### ISSUE THREAD

**Issue by bmartima** [argoproj/argo-cd#3768]
If I have several microservices made with helm and would like to deploy them on Argo CD, what would be the best practice?
- deploy each microservice in a different application
- deploy all microservices in the same application

**Comment by iam-veeramalla** [comment]
In my opinion it is a good practise to keep the approach as simple as posible. An application per micro service would be a better approach.

@bmartima this issue is in opened state for almost more than 6 months now. Did you figure out which approach is better for you ? Please let me know if this issue can be closed.

**Comment by Aliabbask08** [comment]
deploy microservices in same Application with multi repo..i see there's no feature.
Can someone please suggest best way to keep all multi repo(i.e each repo/service) in same Application.
As its very difficult to maintain multiple applications, also less visuality.
Looking for unified dashboard..thanks!
