### ISSUE TITLE
Bug: Helm hooks with deletion policies don't sync

### ISSUE THREAD

**Issue by lippertmarkus** [argoproj/argo-cd#3928]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Helm Charts including hooks with a deletion policy don't sync properly. The first sync after creating the application is successful but afterwards an upgrade, a deletion or a manual sync locks the application in a sync loop.

**To Reproduce**

1. Use an application with Helm Hooks and a deletion policy, e.g. Argo Workflows (see [chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo) and [resources with hooks and deletion policies](https://github.com/argoproj/argo-helm/blob/master/charts/argo/templates/workflow-aggregate-roles.yaml)):
    ```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo
      namespace: argocd
    spec:
      destination:
        namespace: argo
        server: https://kubernetes.default.svc
      project: default
      source:
        chart: argo
        helm:
          valueFiles:
          - values.yaml
          values: ""
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 0.9.8
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    ```

2. Deploy the application:
    ```bash
    kubectl create ns argo
    kubectl apply -f argo-app.yaml
    ```

3. Check that the first sync was successful. Now either click on Sync, upgrade the application or try to delete the application.

4. Observe that you're stuck in a sync loop.

*Further information*

- If you tried to sync in step 3 and stuck in the sync loop then deleting the following two cluster roles with Helm hooks and deletion policies manually allows for the sync to continue successfully. Only those two resources are stuck in a sync loop:
    ```bash
    kubectl delete clusterrole/argo-aggregate-to-admin
    kubectl delete clusterrole/argo-aggregate-to-edit
    ```

- If you tried to delete the application in step 3 then you need to manually delete all Cluster Roles and Cluster Role Binding for the deletion to be successful. All those resources are stuck in the sync loop.

- I first thought this has to do only with the aggregate roles and tried using `ignoreAggregatedRoles`
    ```yaml
    resource.compareoptions: |
            ignoreAggregatedRoles: true
    ```
    But as @jannfis pointed out, this is not the case: https://github.com/argoproj/argo-cd/issues/3602#issuecomment-652349537

- If you disable the resources with Helm hooks and deletion policies, everything works like intended. E.g. set the following in the application definition:
    ```yaml
    # ...
    values: |
        createAggregateRoles: false
    # ...
    ```

**Expected behavior**

Sync should work even when using a Helm Chart with Hooks and deletion policies.

**Screenshots**

Sync Loop of the hooks with deletion policies:
![image](https://user-images.githubusercontent.com/1463140/87221388-ffdfde80-c36b-11ea-9f28-ee9f9ba00ac3.png)

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:43:39Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: windows/amd64
argocd-server: v1.6.1+159674e
  BuildDate: 2020-06-19T00:41:05Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

Application Controller:
```
...
time="2020-07-11T10:24:17Z" level=info msg="Reconciliation completed" application=argo dedup_ms=0 dest-namespace=argo dest-server="https://kubernetes.default.svc" diff_ms=33 fields.level=1 git_ms=14 health_ms=6 live_ms=23 settings_ms=0 sync_ms=0 time_ms=132
time="2020-07-11T10:24:17Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=argo
time="2020-07-11T10:24:17Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argo)" application=argo
time="2020-07-11T10:24:17Z" level=info msg=syncing application=argo skipHooks=false started=false syncId=08247-uVthf
time="2020-07-11T10:24:17Z" level=info msg="getRepoObjs stats" application=argo build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=20 unmarshal_ms=19 version_ms=0
time="2020-07-11T10:24:17Z" level=warning msg="Failed to convert resource: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""
time="2020-07-11T10:24:17Z" level=warning msg="Failed to convert resource: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""
time="2020-07-11T10:24:17Z" level=warning msg="Failed to convert resource: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""
time="2020-07-11T10:24:17Z" level=warning msg="Failed to convert resource: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""
time="2020-07-11T10:24:17Z" level=info msg=tasks application=argo syncId=08247-uVthf tasks="[PreSync/0 hook rbac.authorization.k8s.io/ClusterRole:argo/argo-aggregate-to-admin obj->obj (,,), PreSync/0 hook rbac.authorization.k8s.io/ClusterRole:argo/argo-aggregate-to-edit obj->obj (,,), PreSync/0 hook rbac.authorization.k8s.io/ClusterRole:argo/argo-aggregate-to-view obj->obj (,,), Sync/0 resource /ConfigMap:argo/argo-workflow-controller-configmap obj->obj (,,), Sync/0 resource /ServiceAccount:argo/argo obj->obj (,,), Sync/0 resource /ServiceAccount:argo/argo-server obj->obj (,,), Sync/0 resource apiextensions.k8s.io/CustomResourceDefinition:argo/clusterworkflowtemplates.argoproj.io obj->obj (,,), Sync/0 resource apiextensions.k8s.io/CustomResourceDefinition:argo/cronworkflows.argoproj.io obj->obj (,,), Sync/0 resource apiextensions.k8s.io/CustomResourceDefinition:argo/workflows.argoproj.io obj->obj (,,), Sync/0 resource apiextensions.k8s.io/CustomResourceDefinition:argo/workflowtemplates.argoproj.io obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRole:argo/argo-server obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRole:argo/argo-server-cluster-template obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRole:argo/argo-workflow-controller obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRole:argo/argo-workflow-controller-cluster-template obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRoleBinding:argo/argo-server obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRoleBinding:argo/argo-server-cluster-template obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRoleBinding:argo/argo-workflow-controller obj->obj (,,), Sync/0 resource rbac.authorization.k8s.io/ClusterRoleBinding:argo/argo-workflow-controller-cluster-template obj->obj (,,), Sync/0 resource /Service:argo/argo-server obj->obj (,,), Sync/0 resource apps/Deployment:argo/argo-server obj->obj (,,), resource apps/Deployment:argo/argo-workflow-controller obj->obj (,,), Sync/0 resource networking.k8s.io/Ingress:argo/argo-server obj->obj (,,)]"
time="2020-07-11T10:24:17Z" level=info msg="Applying resource ClusterRole/argo-aggregate-to-view in cluster: https://10.43.0.1:443, namespace: argo"
time="2020-07-11T10:24:17Z" level=info msg="Applying resource ClusterRole/argo-aggregate-to-admin in cluster: https://10.43.0.1:443, namespace: argo"
time="2020-07-11T10:24:17Z" level=info msg="Applying resource ClusterRole/argo-aggregate-to-edit in cluster: https://10.43.0.1:443, namespace: argo"
time="2020-07-11T10:24:17Z" level=info msg="Skipping auto-sync: another operation is in progress" application=argo
time="2020-07-11T10:24:17Z" level=info msg="Update successful" application=argo
...
```

**Comment by jannfis** [comment]
Thanks for this issue. I could reliably reproduce it on of my test clusters with the Argo workflows Helm chart, but could not with my local development cluster. That left me a little confused. On the system where I could reproduce the issue, I could observe that two of the three cluster roles (implemented as Helm hooks) were left in "Deleting" state on a successive sync, and thus the sync never finished. The first one to be deleted was deleted successfully.

After doing some more research, I believe this is some kind of bug in K8s regarding garbage collection of deleted resources. ArgoCD uses [foreground deletion](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion), which blocks until the garbage collection actually removes the resource. As you described, deleting the cluster role with `kubectl delete` (or through the ArgoCD UI resource deletion with `force` option), eventually removed the resources and the sync then continued. Both methods (`kubectl delete` and `force` deletion within ArgoCD) do not use ForegroundDeletion, but rather BackgroundDeletion policy.

So what confused me most was that my test cluster was behaving differently than my dev cluster, and the difference is that my Dev cluster was running K8s v1.18.4 while my test cluster was still on v1.18.2. I found the following in the K8s release notes of v1.18.4:

> Fixed a regression preventing garbage collection of RBAC role and binding objects (#90534, @apelisse) [SIG Auth]

(https://github.com/kubernetes/kubernetes/pull/90534)

I upgraded my test cluster to v1.18.4 and the Argo WF Helm chart is now syncing correctly successively. However, since I have seen a similar behaviour with other kind of resources used for hooks (i.e. Patroni has something similar, using an `Endpoint` resource that refuses to delete on successive syncs) and I also found more issues in K8s issue tracker regarding Garbage Collection and Foreground Deletion, I think just upgrading K8s is not the final solution. I'm also not sure whether this only affects those resources that are implemented as hooks with a pre-sync deletion policy.

May I ask which K8s version you are running?

**Comment by lippertmarkus** [comment]
Thanks for investigating. I'm using k8s v1.18.3

**Comment by jannfis** [comment]
I am wondering whether we should revert to background deletion for resources that are hooks (because it's used during sync), but I guess this could have unwanted side effects. On the other hand, the current foreground deletion tends to break a lot of Helm chart - it's quite a common pattern to use pre-install or pre-upgrade hooks in recent charts, and those will not sync without manual intervention currently.

@jessesuen @alexmt What's your take on this?

**Comment by servo1x** [comment]
We're also running into this issue with the kube-prometheus-stack chart. It's incredibly frustrating to have to delete these resources manually every time. Our clusters are 1.18.8, some clusters sync fine but others just get stuck on delete until we manually intervene.
