### ISSUE TITLE
Logout Redirect

### ISSUE THREAD

**Issue by jayrmehta** [argoproj/argo-cd#4452]
# Summary
Allow configuration to redirect user to custom URL after user clicks Logout button.

# Motivation
This feature will be very handy when third party integrations for authentications are user. Especially when argo heavily relies on 3rd party for authentication needs.

# Proposal
When Okta integrated, an Okta session will persist even after the user invalidates their session with the Logout button. There is a security risk present for as long as the Okta session remains valid, which depends on the Okta configurations/timeout.

If the app could be redirected to the Okta /logout URL, then the user-initiated logout would also invalidate the Okta session.

There could be other use cases for Logout Redirect other than this (general functionality or security). This feature request should not be confused with SSO Global Logout, which is much more complicated to implement. No response is expected after the app is redirected to the custom URL.

**Comment by jessesuen** [comment]
I agree. Proper logout is important

**Comment by jessesuen** [comment]
API server needs to be changed to allow redirecting to something other than `/` upon logout.

**Comment by jaideepr97** [comment]
HI, I'm curious about this issue and would like some more context if possible 
How should a user be able to input their custom URL? Would this be a field in the UI somewhere?

**Comment by Moadfinn** [comment]
This is about giving admins, who are configuring their Argo environment, to set the redirect URL. Normal users will just see the behavior but have no control over it.

**Comment by jaideepr97** [comment]
got it
I would like to take a crack at this if that's okay

**Comment by jaideepr97** [comment]
Hey @jessesuen @Moadfinn 
I'm trying to test login/logout from the argocd-ui running locally by applying the manifests found in the tests folder but I'm unable to reproduce the login/logout behavior because it may be getting bypassed in a way (it lets me past the login page but doesn't actually show me any user info - says I'm not logged in)
is this the expected behavior while running locally, and would I need some kind of oauth setup side-by-side to be able to work on this issue?
