### ISSUE TITLE
Create API objects, which are not within the server namespace

### ISSUE THREAD

**Issue by johannwagner** [argoproj/argo-cd#4483]
I just tried to create an application through the API within a different namespace than my argo server lives in. My argo server uses `argocd` as namespace, I wanted to create an application within `mytenant-dev`. If I change the namespace within my request to `argocd` it works fine.

Error Message: 
```
{"error":"the namespace of the provided object does not match the namespace sent on the request","code":9,"message":"the namespace of the provided object does not match the namespace sent on the request"}
```

 I figured out, that it may be this piece of code, where you call the Kubernetes API server on your server namespace to add a resource but you may want to use the `metadata.namespace` for the application, which should be created. I do not know, if this has any security implications.

https://github.com/argoproj/argo-cd/blob/25823a4625181b9f8bfeb38e99f2b5e0110b6a3e/server/application/application.go#L171

**Comment by johannwagner** [comment]
Oh, this is technically not a bug, its a feature. The application object does not live within the destination namespace, it lives within the server namespace. Thats neat, but not documented anywhere.

**Comment by jannfis** [comment]
Actually, it is documented, but not sufficiently and admittedly somewhat hidden: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#applications - I agree we have some serious debt regarding the docs.

Just as a heads-up for the reasoning behind this restriction: it is based on multiple assumptions, but one of the main reasons is that in multi-cluster environments, the Argo CD CRDs do not have to be installed (and maintained) in destination clusters. So having a central place for the CRs simplifies those things a lot. Also, typically you don't want people being able to create applications in random places, since this could lead to undesired side effects (i.e. two applications conincidently syncing to same namespace, possibly overwriting of existing resources, etc) and severe security implications.
