### ISSUE TITLE
kubectl explain doesn't work as expected

### ISSUE THREAD

**Issue by rdpa** [argoproj/argo-cd#4488]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
`kubectl explain application` and `kubectl explain appproject` only return the following:
```
KIND:     Application
VERSION:  argoproj.io/v1alpha1

DESCRIPTION:
     <empty>
```
```
KIND:     AppProject
VERSION:  argoproj.io/v1alpha1

DESCRIPTION:
     <empty>
```

**To Reproduce**
run `kubectl explain` for either application or appproject

**Expected behavior**
`kubectl explain` would return helpful explanations for each resource.

**Screenshots**
n/a

**Version**

```shell
argocd: v1.7.6+b04c25e
  BuildDate: 2020-09-19T00:53:13Z
  GitCommit: b04c25eca8f1660359e325acd4be5338719e59a0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:56:23Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Logs**
n/a

**Comment by jannfis** [comment]
Hey, good catch. I believe that is because we generate old-style. single-versioned CRDs using `trivialVersions=true` argument to the CRD generator [here](https://github.com/argoproj/argo-cd/blob/f93da5346c3dfe0ec75549fd78b2d30ce7d5cfad/hack/gen-crd-spec/main.go#L30). CRDs generated this way are not versioned, and probably `kubectl explain` expects a versioned CRD. 

I believe this was done for compatibility reasons to K8s versions < 1.13 back when it was written, and we never cared to update it.

@jessesuen @alexmt Is there something speaking against using versioned CRDs instead of the non-versioned format we use right now? This might drop support for K8s versions <1.13, but I think this would be a good thing to do anyway...

**Comment by jessesuen** [comment]
> @jessesuen @alexmt Is there something speaking against using versioned CRDs instead of the non-versioned format we use right now? This might drop support for K8s versions <1.13, but I think this would be a good thing to do anyway...

I think it's time we can bump up our minimum version to support this use case.

**Comment by jannfis** [comment]
After a little more research, I think the root cause is that we generate the spec for the (now deprecated) CRD API `apiextensions.k8s.io/v1beta1`, which is GA as `apiextensions.k8s.io/v1` since K8s v1.16.

By generating `apiextensions.k8s.io/v1` version CRD, we would therefore break compatibility with K8s <= 1.15. Although 1.15 is out of support already, this is probably not a good thing to do. The `apiextensions.k8s.io/v1beta1` is deprecated since a while and will be finally [removed in K8s 1.22](https://github.com/kubernetes/kubernetes/issues/82022).

As we don't have a K8s support strategy yet, I'm reluctant to create a change to change to `apiextensions.k8s.io/v1`. However, I personally think we should follow the the K8s project and support those versions that are considered in maintenance, too.

**Comment by jessesuen** [comment]
> By generating apiextensions.k8s.io/v1 version CRD, we would therefore break compatibility with K8s <= 1.15. Although 1.15 is out of support already, this is probably not a good thing to do. The apiextensions.k8s.io/v1beta1 is deprecated since a while and will be finally removed in K8s 1.22.

I agree we shouldn't remove support for <= 1.15. One thing I've seen other projects do is to generate two sets of CRDs, the v1 and the v1beta1. controller-tools has an option to generate both in one go. Maybe thats the way we should go?

**Comment by jgwest** [comment]
Long since resolved.
