### ISSUE TITLE
Diff remains empty after making manual changes via kubectl

### ISSUE THREAD

**Issue by BartoszZawadzki** [argoproj/argo-cd#4661]
Checklist:

* [/] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [/] I've included steps to reproduce the bug.
* [/] I've pasted the output of `argocd version`.

**Describe the bug**

We've made manual changes via kubectl to our DeamonSets. Those changes included adding a Label, a volumeMount and a Volume. We can clearly see the difference in ArgoCD UI (Live Manifest != Desired Manifest). When we go the "Diff" tab it remains empty, thus our application is marked as being "in-sync". This is not the expected behavior as we trust ArgoCD to show us the diff and mark application as out-of-sync.

**To Reproduce**

1. Manually edit (via kubectl) a Deployment or a DaemonSet and add a label, volumeMount and Volume
2. Wait or refresh the application (that you've made the aforementioned changes to) in ArogCD UI
3. Notice the difference betwen 'Live Manifest' and 'Desired Manifes' and see that 'Diff' remains empty and application is marked green (in-sync)

**Expected behavior**

Changes visible in 'Diff' and application marked yellow (out-of-sync)

**Screenshots**

**Version**

```shell
argocd: v1.7.7+33c93ae
  BuildDate: 2020-09-29T04:57:34Z
  GitCommit: 33c93aea0b9ee3d02fb9703cd82cecce3540e954
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
This is expected behavior. Your changes are treated the same as if a controller made an out-of-band edit of your manifests. The only diff that we report, are the ones that are on fields managed by the user. This behavior matches `kubectl diff`.

**Comment by BartoszZawadzki** [comment]
Could you tell me if that behavior changed recently? If yes, what made that change? I'm asking because we're pretty sure that when we added volumes or volumeMounts the app was marked as being out-of-sync.

**Comment by josecv** [comment]
@jessesuen we're having the same issue with service selectors; manually adding a label selector to a service's `spec.selector` does not generate a diff. AFAIK the service controller doesn't mutate `spec.selector`, so this seems like a bug.
Interestingly, mutating an _existing_ label selector's value does result in a diff.

**Comment by darshanime** [comment]
Diffing is done against a manifest file. If the manifest does not have a field, manually adding it to live object won't make it show up on the diff. 

> mutating an existing label selector's value does result in a diff.
This happens if the label selector is present in the actual manifest the diff is renerated against.

This is the `kubectl diff` behaviour too.

**Comment by georgevella** [comment]
Hi everyone.  It seems we are also experiencing this issue and since I've found this issue I'm gonna post here instead of creating a new one, for now.  

We have had chart upgrades that change labels and annotations (latest one that did this was the nginx ingress controller chart). Changing the chart version resulted in some pod labels getting replaced, while service selector labels where not, hence resulted in us having to update resources manually (deletion was not an option).  Now I've reproduced the diff issue again by adding an annotation to an ingress manually - without updating the manifests in the git repo - Argo does not report that the app is out of sync even though it diverged from the git repo manifests.

I understand that the issue is with `kubectl diff` - I generated the manifests and confirmed it locally - but this is:
1. a change in argo behaviour - we were running 1.4 before jumping to 1.8 and changing the resources directly always caused the the app to be out of sync
2. now I cannot trust what argo is reporting because the manifests generated in the git repo and what's deployed in the cluster can be different.  I cannot consider the git repository as the source of truth.

Either way I'll try to allocate some time and investigate possible diff alternatives since clearly this is the expected behaviour.

**Comment by musabmasood** [comment]
> Hi everyone. It seems we are also experiencing this problem and since I've found this issue I'm gonna post here instead of creating a new one, for now.
> 
> We have had chart upgrades that change labels and annotations (latest one that did this was the nginx ingress controller chart). Changing the chart version resulted in some pod labels getting replaced, while service selector labels where not, hence resulted in us having to update resources manually (deletion was not an option). Now I've reproduced the diff issue again by adding an annotation to an ingress manually - without updating the manifests in the git repo - Argo does not report that the app is out of sync even though it diverged from the git repo manifests.
> 
> I understand that the issue is with `kubectl diff` - I generated the manifests and confirmed it locally - but this is:
> 
> 1. a change in argo behaviour - we were running 1.4 before jumping to 1.8 and changing the resources directly always caused the the app to be out of sync
> 2. now I cannot trust what argo is reporting because the manifests generated in the git repo and what's deployed in the cluster can be different.  I cannot consider the git repository as the source of truth.
> 
> Either way I'll try to allocate some time and investigate possible diff alternatives since clearly this is the expected behaviour.

Manifests in git repo don't have a one-to-one correlation between manifests that get deployed, thats expected.
