### ISSUE TITLE
Bearer token missing in secrets when adding external cluster ( EKS )

### ISSUE THREAD

**Issue by roy-tonal** [argoproj/argo-cd#4701]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Trying to add external AWS EKS cluster to argocd, connection is added successfully but its not adding bearerToken to secrets. We are not able to deploy any apps due to this i suppose.

**To Reproduce**

Add an external EKS cluster, try to add apps but fails.

**Expected behavior**

Bearer token should be added to secrets created by Argo for external cluster.

**Screenshots**

**Version**

```shell
Argo :- v1.7.4+f8cbd6b
EKS:- 1.17
```

**Logs**

```
comand used to add the cluster.
argocd cluster add <cluster arn>

```

**Comment by jessesuen** [comment]
I'm confused. EKS uses IAM auth, and not bearer tokens, so it's expected that we would not store/use bearer tokens.

**Comment by roy-tonal** [comment]
> I'm confused. EKS uses IAM auth, and not bearer tokens, so it's expected that we would not store/use bearer tokens.

Ohh...I will take a look into this, I thought it uses bearer token just like KOPS cluster. The problem is I'm not able to get any guide for connection between Argo and EKS ( external cluster ). Thanks for the quick reply.

**Comment by roy-tonal** [comment]
So it appears that the secret does adds the "bearerToken" when an external cluster is added. I create an IAM role for argo service accounts and then allowed it in aws_auth config map. I was able to add external cluster to argo and deploy apps too. I cross-checked the secret which gets created on argo server and found that bearerToken for the EKS cluster exists now.

**Comment by jessesuen** [comment]
> The problem is I'm not able to get any guide for connection between Argo and EKS ( external cluster ). Thanks for the quick reply.

```
argocd cluster add CONTEXT --aws-cluster-name AWSCLUSTERNAME
```

optionally you can add:
```
--aws-role-arn string       Optional AWS role arn. If set then AWS IAM Authenticator assume a role to perform cluster operations instead of the default AWS credential provider chain.
```

**Comment by roy-tonal** [comment]
So what I have done is using IRSA ( IAM role for service account ), where I'm creating a role with trust identity for EKS OIDC provider and argocd k8s service accounts. Now when I shoot below command it works.
```
argocd cluster add CONTEXT
```
But if I give ```--aws-cluster-name``` and ```--aws-role-arn``` flags it give me error ```FATA[0003] rpc error: code = Unauthenticated desc = the server has asked for the client to provide credentials```.

And I'm not sure if it's taking the default AWS creds provider chain, because I have only one chain with the name default which is associated to one of my AWS account and i have multiple AWS accounts with different name, my argo sits on different AWS account along with EKS cluster and i was able to add cluster without providing that ```--aws-role-arn```. 

Please let me know if I miss something here or if there is any better way to achieve this.

Thanks.

**Comment by axozoid** [comment]
@roy-tonal I was also getting that error and in my case it was a simple typo - I used a wrong value for `--aws-cluster-name` - I was giving the K8s context name by mistake whereas this has to be the value that you get with `aws eks list-clusters`.

Regarding your creds chain - jump into the `argocd-application-controller-*` pod and try `aws sts get-caller-identity` to see what's being used. For the EKS you should see the nodes' IAM role by default (unless you blocked access to the metadata).

RE: IAM roles.
My setup is a bit different - we've got a few clusters and in order to access them easily we created just one IAM role and during the cluster creation we pass this role to be put into `aws_auth` configmap. So when a cluster is up and running, anyone who can assume that role can access the cluster. 
With ArgoCD you either need expand nodes' policy to allow assuming that role or use IRSA for the `argocd-application-controller` pod.

**Comment by roy-tonal** [comment]
@axozoid  Thanks for the comment. I have already resolved the problem which i was facing by using IRSA account on AWS. That account is then added to aws-auth on the EKS cluster. Everything is working fine.
