### ISSUE TITLE
Revision is not signed is misleading

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4731]
**Describe the bug**

People are often confused that "Revision is not signed" is an error, but it's not. We should conditionally display this only if the project is enabled with signed commits.

**Screenshots**

![image](https://user-images.githubusercontent.com/12677113/97923680-3a9ec580-1d13-11eb-9a6d-213d45d2e76f.png)

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
I agree, this is bad. 

I recently had a chat on Slack who had an even worse experience if the revision is actually signed, but GPG has not been configured. Status reads "Invalid signature..." then (because it could not be verified), and in combination with a sync error of different cause this message is awfully misleading.

**Comment by rajivml** [comment]
yeah this is very misleading, first time when I tried argo, I don't know whether it's a sync error or it's due to GPG, I went on editing all the deployments to disable GPG completely but still the error didn't disappear and then I realized it's something else

**Comment by SwarlsBarkley01** [comment]
@rajivml Any clue to what it ended up being, I'm encountering the same issue.
