### ISSUE TITLE
ArgoCD while rendering UI don't show passwords as clear text

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#4736]
# Summary

ArgoCD UI when it renders the UI it shows the passwords as clear text which is a big no no for many enterprises 

![image](https://user-images.githubusercontent.com/46923567/97950528-26af9e00-1dbd-11eb-8ca2-4d2851f1f9bc.png)

Can we instead have passwords displayed as  ****** 

# Proposal

In the values.yaml file specify that it's an password field via a specific character combo basis which UI should render it as a password i.e. hide actual value

**Comment by jessesuen** [comment]
Theres not much of a point to hide sensitive data. This data would still be exposed in multiple places:
* git
* application spec
* API sever
* debug logs

This would only cause users to have a false sense of security. I'm against this

**Comment by rajivml** [comment]
okay, that makes sense then, that we cannot hide it at multiple other places...

**Comment by rajivml** [comment]
@jessesuen am fine it being exposed as secret at all other places but on UI can we introduce a way to mask the password. Context is we are planning to use Argo as an Application lifecycle management tool (ALM) to deliver software to customers on premise environments and usually during debugging sessions we record the session for training purposes and passwords being in clear text is a big no over there, one has to be conscious to pause the record while these inputs are entered and resume the deployment session

**Comment by matthewhembree** [comment]
I don't speak for the ArgoCD project, but:

ArgoCD is an excellent way to deploy Hashicorp Vault. The would eliminate the need to explicitly specify secrets in configuration. There also are other simpler ways of managing sensitive data and not exposing it in the UI. You could put it in a K8s Secret, which you don't need to put the literal in git. You could deploy the K8s Secret in a different ArgoCD Helm Application where you could specify the secret as a value in the UI. Then have your pod spec ingest that secret into an envar.

There are a also couple of articles out there about [integrating ArgoCD with Helm and SOPS](https://medium.com/faun/handling-kubernetes-secrets-with-argocd-and-sops-650df91de173).

Masking it in the UI is just a way for the ArgoCD project to mitigate a users intentional bad security practice. I'd rather see the effort expended in mainlining [SOPS into ArgoCD](https://github.com/argoproj/argo-cd/issues/3024), instead of a masking feature.

**Comment by rajivml** [comment]
@matthewhembree we are using ArgoCD to deploy our services onto customers onprem baremetal kubernetes clusters. There are few pieces of Infra which our customers own and are deployed outside the K8 cluster like SQL server, Redis Enterprise etc. 

And when the customer is deploying the software via Argo, we need these coordinates to be feed via argo UI and that's where I think it makes sense to hide the passwords, we can't expect them to go to the cluster and create a secret for the same which our helm templates can refer to

**Comment by blakepettersson** [comment]
>we can't expect them to go to the cluster and create a secret for the same which our helm templates can refer to

You can do something similar thorough AWS Secrets Manager, or Vault etc. Will close this issue, since the likelihood that something like this will be worked on will be very low.
