### ISSUE TITLE
Argo CD events show firstTimestamp instead of lastTimestamp

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#4786]
**Describe the bug**

we should show lastTimestamp

```yaml
- apiVersion: v1
  count: 623
  eventTime: null
  firstTimestamp: "2020-10-30T19:38:10Z"
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{argocd-application-controller}
    kind: Pod
    name: argocd-application-controller-8b66dcfb8-n5l9v
    namespace: dev-deploy-argocd-us-west-2-prod-payroll
    resourceVersion: "5333642438"
    uid: f69247cd-7daa-45aa-8159-2ada521061ec
  kind: Event
  lastTimestamp: "2020-11-06T22:13:40Z"
  message: 'Readiness probe failed: Get http://IP:8082/healthz: net/http:
    request canceled (Client.Timeout exceeded while awaiting headers)'
  metadata:
    creationTimestamp: "2020-11-06T17:58:10Z"
    name: argocd-application-controller-8b66dcfb8-n5l9v.1642dc58a7192aee
    namespace: NAMESPACE
    resourceVersion: "87186016"
    selfLink: /api/v1/namespaces/NAMESPACE/events/argocd-application-controller-8b66dcfb8-n5l9v.1642dc58a7192aee
    uid: 8fbfc654-ee1d-4e9d-ac85-41282f8a647b
  reason: Unhealthy
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: kubelet
    host: HOST.compute.internal
  type: Warning

```

**Comment by jessesuen** [comment]
![image](https://user-images.githubusercontent.com/12677113/98421239-bfece780-203d-11eb-8a37-39034cc626c4.png)

**Comment by jannfis** [comment]
IMHO showing both timestamps would be much better than to just show the first or last time, because I guess it's also good to know when the event occurred the last time (i.e. whether it's ongoing or not, I can think of intermittent image pull failures or similar).

So we could either introduce a new column and title one "First occurred" and the second one "Last occurred", or we could just put both timestamps in same column, i.e. "First: <first_ts>\nLast: <last_ts>"

What do you think?

**Comment by jannfis** [comment]
So either like this:

![image](https://user-images.githubusercontent.com/3942683/98649063-6a635400-2337-11eb-9113-dbda4f3d5d46.png)

Or like this:

![image](https://user-images.githubusercontent.com/3942683/98649271-b3b3a380-2337-11eb-99dc-a340ae4156f3.png)
