### ISSUE TITLE
Provide last updated time for application in tree view

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#4903]
# Summary

There's no information about when the application on a given view was changed/created

![image](https://user-images.githubusercontent.com/2119212/100162513-d5f20900-2e81-11eb-8e62-441927c5cac7.png)

# Motivation

Everything else has a time of sorts

# Proposal

How do you think this should be implemented?

Provide something in a bubble like the other bubbles.

**Comment by chetan-rns** [comment]
Hi @jsoref, how about using `metadata.creationTimeStamp` in a bubble for displaying creation time. There's also `status.reconciledAt`, but I'm not sure if it represents the last updated time since it is updated every time the app is synced .`CREATED_AT` field is also missing on the application summary page. Can I raise a PR with this approach?

**Comment by jessesuen** [comment]
What do you mean by last updated? We display the last time the application was synced prominently at the top of the app view.

**Comment by jsoref** [comment]
It's a consistency thing, most objects that are children of this object have a time bubble that explains something about the object. Synced isn't particularly useful. If the repo has a thousand changes which do not change the state of the application, the fact that it was synced those thousand times doesn't tell me about the last time the application was significantly changed.

Compare w/ the children which show a time relative age in a bubble which reflects when they were (re)created.
