### ISSUE TITLE
Add k8s labels to argocd_app_info metric

### ISSUE THREAD

**Issue by snuggie12** [argoproj/argo-cd#4997]
# Summary

I'm curious what the impact would be to add the labels under `metadata.labels` on an argocd `Application` to the metric `argocd_app_info`.

# Motivation

Most of our resources have a label identifying the owner of that resource. We'd like to take that owner label in order to handle routing alerts for a given application.

# Proposal

How do you think this should be implemented?
Not really sure, but was also pondering whether it should be optional and the default should be off in case it blows up the cardinality (not an expert in this area.)

**Comment by jessesuen** [comment]
> I'm curious what the impact would be to add the labels under metadata.labels on an argocd Application to the metric argocd_app_info.

Adding everything under `metadata.labels` as a prometheus label will cause the cardinality of prometheus to explode exponentially. So this cannot be done as a default. That said, there could be a enhancement to configure/pick specific labels to include as a prometheus label for your use case.

**Comment by snuggie12** [comment]
> > I'm curious what the impact would be to add the labels under metadata.labels on an argocd Application to the metric argocd_app_info.
> 
> Adding everything under `metadata.labels` as a prometheus label will cause the cardinality of prometheus to explode exponentially. So this cannot be done as a default. That said, there could be a enhancement to configure/pick specific labels to include as a prometheus label for your use case.

Yeah, what little I know I worried that would be the case.

Selecting labels sounds interesting. I also think we might work around this via other means (some ugly joins with the dest_namespace which has the label and can be retrieved via kube-state-metrics,) but I'm curious if there's a better process.

Are there any suggestions on how Argoproj would route alerts for a given application or project?

**Comment by cpflaume** [comment]
I would appreciate a feature like this too. It would help us to implement a more sophisticated alerting on this metric.

**Comment by jutley** [comment]
Found this ticket from wanting behavior like this. My recommendation would be to make a separate metric `argocd_app_labels` in the same spirit as kube-state-metrics' `kube_pod_labels`.

Regarding cardinality, I would argue that this is not an issue. Typically cardinality concerns have to do with having many possible values for multiple labels, and having metrics express all the possible combinations of these. This concern is not applicable to metrics that represent kube labels, because there is exactly one such metric for each kubernetes resource. There is no fanning out.

I think most orgs that run both Kubernetes and Prometheus are using kube-state-metrics, and there are many info metrics that expose resource labels. Given that one ArgoCD application creates many Kubernetes resources, we are surely going to see fewer of these argocd_app_label metrics than what kube-state-metrics exposes.

**Comment by leoluz** [comment]
I think having `argocd_app_labels` dedicated as an info metric a good idea. I also don't think this would exponentially increase the metric cardinality as the labels are always the same for a single `Application`. With that, we are going to have one dimension per `Application` which seems to be fine.

@jessesuen Do you have any objection in going in this direction?
