### ISSUE TITLE
Add versioning to Argo CD docs

### ISSUE THREAD

**Issue by reginapizza** [argoproj/argo-cd#5031]
# Summary

Add versioning to Argo CD Docs (ie: 1.0, latest, etc.). Would also issue a warning if you're not reading the latest version of the docs. 

# Motivation

Users who are running older Argo CD versions could read the docs associated with their release, versions could be updated and preserved. 

# Proposal

Migrate from [Material](https://squidfunk.github.io/mkdocs-material/) to [readthedocs.org for mkdocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html).

**Comment by reginapizza** [comment]
How do you image versioning working for Argo CD? Will the version of the doc respond to the version of Argo CD at the time (ex: right now would the versioned docs be at 1.7.4)? 

I think I have this pretty much figured out, but want to test it on my own forked repo first and play around with getting the versioning down

**Comment by jannfis** [comment]
That are some awesome news, @reginapizza!

As for your question, I think it will make sense if we have documentation versioned to the release branch, and not the actual release. So, instead of having separate versions for `v1.7.10`, `v1.7.11`, `v1.8.0`, `v1.8.1` etc we should just have `v1.7` and `v1.8`. This way, we could cherry-pick improvement changes for the documentation to the release branches (if applicable for earlier versions) and they will be user visible without waiting for a new release of Argo CD.

**Comment by reginapizza** [comment]
that sounds good to me! 

And for the account on readthedocs.org, I have created my own based on my own forked repository, but I feel that the account shouldn't be under my name. I think all you would need is to log in with github and be a member of the argoproj organization, and then you should be able to import the argocd repository. I can then make a PR that contains the configuration for readthedocs and then it should automatically pick up those changes via a webhook and host it. I also don't mind getting on a call to walk through it if that's easier, but I think you probably would have set it up before when you tried it the first time?

**Comment by jannfis** [comment]
Great! I think the base configuration part for RTD should be submitted to the `argoproj/argocd` repository, before we're able to import the repository into RTD, but I'm not sure. But I guess we can figure that out by trial & error :) I'm a little familiar with RTD because I already host docs for the Argo CD Image Updater with them.

Have you also figured out how to display the RTD version selector pop-up while using Material theme with RTD?

**Comment by reginapizza** [comment]
we could probably do it either way, I think both work but we can certainly do that part first if you want. 

Currently the version is displayed as part of the url (ex. https://argo-cd.readthedocs.io/en/latest/). I don't think that Material theme has any easy way to add in a version selector unfortunately, at least from everything that I've found...

Some solutions I've found for this is to:
1. ) use [mike](https://github.com/jimporter/mike)

- CON: uses JS (potentially bad if javascript isn't available, but not sure if that's a concern here)
- CON: smaller project, doesn't have wide support yet
- old docs link to newer versions 
-  once built, you never have to rebuild docs for a version
- if the built docs are copied somewhere without versioning info, the version selector should go away
-  works on gh-pages

2.) use [mkdocs-material-extensions](https://github.com/sealsystems/mkdocs-material-extensions)

- generates a version selection dropdown next to the title in the header
- no support available

What do you think about these? I can try them out, let me know if one seems better than the other in your opinion

**Comment by jannfis** [comment]
Thank you for sharing evaluation results of the tools you have looked at. I didn't know about these two tools until now.

My initial thought was to leverage the versioning feature of RTD instead of a 3rd party tool. There are a few mkdocs themes for RTD that provide the version selector (including the default theme) as far as I know, so my hope was that we might be able to somehow "port" this functionality to the material theme we use for Argo CD. But this is also the part that I was refraining from doing when I did my initial work to port the docs to RTD - I just lack the mkdocs/Python/HTML/CSS skills, and haven't had time/mood to dig into it :) However, as a hint, RTD provides all this version apparently by an API call to `https://docs.readthedocs.io/_/api/v2/footer_html`, and there must be some JavaScript somewhere that pulls and interprets the information that is returned. The [mkdocs documentation](https://mkdocs.readthedocs.io/en/stable/) for example is hosted on RTD and has the RTD version selector, so maybe this would be a good pointer to start.

But if this is not possible with reasonable effort, or requires hard-to-maintain hacks, I think it's not worth the effort to make it happen just yet. I took a look at the `mike` tool you linked above, and it seems quite useful for maintaining different versions of the docs, which is the main goal and is what brings the most value to our community. And the features you mentioned above would satisfy initial requirements, such as version selector and possibly a warning or link to recent docs if you are viewing outdated docs. And albeit being a small & young project, it seems pretty active and well maintained. I guess we would have to integrate it into our CI processes, tho, right?

So, we do host documentation on GitHub Pages currently and mike would be compatible. I think it would be a quick-win to migrate to it. And we also would have one external dependency (RTD) less to look about and maintain. RTD has some useful features, such as multiple languages, easy disabling old versions of docs, configurable redirects (so if we re-structure docs, we can redirect old bookmarks to new location), etc etc.

**Comment by reginapizza** [comment]
So I've tried out `mike` and it's super easy to add in, except that I'm not sure how to make the version dropdown appear on the main page. For example, with the [arduino cli documentation pages](https://arduino.github.io/arduino-cli/installation/), when you click the arduino icon in the nav bar, it will take you to the `latest` documentation and then in the side bar you can see the version selector. This is pretty much what I'm able to get the argo cd documentation to look like. Also, there is no warning if you're on a later version of the docs, this would really only serve as a way to go back to past versions (but you'd probably only view an older version if you manually selected it I think, therefore you would know it's older I assume?). 

If this is sufficient then I can go ahead and make a PR to add this in now, but I also don't mind trying to dig into how to make a custom version selector with what I have for RTD with material theme based on the other themes :)

**Comment by jannfis** [comment]
> Also, there is no warning if you're on a later version of the docs, this would really only serve as a way to go back to past versions (but you'd probably only view an older version if you manually selected it I think, therefore you would know it's older I assume?).

I think people might come in via Google, and the Google link might not always point to the latest version. At least, it happened to me a couple of times with other projects when I googled for something and there was a link to their docs in the results. I was very grateful for a "you are not reading the latest version of the docs" banner along with a link to latest version.
 
> If this is sufficient then I can go ahead and make a PR to add this in now, but I also don't mind trying to dig into how to make a custom version selector with what I have for RTD with material theme based on the other themes :)

If you have the resources and the mood to dig into RTD version banner, it would be much appreciated! As far as I can tell from my initial research, RTD delivers some HTML from the API call I mentioned above, which must be injected by something (JavaScript) somewhere in the DOM of the documentation page. I think this all revolves about an element with ID `.rst-other-versions` in the DOM. Maybe we could also ask the RTD people how to inject this piece of information into custom themes such as Material.

**Comment by jannfis** [comment]
Actually, I made it (somewhat) happen on the test repo: https://argo-cd-docs.readthedocs.io/en/latest (sourced from https://github.com/jannfis/argo-cd-docs) - you can see it on the bottom right corner. So, it's possible. But needs some more work. I don't know exactly what I did tho. I just copied around some CSS and JavaScript from the [mkdocs rtdocs dropdown theme](https://github.com/cjsheets/mkdocs-rtd-dropdown), and it started working. It might be a good starting point.

**Comment by reginapizza** [comment]
Okay thanks, I'll look into that too! Currently I'm seeing if it can be done with theme extensions/partials to just add a secondary header to act as a banner, but I'm not sure that it's going to work the way I want it to
