### ISSUE TITLE
Prevent unnecessary controller diffing with caching

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#5079]
# Summary

The controller currently calculates a diff between the live state and git state on every reconciliation. This process is CPU intensive, because it involves unmarshalling and marshalling objects, sometimes repeatedly. When there are many applications in the system, or if an application reconciles frequently, it causes the CPU requirements of the controller to increase dramatically.

# Proposal

Similar to how we cache git manifests based on commit sha, the controller should cache diff status based on the resource version of an object.  If a resource version has not been modified from the last time we see the object, then we can trust that there is no change in the diff, and we can re-use the existing diff output.

**Comment by jessesuen** [comment]
I think the cache key should be comprised of the combination of:
1. the live object's `metadata.resourceVersion`
2. the parameters which we send to the repo-server to generate the manifests

If we get a hit, then there is no need to call repo-server or calculate diff because the cache will already have the calculated diff.

**Comment by rbreeze** [comment]
the issue is:
- the current cache is good for app reconciliation avoidance
- it is not good for granular resource diff avoidance

Example:
- there is an app with hundreds of resources
- this app has a single HPA or Lease object which updates and has a new version every 30 seconds

As a result, we do diff on all hundreds of objects every 30 seconds even though the lease/HPA is the only one that changed
