### ISSUE TITLE
Vulnerabilities detected on argocd image

### ISSUE THREAD

**Issue by gabrilabs75** [argoproj/argo-cd#5155]
Hi all,
these vulnerabilities were detected on latest argocd image present on docker hub:

CVE-2019-20367 
Critical
libbsd0 0.9.1-2

CVE-2020-29362 
Critical
libp11-kit0 0.23.15-2

CVE-2020-29363 
Critical
libp11-kit0 0.23.15-2

We are trying to install a custom repository with some interesting features for our consumers.
As a registry we installed Harbor with "Trivy" add-on as vulnerability scanner.
When I pushed the latest image of argocd from docker hub to our registry "Trivy" detected the vulnerabilities above marked as "Critical".

Could you let us know when you fixed the image with the correct libs version or if we could use another image?

Thanks in advance.
Regards,
Gabriele

**Comment by jannfis** [comment]
All these issues you listed are not fixed upstream yet (in Debian 10 aka buster aka stable), unfortunately similar to many other issues. But except for CVE-2020-29363, all the issues are marked as medium severity by vendors, so I wonder where the "critical" stems from.

We do not use the functionalities that are vulnerable in the libp11-kit (from what I could read, the affected components are RPC between some client and server component). Also, the libbsd vulnerability should be negligible in our case.

However, due to the fact that the Debian 10 base does not seem to fix many vulnerabilities reported by several image scanners out there, we started efforts to evaluate migrating to another base image with better update policies: https://github.com/argoproj/argo-cd/issues/5047

**Comment by jsoref** [comment]
Fwiw, ubuntu marked there item as medium: https://ubuntu.com/security/CVE-2020-29363

**Comment by jessesuen** [comment]
I think we can close this as part of https://github.com/argoproj/argo-cd/pull/5185
