### ISSUE TITLE
Support --in-cluster authentication without providing a kubeconfig

### ISSUE THREAD

**Issue by justinbarrick** [argoproj/argo-cd#527]
I would like to add the cluster that argo is running in to argo without having to provide a kubeconfig for it to make bootstrapping easier. The use-case for this is that it allows declaratively deploying a cluster with an argo instance without needing to include the credentials.

Is there a reason that the --in-cluster flag requires a kubeconfig to be provided?

**Comment by jessesuen** [comment]
> I was actually going to use Flux and argo together - use Flux to deploy the base cluster components and Argo and all of the Argo Application and AppProj resources and then use Argo to manage actual application deployments.

This is very interesting approach! I do believe we would be compatible with this mode of operation. 

BTW, on a related note, I'm not sure if you are using or planning on using AWS EKS, but we eventually will be supporting IAM based authentication to manage clusters (https://github.com/argoproj/argo-cd/issues/482). When this is in place, it would be possible to do what you are asking because the local kubeconfig would be irrelevant to the process of adding a cluster.

**Comment by jessesuen** [comment]
After discussion, we agree we can remove the procedural step of adding ArgoCD's own cluster credentials, and have the option of run ArgoCD with clusteradmin privileges, negating the need for the initial bootstrapping step.
