### ISSUE TITLE
k8s client version is blank after removing client binary

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#5325]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

#5101 removed `kubectl` from the image leaving a blank version box.

**To Reproduce**

1. Load https://cd.apps.argoproj.io/applications/argo-cd
2. Click the version (v1.9.0+7165b45)

**Expected behavior**

Report k8s client version

**Screenshots**

![image](https://user-images.githubusercontent.com/2119212/105938209-2114cd80-6025-11eb-87e9-b1b43c98973b.png)

**Version**

```shell
{
    "Version": "v1.9.0+7165b45",
    "BuildDate": "2021-01-26T21:23:37Z",
    "GitCommit": "7165b45aeaa15044cec514e7de3d300d448b2df9",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment]
Yes, it is definitely a bug that we don't show the Kubernetes client version used. But the goal of the mentioned PR was not to remove version information, but to remove the kubectl binary since we've moved to using the client libraries from Kubernetes instead of the binary.

So, the correct fix to this issue would be to properly display the Kubernetes client version instead of removing the row/information altogether, I think.

@iam-veeramalla do you want to take a look, please?
