### ISSUE TITLE
Send Access-Control-Allow-Origin: * response headers for status badges

### ISSUE THREAD

**Issue by markushinz** [argoproj/argo-cd#5335]
# Summary

Currently, status badges cannot be fetched via XHR (fetch requests) from frontend applications without running into CORS issues. If an `Access-Control-Allow-Origin: *` response header was present for status badges, custom logic could be added to frontend applications e.g. only displaying badges if Argo CD is reachable.

# Motivation

If Argo CD runs behind a VPN connection, it might not be reachable from a user’s browser if no connection to the VPN is established. Currently, the only way to embed badges is by directly adding `<img src="<badgeUrl>"`. If Argo CD is not reachable, this would lead to a broken image. If CORS was possible, one could nicely handle this case using JavaScript.

Even though this header could be added by an Ingress, Application Load Balancer, ... it would be nice if it was provided out of the box.

# Proposal

* Send `Access-Control-Allow-Origin: *` response header for status badges
* *Optional*: Make it configurable whether this header should be sent

**Comment by torstenwalter** [comment]
Configuring the header could be done here:
https://github.com/argoproj/argo-cd/blob/5af0c5ad3a52ba8bfa16cce90855efce761395ed/server/badge/badge.go#L157

In case one really want's so make it configurable one could look into this:
https://github.com/argoproj/argo-cd/blob/5af0c5ad3a52ba8bfa16cce90855efce761395ed/server/badge/badge.go#L73-L75


Another thing which would be nice is the option to get the status information via an API endpoint containing the raw data.

One could for example specify an accept header and return JSON instead of the SVG in that case:
https://github.com/argoproj/argo-cd/blob/5af0c5ad3a52ba8bfa16cce90855efce761395ed/server/badge/badge.go#L136-L152

**Comment by markushinz** [comment]
Thanks for your feedback @torstenwalter! In the meanwhile I created a PR for adding the header. But I agree, having a JSON endpoint would be great
