### ISSUE TITLE
Add ability for users to update their passwords through the UI

### ISSUE THREAD

**Issue by jaredclarke** [argoproj/argo-cd#5433]
# Summary

A way to for a user to update their own password through the UI

# Motivation

We have a number of users who will be given access to ArgoCD as a way to track deployments and logs - they should have the ability to manage their own password without needing kubectl or argocd CLI tools (and access into the cluster).

# Proposal

A sliding drawer on the user info page 

#5444 

I did a quick search and couldn't see any previous issues regarding this - has it already been decided that it won't be added? https://github.com/argoproj/argo-cd/issues/3257 this issue mentions the focus is on SSO rather than additional local user features

**Comment by jannfis** [comment]
I think having feature-parity between the CLI and the UI is something we should work towards to achieve. 

What @jessesuen wrote in #3257 still holds true, and I strongly agree with him in this matter. However, I think this feature would be rather an UI enhancement instead of a new feature for local user management, since the API already supports it and the CLI is also already a consumer of that API.

So from my point of view, this would be a welcomed addition.

**Comment by andrei-dascalu** [comment]
IMHO this is an important feature. It shouldn't be required to use the CLI for a security feature like own password management. We have UI-only users that need to asks CLI users to change their password.

One use case we have for UI is to allow others to perform manual deploys on certain environments but they're not necessarily technical users proficient with CLI.

**Comment by crenshaw-dev** [comment]
This was noted in the Trail of Bits security audit as item 32. file:///Users/mcrenshaw/Downloads/argo_security_final_report%20(2).pdf

**Comment by jaredclarke** [comment]
https://github.com/argoproj/argo-cd/pull/5444

This was added and merged a year ago so closing this issue
