### ISSUE TITLE
Ignore Deployment spec.replicas if not present

### ISSUE THREAD

**Issue by dpolicastro** [argoproj/argo-cd#5472]
# Summary
When using HPA for deployment, we need to remove the `spec.replicas` field from the manifest. But even after removing it, ArgoCD uses a default value of 1 for this field.

# Motivation
I know it's possible to use `ignoreDifferences` on Application CRD to ignore this field, but in this case I think it's a missbehaviour, bacause in some cases the lack of replicas field is ignored, and in others (removing it after it was deployed with the field), it tries to use 1 as the value.

![image](https://user-images.githubusercontent.com/29067941/107533477-becbd900-6b9d-11eb-8d94-3639bc4b0080.png)

# Proposal
Some guidance would be appreciated!

**Comment by alexmt** [comment]
Hello @dpolicastro ,

This is expected behavior. Argo CD, as well as `kubectl apply/diff` calculate diff using user-provided manifest, live resource manifest and manifest stored in `kubectl.kubernetes.io/last-applied-configuration` annotation. Most likely in your case `kubectl.kubernetes.io/last-applied-configuration` have Deployment version with replicas, so Argo CD thinks it should be defaulted. Try to remove `kubectl.kubernetes.io/last-applied-configuration` annotation.

**Comment by dpolicastro** [comment]
Thank you @alexmt , that was exactly what was happening. Removing the annotation solved it!
