### ISSUE TITLE
ArgoCD CLI local template

### ISSUE THREAD

**Issue by OmerKahani** [argoproj/argo-cd#5525]
# Summary

Add CLI command for local templating, mainly when using Helm

# Motivation

In order to scan K8s files in PR, they should be templated, but if the application has parameter override, then the user should know how argocd do the templating.

# Proposal

add: `argocd app template APP_NAME LOCAL_PATH`

the output could be to stdout or to a directory

**Comment by jessesuen** [comment]
We actually do a form of this in `argocd app diff --local` so it makes sense to have a command for it. But instead of `argocd app template` it should go under the existing `argocd app manifests` e.g.:

```shell
argocd app manifests APPNAME --local=./path/to/repo
```

**Comment by Cylix** [comment]
Hey all, that sounds like an interesting idea! I'm frequently using `argocd app diff --local` to preview changes before syncing, but there are a few times I feel something like `argocd app manifests --local` could come in handy.

If nobody is working on this, I'll get started to implement this!

**Comment by fabricepipart1a** [comment]
Hi
I am currently struggling with PR validation with Argo CD like mentioned in this issue. My use case is that I have a PR on the repository watched by Argo and I want to automate the analysis of what has changed in the PR.

As @Cylix seems to be doing, I use `argocd app diff --local` to get an idea of what has changed.

The problem I have today is when I want to add a new manifest in my repo. `argocd app diff --local` works fine when the application name is known by Argo CD live instance. If it is not, the command fails.
From there, I see several options that would help me validate the change anyway when I only have manifests in local:
- `argocd app diff --local` does not return an error but instead a diff where live is considered empty
- `argocd app list` proposes a `--local` option allowing me to detect the apps that are new compared to the live app list
- `argocd app manifests` proposes a `--local` option allowing me to inspect the manifests that would be generated by my newly introduced app (its definition only exists in local)

@Cylix Do you confirm the changes you're introducing would help for that use case?
Would `argocd app manifests APPNAME --local` work even if APPNAME is not known by the live instance of Argo ?

**Comment by Cylix** [comment]
Hey @fabricepipart1a, I implemented the change in https://github.com/argoproj/argo-cd/pull/7658 (pending review).

Unfortunately, this change still relies on APPNAME to be known by the live Argo instance, because I followed the implementation of `argocd app diff --local`:
* `argocd app manifests --local` when APPNAME is known will show the manifests for that app using the local data.
* `argocd app manifests --local` when APPNAME is not known will show an error.

`argocd app manifests --local` using an existing APPNAME not corresponding to your local manifests does work though, but it may interpolate some of that app configuration into the manifests.
