### ISSUE TITLE
Upgrade Redis to a version without high vulnerabilities 

### ISSUE THREAD

**Issue by rumstead** [argoproj/argo-cd#5554]
# Summary

redis:5.0.10-alpine has 3 high and 1 medium CVEs in it according to AquaSec. 

CVE-2019-10192, CVE-2019-10193, CVE-2020-14147, and CVE-2020-28928 respectively.

# Motivation

To run vulnerability free-ish software 

# Proposal

I scanned a couple of images:
redis:6.0.10-alpine - CVE-2020-14147 (High), CVE-2020-28928 (Medium)
redis:6.2-rc3-alpine3.13 - CVE-2020-28928 (Medium)

redis:6.2-rc3-alpine3.13 at least has no highs.

**Comment by jannfis** [comment]
Thanks @rumstead, we already have this on the roadmap to v1.9: https://github.com/argoproj/argo-cd/issues/4768

However, there have been discussions in the past about exact the same issues that your scanner reports. We believe they are false positives:

* https://github.com/argoproj/argo-cd/issues/4824
* https://github.com/argoproj/argo-cd/issues/4749

All of our research provided that the issues have been fixed in v5.0.10 already. If you have more actual information, can you please provide them to us?

**Comment by rumstead** [comment]
I will check and get back.

**Comment by rumstead** [comment]
@jannfis I agree that CVE-2019-10192 and CVE-2019-10193 looked to be fixed and this is an AquaSec false positive. CVE-2020-14147 does not look to be fixed though.

**Comment by jannfis** [comment]
Thanks for the additional research on your side, @rumstead!

> https://nvd.nist.gov/vuln/detail/CVE-2020-14147 says Redis 6.0.3 and up have the fix.

The details on the CVE read

> NOTE: this issue exists because of a CVE-2015-8080 regression.

This was supposed to be fixed in Redis 5.0.8 already, and is also mentioned in the Redis Changelog (https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES):

> Seunghoon Woo in commit 16b2d07f:
> [FIX] revisit CVE-2015-8080 vulnerability

So I believe the fix version information in the CVE is outdated.

**Comment by rumstead** [comment]
I will report back 😄

**Comment by rumstead** [comment]
Confirmed this is another false positive. Thank you for bearing with me.
