### ISSUE TITLE
Application status icons are not aligned vertically.

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#5645]
**Describe the bug**

Application status icons are not aligned vertically.

**To Reproduce**

See attached screenshot:

<img width="1069" alt="Screen Shot 2021-03-01 at 10 15 26 AM" src="https://user-images.githubusercontent.com/426437/109540490-5de64100-7a77-11eb-8d60-9c51ab4686fa.png">

**Expected behavior**

All three icons should be at the top of status panel

**Version**

https://github.com/argoproj/argo-cd/commit/c6d37289c0ce2c5e94c33d917ad3b94ae6b4b706

**Comment by alexmt** [comment]
@rbreeze , @reginapizza let me know if you have time, please

**Comment by rbreeze** [comment]
I can do this

**Comment by reginapizza** [comment]
Didn't see this until now but I think part of this is solved in my PR #5700. App Health is still off though

**Comment by alexmt** [comment]
Thank you @reginapizza ! I think https://github.com/argoproj/argo-cd/pull/5700 address most of this issue. We just need to align Health status label vertically as well.

**Comment by reginapizza** [comment]
Submitted a PR for a quick fix for this, it doesn't cover the author/comment line alignment because that would take a little longer to fix, but this would just be the bare minimum. I could always add that to it later on, just didn't want 2.0 to be waiting on this. @rbreeze feel free to submit something else if you were working on it!

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/5746
