### ISSUE TITLE
Mobile Friendly UI

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-cd#5705]
# Summary

Right now, the UI doesn't display very well on mobile devices since it was designed for desktop usage.  Curious to see if there's enough interest in a Mobile friendly UI to warrant some design work/effort there, so opening this to gather interest since I didn't see another existing issue.

# Proposal

No idea yet, just interested in seeing if there's interest!

**Comment by jsoref** [comment]
Some views are ok, but the root applications view is really bad. The filters area should be next to a minimum box for the applications view, so that on narrow portrait screens, one gets a little horizontal scrolling, or a zoom effect.

![Screenshot_20210919-210353](https://user-images.githubusercontent.com/2119212/133949096-bd046d64-97bf-4e47-964d-f00b485d60e8.png)
![Screenshot_20210919-210406](https://user-images.githubusercontent.com/2119212/133949098-004995e6-5c95-4cd4-88e2-de30ac3af6e5.png)
```json
{
    "Version": "v2.2.0+f613fab",
    "BuildDate": "2021-09-18T06:24:27Z",
    "GitCommit": "f613fab6f33cf03dd2a708085e1e45a041a04bcd",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Comment by alexef** [comment]
Please see: https://github.com/argoproj/argo-cd/pull/11508
