### ISSUE TITLE
Separate TLS cert from admin password in argocd-secret

### ISSUE THREAD

**Issue by cyrilcros** [argoproj/argo-cd#5890]
# Change
Split `argocd-secret` into opaque secret `argocd-secret` (admin password etc...) and TLS secret `argocd-cert`.

# Motivation
This allows an easier time configuring the certificates for argocd, for example with cert-manager. You can uncouple the TLS certificate rotation from argocd password.
You can also have an easier time with the various ingress setups in the documentation this way, for example with https://argoproj.github.io/argo-cd/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts you end up with only one valid SAN.

**Comment by jannfis** [comment]
I actually do agree with this proposal, and had something similar in mind for some time as well (see https://github.com/argoproj/argo-cd/pull/5764#discussion_r594922440 for context).

**Comment by jannfis** [comment]
I think the way to handle this in a non-breaking way will be:

* If an external secret, say `argocd-server-tls`, exists in Argo CD's namespace, `argocd-server` will use the certificate stored in this secret for provisioning TLS on its endpoint and ignore `tls.crt` and `tls.key` keys in `argocd-secret` completely. Also, if such a secret exist, `argocd-server` will not auto-generate a certificate.
* If such a secret does not exist, the TLS information will be taken from `tls.crt` and `tls.key` in the `argocd-secret` secret like it's being done currently.
* Going forward, we can think about proper migration from storing TLS information in `argocd-secret` to `argocd-server-tls`. Since this will be breaking for almost everyone, next major version bump would be the correct scope (i.e. v3.0)

**Comment by jannfis** [comment]
Also, if Argo CD is managing itself in a GitOps way, `argocd-secret` will most likely be created by being derived from a resource such as `SealedSecret`. This interferes with an external entity managing TLS on the cluster, such as `cert-manager`.
