### ISSUE TITLE
Vulnerabilities ArgoCD v2.0.0-rc2

### ISSUE THREAD

**Issue by rumstead** [argoproj/argo-cd#5921]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

My company uses AquaSec as its container scanning tool and it alerted me to some issues found in the ArgoCD image. I know there were two closed issues for the v1.8.* version that addressed vulnerabilities. 

1. https://github.com/argoproj/argo-cd/issues/5047
1. https://github.com/argoproj/argo-cd/issues/5155

```
❯ snyk container test argoproj/argocd:v2.0.0-rc2
...
Project name:      docker-image|argoproj/argocd
Docker image:      argoproj/argocd:v2.0.0-rc2
Platform:          linux/amd64
Licenses:          enabled

Tested 241 dependencies for known issues, found 29 issues.

❯ trivy image argoproj/argocd:v2.0.0-rc2                                                                                                                                                                      
2021-03-30T13:42:07.643-0400	WARN	This OS version is not on the EOL list: ubuntu 20.10
2021-03-30T13:42:07.643-0400	INFO	Detecting Ubuntu vulnerabilities...
2021-03-30T13:42:07.648-0400	INFO	Trivy skips scanning programming language libraries because no supported file was detected
2021-03-30T13:42:07.648-0400	WARN	This OS version is no longer supported by the distribution: ubuntu 20.10
2021-03-30T13:42:07.648-0400	WARN	The vulnerability detection may be insufficient because security updates are not provided

argoproj/argocd:v2.0.0-rc2 (ubuntu 20.10)
=========================================
Total: 117 (UNKNOWN: 0, LOW: 90, MEDIUM: 27, HIGH: 0, CRITICAL: 0)

❯ aquasec 
CVE-2020-14343 - Critical 
CVE-2019-9923 - High
CVE-2019-18276 - High
1 Critical, 2 High, 5 Medium, 9 Low, 3 Negligible
```

The dispersion between the 3 scanners is very interesting.

CVE-2020-14343 is fixed by updating PyYAML 5.3.1 to 5.4
CVE-2019-9923 is fixed by updating tar 1.30 to 1.34
CVE-2019-18276 has no fixed version (bash 5.0)

**Version**

```shell
argocd:v2.0.0-rc2
```

**Comment by jannfis** [comment]
Regarding CVE-2020-14343, is indeed something we should fix, although the impact is deemed very low (YAML from untrusted sources, Python is a dependency of `awscli` whose only purpose is to authenticate to aws for getting cluster credentials in Argo CD). And whether we are

CVE-2019-9923 is fixed by a backport in Ubuntu 20.10 (please see https://ubuntu.com/security/CVE-2019-9923, the fix version is `1.30+dfsg-7ubuntu0.20.10.1`). From the container:

```shell
argocd@2ca0b3a1018c:~$ dpkg -l tar    
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                    Architecture Description
+++-==============-==========================-============-========================================
ii  tar            1.30+dfsg-7ubuntu0.20.10.1 amd64        GNU version of the tar archiving utility
```

For CVE-2019-18276, according to https://ubuntu.com/security/CVE-2019-18276 this is not yet fixed upstream and also considered as of low impact, because it only affects scripts or bash running with the suid bit set. We don't make use of such things in the image, and possibly wouldn't even be allowed due to security constraints on many clusters.

That all being said, as much I appreciate all these security scanners in place everywhere now, they tend to produce a lot of false positives, and always require dedicated research before taking their alerts for granted. We also scan our release images regularly for security issues using Snyk, and are well aware of critical issues that affect Argo CD.
