### ISSUE TITLE
[Argocd 2.0 rc1] CLI `argocd app logs` failed with internal error 

### ISSUE THREAD

**Issue by mayzhang2000** [argoproj/argo-cd#5925]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd app logs <appName>l --kind Pod --name <podName>` consistently failed with
```
FATA[0002] stream read failed: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: required field "content" not set
```
Or
```
grpc: failed to unmarshal the received message proto: LogEntry: wiretype end group for non-group
```

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment]
Apparently, it is not related to `argocd app logs` . Error happens with grpc-web + ALB. Not sure where the bug is. It might be either https://github.com/argoproj/argo-cd/blob/master/pkg/apiclient/grpcproxy.go#L52 in or in https://github.com/improbable-eng/grpc-web . 


Attempted to upgrade https://github.com/improbable-eng/grpc-web  but it requires us to upgrade grpc-go (https://github.com/improbable-eng/grpc-web/issues/638 )
