### ISSUE TITLE
ArgoCD deleted all the namespaces/apps which it manages

### ISSUE THREAD

**Issue by sheshankgujjari** [argoproj/argo-cd#6046]
ArgoCD Version: v1.8.1+c2547dc & v1.8.7
Pattern: app of apps deployment
EKS Clusters: 1.18 & 1.17

Original State:
ArgoCD namespace created
Deployed all the apps through gitops using app of apps pattern
Everything is up and running

Issue:
  1. ArgoCD application UI become unresponsive for some time, we have tried to delete all PODs and other components of argocd did not work. At this moment we have decided to wipe/clean everything from argocd including namespace
  2. We have deployed v1.8.1+c2547dc of hainstall.yaml in our argocd
  3. Kubectl apply -f <hainstal.yamll>
  4. All the argocd k8 objects came back up and running and UI is also accessible
  5. Argocd now started deleting all the apps under it's management

We have tried the same with v1.8.7 argocd version and we saw the same behavior.

Why would applying the argocd from scratch deletes what is existing and re initiates the apps?

Please let me know if you want me to provide any more information around it. 

If I remember correctly this was not the behavior in v1.6.0-rc1. Any major changes happened for this behavior?

**Comment by andrei-dascalu** [comment]
This sounds pretty serious - I wonder if it's the case with v2.x

**Comment by ayasuda-ge** [comment]
> This sounds pretty serious - I wonder if it's the case with v2.x

Versioning or not, argocd shouldn't remove the data storage during uninstalling process.

I believe the existing flag for any un-installation of argocd instance should always by default set to **false**, or rather, remove the flag/option completely from the instance. @andrei-dascalu

**Comment by palokam** [comment]
yes, It is a serious issue, it should reconcile the status than deleting the K8s objects, I do not think that is the intentional - may be a bug

**Comment by andrei-dascalu** [comment]
@ayasuda-ge of course, I was wondering mostly for selfish reasons. Aka: we're just about ready to extend the range of environments managed with Argo, recently went to v2 - this is the kind of thing to make one reconsider.

**Comment by alexmt** [comment]
@sheshankgujjari did you have Application CRs in Argo CD namespace with `resources-finalizer.argocd.argoproj.io` finalizer? If the application has that finalizer then Argo CD supposed to delete managed resources before deleting the application.

**Comment by palokam** [comment]
@alexmt - I want to understand your question correctly ... 
I understand, when we deleted -n argocd namespace, argocd Application CRs are also lost because of argocd  NS was deleted
But when we apply argocd again - reinstall 
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/<version>/manifests/ha/install.yaml

The expectation was it should not touch the existing app of applications, correct?
---- existing Applicarion CRs below ---
 k get applications -n argocd -o wide
NAME                 SYNC STATUS   HEALTH STATUS   REVISION
argo-cd              Synced        Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
aws-efs-csi-driver   Synced        Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
cluster-autoscaler   Synced        Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
cluster-config       Synced        Healthy         c26551102eed07727976e100496b99c19efde9eb
dc-wordpress-ci      Synced        Healthy         792bad208b42090d5c250fde1c5da007eae78865
dive-eng-common      Synced        Healthy         40c3e69015e44630a59336b29d851a134736ec56
dive-eng-dev         OutOfSync     Healthy         40c3e69015e44630a59336b29d851a134736ec56
dive-eng-dev-v2      Synced        Healthy         40c3e69015e44630a59336b29d851a134736ec56
dive-eng-qa          Synced        Healthy         40c3e69015e44630a59336b29d851a134736ec56
dive-engineering     Synced        Healthy         40c3e69015e44630a59336b29d851a134736ec56 
eng-server           Synced        Healthy         025f20246e675667a2b276948c16dd805b3eceac
environments         OutOfSync     Healthy         c26551102eed07727976e100496b99c19efde9eb
fluent-bit           OutOfSync     Missing         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
grafana              Synced        Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
graylog              OutOfSync     Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
ingress-nginx        Synced        Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
prometheus           OutOfSync     Healthy         e2237418aa3a8a9fa7fe8e70374f136f0ef7cde8
.......

**Comment by jannfis** [comment]
@palokam I think what @alexmt was asking is, whether you have set the resource deletion finalizer in your application CRs, e.g. whether it has something like the following in the `.metadata` section:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
```

**Comment by alexmt** [comment]
thank you for clarification @jannfis

**Comment by sheshankgujjari** [comment]
@alexmt  and @jannfis 

Yes we do have resource finalizers for all our apps we manage through argocd
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environments
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
 ```

**Comment by alexmt** [comment]
This might be the reason. If you delete `argocd` namespace then Kubernetes tries to delete Application CRs and argocd pods at the same time. 

It is hard to tell what happened exactly without seeing logs. Here is one possibility: 

* `kubectl delete argocd` - argocd pods are gone, but Application CRs are still there because there is no controller that can remove finalizers. So namespace is not really deleted because kubernetes is waiting when something process deletion of Application CRs.
* `kubectl apply -f <hainstal.yamll>` - Argo CD pods are recreated. 
* Argo CD controller wakes up and notices bunch of applications in "deleting state" - goes ahead and deletes managed resources. This is the right thing to do because applications have finalizers.

**Comment by alexmt** [comment]
If this is the case when Argo CD worked as expected but I think we have a documentation issue. It is not safe to delete `argocd` namespace if you manually add `resources-finalizer.argocd.argoproj.io` finalizer. Even during deletion controller might have few seconds to delete managed resources.

**Comment by palokam** [comment]
@sheshankgujjari   - it debunks the theory of previous versions of ArgoCD that is NOT working this way - it is seems the ArgoCD expected to delete app of Apps because of the reinstalled ArgoCD controller showed up after reinstall, then delete app of Apps

_Best way to reinstall ArgoCD, if you have to is as follows
1) Identify all ArgoCD managed Applications, remove the Finalizers - that will take out the ArgoCD controller out of picture for these running apps
2) Remove the ArgoCD namespace 
3) Install ArgoCD - kubectl apply -f <hainstal.yamll>
4) kubectl -f <Apply app of  Apps YAML>_

At this point ArgoCD will resume back safely

**Comment by ayasuda-ge** [comment]
> If this is the case when Argo CD worked as expected but I think we have a documentation issue. It is not safe to delete `argocd` namespace if you manually add `resources-finalizer.argocd.argoproj.io` finalizer. Even during deletion controller might have few seconds to delete managed resources.

Second IMO-
https://github.com/argoproj/argo-cd/issues/5305#issuecomment-767183629

I vote up that argocd should inherit readonly RBAC to the resources instead of cluster adm to API Server. E.g. Deletion #securityEnhancement

@alexmt

**Comment by ayasuda-ge** [comment]
> > If this is the case when Argo CD worked as expected but I think we have a documentation issue. It is not safe to delete `argocd` namespace if you manually add `resources-finalizer.argocd.argoproj.io` finalizer. Even during deletion controller might have few seconds to delete managed resources.
> 
> Second IMO-
> [#5305 (comment)](https://github.com/argoproj/argo-cd/issues/5305#issuecomment-767183629)
> 
> I vote up that argocd should inherit readonly RBAC to the resources instead of cluster adm to API Server. E.g. Deletion #securityEnhancement
> 
> @alexmt



> > If this is the case when Argo CD worked as expected but I think we have a documentation issue. It is not safe to delete `argocd` namespace if you manually add `resources-finalizer.argocd.argoproj.io` finalizer. Even during deletion controller might have few seconds to delete managed resources.
> 
> Second IMO-
> [#5305 (comment)](https://github.com/argoproj/argo-cd/issues/5305#issuecomment-767183629)
> 
> I vote up that argocd should inherit readonly RBAC to the resources instead of cluster adm to API Server. E.g. Deletion #securityEnhancement
> 
> @alexmt

@jannfis

**Comment by sheshankgujjari** [comment]
@palokam I see that resource finalizers was added last year and our testing was completed before the flag enablement with previous versions of argocd.

We will go through another round of testing removing resource finalizers flag and post the results

**Comment by sheshankgujjari** [comment]
@alexmt and @jannfis 

Steps performed:

1. Removed the `resources-finalizer.argocd.argoproj.io` in our apps
2. Deleted all the K8 objects from argocd namespace and deleted argocd namespace
3. Re-initialized argocd on the same EKS cluster
4. Good news is it did not delete any applications owned by argocd

After re-initializing argocd on the same EKS cluster, below are my initial unexpected behaviors on the existing apps please check and add your comments

1. ArgoCD doesn't inherit the old apps, all apps are showing as out of synch and I have explitily re-synced one by one
2. Throwing an error on RepeatedResourceWarning on prometheus app

``Resource /Service/prometheus/prometheus-kube-state-metrics appeared 2 times among application resources.
    Resource /ServiceAccount/prometheus/prometheus-kube-state-metrics appeared 2 times among application resources. 
    Resource apps/Deployment/prometheus/prometheus-kube-state-metrics appeared 2 times among application resources. 
    Resource rbac.authorization.k8s.io/ClusterRole//prometheus-kube-state-metrics appeared 2 times among application resources.
    Resource rbac.authorization.k8s.io/ClusterRoleBinding//prometheus-kube-state-metrics appeared 2 times among application resources.``


<img width="1407" alt="Screen Shot 2021-04-19 at 9 45 21 PM" src="https://user-images.githubusercontent.com/21126674/115327894-becbf480-a15d-11eb-9caf-90a5812dd700.png">

2. When I synch daemonset apps, it delete the existing pods and recreate them on every worker node
3. After synching our internal product which is deployed as statefulset, no issues with the synch operation. However the ``app diff, sync status, history and rollback `` buttons are in disabled state
<img width="1091" alt="Screen Shot 2021-04-19 at 10 06 10 PM" src="https://user-images.githubusercontent.com/21126674/115327969-dc00c300-a15d-11eb-89c0-9e516217c58d.png">
4. For one of the applications when I browse the url with https://argocd-dns-entry/applications/application-name, argocd UI shows blank page. When I navigate through app of apps, I am able to browse it without any issues
<img width="1036" alt="Screen Shot 2021-04-19 at 9 51 36 PM" src="https://user-images.githubusercontent.com/21126674/115328228-4154b400-a15e-11eb-9970-c8aff9ee017a.png">



As I find more, I will add it to the thread

**Comment by palokam** [comment]
it sounded like without the finalizer, ArgoCD controller seems behaving differently than expected

**Comment by ErikLundJensen** [comment]
@knweiss always remember to install the CRDs before installing the chart as you don't what all your CR resources to be deleted when the CRD are deleted. This is not just ArgoCD but any CRD.

**Comment by nikhleshgoenka** [comment]
**When I'm trying to sync all apps it deletes the namespace for me too!! Though in ArgoCD logs there is no symptom of delete namespace being called by any application, is it due to Replace being used in all the apps?

{
    "Version": "v2.2.9+38755a4",
    "BuildDate": "2022-05-18T12:02:28Z",
    "GitCommit": "38755a4c1e5232aa2e6f80c062593c9f07da0757",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.11",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}**
