### ISSUE TITLE
Vulnerability in version 2.0.0

### ISSUE THREAD

**Issue by infa-kparida** [argoproj/argo-cd#6258]
**Describe the bug**
Our security scanning tool is reporting few vulnerability during scanning of argocd 2.0.0

argocd-application-controller | CVE-2016-2781 | 8.6
argocd-application-controller | CVE-2021-20231 | 9.8
argocd-application-controller | CVE-2021-20232 | 9.8
argocd-application-controller | CVE-2018-5709 | 7.5
argocd-application-controller | CVE-2021-20305 | 8.1
argocd-application-controller | CVE-2020-9794 | 8.1
argocd-application-controller | CVE-2020-9991 | 7.5
argocd-application-controller | CVE-2018-20839 | 9.8
argocd-application-controller | CVE-2018-6952 | 7.5
argocd-application-controller | CVE-2019-20838 | 7.5
argocd-server | CVE-2016-2781 | 8.6
argocd-server | CVE-2021-20231 | 9.8
argocd-server | CVE-2021-20232 | 9.8
argocd-server | CVE-2018-1000021 | 8.8
argocd-server | CVE-2018-5709 | 7.5
argocd-server | CVE-2021-20305 | 8.1
argocd-server | CVE-2020-9794 | 8.1
argocd-server | CVE-2020-9991 | 7.5
argocd-server | CVE-2018-20839 | 9.8
argocd-server | CVE-2018-6952 | 7.5
argocd-server | CVE-2019-20838 | 7.5
argocd-repo-server | CVE-2016-2781 | 8.6
argocd-repo-server | CVE-2021-20231 | 9.8
argocd-repo-server | CVE-2021-20232 | 9.8
argocd-repo-server | CVE-2018-5709 | 7.5
argocd-repo-server | CVE-2021-20305 | 8.1
argocd-repo-server | CVE-2020-9794 | 8.1
argocd-repo-server | CVE-2020-9991 | 7.5
argocd-repo-server | CVE-2018-20839 | 9.8
argocd-repo-server | CVE-2018-6952 | 7.5
argocd-repo-server | CVE-2019-20838 | 7.5
argocd-dex-server | CVE-2021-23840 | 7.5

I have listed them component wise.Can we implement fix for the high critical vulnerabilities ?

**Comment by jannfis** [comment]
Thanks for your concerns, @infa-kparida. However, from my experience, different security scanners all report different things on the very same input.

Before I will be going through the list, can you please elaborate on the reported CVEs and how you think they affect Argo CD? As an example, I took CVE-2018-20839 (https://nvd.nist.gov/vuln/detail/CVE-2018-20839) from your list and this is about a flaw in systemd, which isn't used in a container environment (and also, not part of our image distribution).

What scanner do you use? I'm asking because we do implement scanning on our images through quay.io and Snyk, and neither of them reports any high severity issues.

**Comment by mkilchhofer** [comment]
Container Image scanning on artifacthub.io also gives a good overview with some details about each issue:
https://artifacthub.io/packages/helm/argo/argo-cd?modal=security-report
