### ISSUE TITLE
reconciliation timeout is too aggressive.

### ISSUE THREAD

**Issue by tcarland** [argoproj/argo-cd#6357]
# Summary

Configuring argocd `timeout.reconciliation` config-map option should be more clearly stated in the docs.

# Motivation

 At over 20 apps controlled by argo resulted in 184k queries in 14 days to the enterprise github instance causing a bit of an uproar as the repository instantly became the no.1 heavy-use repo by an order of magnitude. 

# Proposal

For starters. configuring the timeout should be better documented and easier to find.  I had to dig deep to locate the setting in /docs/operator-manual/argocd-cm.yaml#L263-L266.  I suggest adding more clear notes regarding this to both the "Getting Started" page as well as in the OperatorManual.

Another alternate feature, might be to have a backoff option to the timeout such that when all apps are synced, those apps are not then polled as often.  Clearly using github webhooks would be the 
better solution, however, of note, this is per repository.

**Comment by jannfis** [comment]
I totally agree with the fact that we should state this more clearly, and also provide pointers to the webhook mechanisms as a remediation.

To the aggressiveness, I'm assuming you use some kind of `latest` build (since this change was introduced after 2.0 release), there was a bug in the `timeout.reconciliation` setting that got fixed by https://github.com/argoproj/argo-cd/pull/6299 meanwhile.

Also, some improvements regarding Git (and Helm) requests have been made in https://github.com/argoproj/argo-cd/pull/6102

**Comment by tcarland** [comment]
> I totally agree with the fact that we should state this more clearly, and also provide pointers to the webhook mechanisms as a remediation.
> 
> To the aggressiveness, I'm assuming you use some kind of `latest` build (since this change was introduced after 2.0 release), there was a bug in the `timeout.reconciliation` setting that got fixed by #6299 meanwhile.
> 
> Also, some improvements regarding Git (and Helm) requests have been made in #6102

'latest' is evil and I avoid it at all costs!  I was using this kustomization.yaml for deploying 

`apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=33eaf11e3abd8c761c726
e815cbb4b6af7dcb030 # tag=v2.0.1

patchesStrategicMerge:
- configmap-patch.yaml
- add-custom-kustomize.yaml

images:
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.27.0
  # digest: sha256:ff94efdd1ec68f43e01b39a2d11a73961b1cf73860515893118af731551f1939
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.0.1
  # digest: sha256:8d1d58ef963f615da97e0b2c54dbe243801d5e7198b98393ab36b7a5768f72a4
- name: haproxy
  newName: haproxy
  newTag: 2.0.20-alpine
  # digest: sha256:61ddebc917f98e16a8c479f0fe90d01ed54c5f53ab7937449906f0a89b69e61e
- name: redis
  newName: redis
  newTag: 6.2.1-alpine
  # digest: sha256:85f11bc7bc6f247b8bc475ab48110076af9a251fcffd61c6b5d7b79a40c4604a`

**Comment by jannfis** [comment]
I was just wondering because you mentioned the `timeout.reconciliation` setting in `argocd-cm`, which was introduced with https://github.com/argoproj/argo-cd/commit/9b32e0110439e5aec1b0171d5f7a3dbd51224535 and is not yet part of any release.

**Comment by tcarland** [comment]
Well, color me confused. Correct me if I'm wrong here, but if I follow that kustomization above, and/or checking out tag v2.0.1, I clearly see a `argocd-cm` ConfigMap object...
https://github.com/argoproj/argo-cd/blob/33eaf11e3abd8c761c726e815cbb4b6af7dcb030/manifests/ha/namespace-install.yaml#L2347

**Comment by jannfis** [comment]
Sorry if my previous statement was ambiguous. To clarify, the `argocd-cm` ConfigMap exists since ages, but the `timeout.reconciliation` setting was introduced just recently and is not yet in any release (comes with v2.1).

The current proper way to control the reconciliation interval is to set `--app-resync` flag on the `argocd-application-controller` workload. The `timeout.reconciliation` setting will supersede that from v2.1 onwards.

I also think part of your confusion stems from the fact that you browsed docs from `master` branch in Git. This may contain information for not yet released things. If you browse the ConfigMap example from the 2.0.1 release (https://github.com/argoproj/argo-cd/blob/33eaf11e3abd8c761c726e815cbb4b6af7dcb030/docs/operator-manual/argocd-cm.yaml), you'll notice the setting is not there.

But you are correct that this setting is badly documented (if at all).

**Comment by tcarland** [comment]
Ahh, now I understand. Thank you for the clarification. That is exactly what I did wrong between master and v2.0.1. cheers

**Comment by tcarland** [comment]
I understand that this fix is coming in 2.1, however my original report specifically calls out documentation to adjusting the sync timer.  For current version as stated in a previous comment from @jannfis mentions use of an `--app-resync` flag however this too is not documented anywhere from what I can see?  I still have an issue of about 9 clones per minute with current stable, which is simply unacceptable to our enterprise github server.
