### ISSUE TITLE
Redis issues with IPV6 disabled cluster

### ISSUE THREAD

**Issue by MikeK184** [argoproj/argo-cd#6471]
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

### Describe the bug

After upgrading to v2.0.3 the `deployment.apps/argocd-redis` was failing to successfully create the redis pod because it wasn't able to bind the socket. A similar issue for the HA version was raised in this https://github.com/argoproj/argo-cd/issues/5957

### To Reproduce

Deploy non-ha ArgoCD v2.0.3 to a Kubernetes cluster (TKGI) with IPv6 disabled.

### Expected behavior

Redis pod to successfully bind the socket.

### Logs
```shell
# Could not create server TCP listening socket ::*:6379: unable to bind socket, errno: 97
```

### Workaround 
I had to manually add `--bind 0.0.0.0` to the args of the `argocd-redis deployment`
https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L3099-L3105

**Comment by jkleinlercher** [comment]
Found lots of issues regarding redis and binding issues with IPv6 disabled. Last one was https://github.com/docker-library/redis/issues/273

maybe redis solves this issue with 6.2.2 as also mentioned in https://github.com/argoproj/argo-helm/pull/700


When will argocd switch to redis 6.2.2 officially?

**Comment by jannfis** [comment]
Thanks for the heads up regarding the bug being fixed in a more recent version. It seems to be indeed true, from the [Changelog](https://raw.githubusercontent.com/redis/redis/6.2/00-RELEASENOTES):

> * Fix not starting on alpine/libmusl without IPv6 (#8655)

Looking further at the Changelog, Redis reached 6.2.4 meanwhile with some important changes. So probably worthwhile to include an update to 6.2.4 in the next patch release of Argo CD v2.0 branch.
