### ISSUE TITLE
Why is it now very hard to get running locally?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-cd#6545]
I started trying to get it running at 10am today. It is now 5pm and it is still not working.

* `node-sass` is broken. Should use `sass`.
* Very long confusing instructions.
* Slow, often running `go mod vendor`.
* `make start-local` is not documented. Was `make start`. Is broken I think.
* Does not install correct configuration.
* `goreman` never cleanly exists. Leaves old containers running.

Another error:

`gpg --no-permission-warning --logger-fd 1 --batch --generate-key /var/folders/s0/41b1vy2d6nn42rmgltmbrpdw0000gp/T/gpg-key-recipe235648706` failed exit status 2 
exit status 20

ARGOCD_GPG_ENABLED=false removes that last error.

**Comment by joebowbeer** [comment]
Release v2.0.4?

**Comment by jannfis** [comment]
I agree that it's quite a mess and needs some context to set-up all swiftly. Just a nitpick: it always has been.

> Very long confusing instructions.

Would appreciate some more details on what's confusing, so that we can fix it.

> Slow, often running go mod vendor

`go mod vendor` is usually not slow when the modules have already been downloaded:

```shell
$ ls -la vendor
ls: cannot access 'vendor': No such file or directory
$ time go mod vendor

real    0m2.192s
user    0m1.942s
sys     0m1.156s
```

> Does not install correct configuration.

Could you please elaborate a little more on that? What configuration do you mean?

> goreman never cleanly exists. Leaves old containers running.

Yup, agreed. That's one very annoying thing. Just submitted #6576 to fix that.

**Comment by alexec** [comment]
FWW I just want to run a single command and have it up and running with no fuss. I think that command `make start-local` should do that.

**Comment by jannfis** [comment]
`make start` does exactly that, it will run your local Argo CD code within a Docker container that has everything inside required to run Argo CD correctly. Hasn't it worked for you?
