### ISSUE TITLE
Redis resources have misleading Helm labels in HA mode

### ISSUE THREAD

**Issue by mgarstecki** [argoproj/argo-cd#6570]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
~* I've pasted the output of `argocd version`.~ I believe this is irrelevant

**Describe the bug**

Redis manifests for HA deployment include helm-release-related labels even though they will not be installed by Helm. They are also incosistent with the labelling of the rest of the manifest.

**To Reproduce**

Here are the resources in the manifests where I see the issue:
- https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml#L2653-L2657
- https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml#L2813-L2817
- https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml#L3372-L3375

Also present in the HA manifest for release v2.0.4, and in the HA namespace-install.

**Expected behavior**

Those resources should have coherent labelling with the rest of the manifest: `app.kubernetes.io/part-of: argocd`, `app.kubernetes.io/component: redis`, `app.kubernetes.io/name: ...`.

Even though those labels are more linked to Helm v2 and don't look likely to me to cause issues, they will still cause confusion, and the Redis resources won't be associated with ArgoCD when selecting resources.

**Version**

Visible in the HA manifests at least for v2.0.4 and `master`, both namespaced and cluster-wide.

**Comment by jannfis** [comment]
I agree. Probably this is due to the fact that we take the [redis-ha Helm chart](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha) and template it. We're then running [Kustomize](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/base/redis-ha/kustomization.yaml) over the template to modify some of the resources before including them into `install.yaml`, and probably missed the RBAC resources.
