### ISSUE TITLE
Support using external OIDC providers

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#671]
Dex doesn't propagate group claims from upstream OIDC providers : https://github.com/dexidp/dex/issues/1065. Due to this issue ArgoCD RBAC cannot be used in  conjunction with OIDC. 

Argocd is not really coupled with Dex and only requires on OIDC. We should remove dex dependency from code and allow using external OIDC provider without Dex in the middle.

**Comment by jessesuen** [comment]
Another reason to support OIDC provider outside of dex is that dex does not seem to support OIDC Implicit flow, which we to have if we want to allow CLI login to an Okta IDp:

https://github.com/dexidp/dex/issues/1254

**Comment by mickleissa** [comment]
Hello,
I have Argocd, I need to connect it with OIDC during dex. I have an issue, when I connected in argocd-cm and argocd-rbac-cm it says's "Failed to authenticate: invaild_scope The requested scope is invalid, unknown, or malformed".
in Azure, I have already set up a group for admin. 
Also, I did curl http://127.0.0.1:5556/dex/.well-known/openid-configuration .  
output 
curl: (28) failed to connect to  http://127.0.0.1:5556 port 80: operation timed out 

What are you think guys the problem is ?

Thank you.
