### ISSUE TITLE
Merge ApplicationSet into Argo CD installation

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#7351]
# Summary

The [applicationset](https://github.com/argoproj-labs/applicationset) was created with the intention to merge it into Argo CD eventually. The project had been validated and mature enough to it should be available out of the box with Argo CD.

# Motivation

In order to improve user experience, the ApplicationSet controller should be available in Argo CD out of the box.

# Proposal

The https://github.com/argoproj-labs/applicationset repository should be moved into https://github.com/argoproj org. The Argo CD controller should include https://github.com/argoproj/applicationset as a library and use it to run controller in the the process with `argocd-application-controller`. The Argo CD installation manifests should include application set manifests

**Comment by sbose78** [comment]
Thanks, this should help close out https://github.com/argoproj/argoproj/issues/30

**Comment by sbose78** [comment]
I'm good with moving the controller into the same process. Are there any concerns with scalability/resource consumption that we should consider ?

**Comment by crenshaw-dev** [comment]
Per discussion today, we shouldn't run the ApplicationSet controller in the same process as the Argo CD (application) controller, because we would have to make changes to mirror Argo CD's support for controller sharding.

Instead, we should add the ApplicationSet deployment to the Argo CD install manifests.

**Comment by crenshaw-dev** [comment]
Merge steps:
 - [ ] Move ApplicationSet repo to the argoproj org from the argoproj-labs org.
 - [ ] Add ApplicationSet install manifests to Argo CD install manifests (CRD, Deployment, supporting resources[?]).
      It's not immediately clear how this will be done. Will have to analyze the manifest generation tools for both projects.
 - [ ] Create ApplicationSet API (should this code live in the ApplicationSet or the Argo CD repo?).
 - [ ] Add UI pages to better integrate ApplicationSet with the Argo CD UI.
      * application set list page
     * application set create page
     * application details page

**Comment by sbose78** [comment]
>  we should add the ApplicationSet deployment to the Argo CD install manifests.

Definitely a lot cleaner.

**Comment by jgwest** [comment]
Presuming that we want to go the route of maintaining ApplicationSet controller as a standalone `Deployment`, rather than integrating it into the application-controller process in the original proposal, the work would look like this:
- Wait for ApplicationSet 0.3.0 to be out (timed roughly with Argo CD v2.2), before we proceed with any of the following steps.
- Move applicationset repo from 'argoproj-labs' to 'argoproj' org
    - One of the argoproj admins would need to do this.
- Update references in the code from `github.com/argoproj-labs/applicationset` to `github.com/argoproj/applicationset`
    - GitHub _should_ transparently redirect until we complete this refactor
    - Then run the existing tests and make sure they still pass :sweat_smile:.
- [`manifests/cluster-install/kustomization.yaml`](https://github.com/argoproj/argo-cd/blob/master/manifests/cluster-install/kustomization.yaml) and [`manifests/namespace-install/kuztomization.yaml`](https://github.com/argoproj/argo-cd/tree/master/manifests/namespace-install/kustomization.yaml) should be updated to reference the ApplicationSet install YAML.
    - For an example of this, see how we are doing this [in the reverse direction with the ApplicationSet controller install](https://github.com/argoproj-labs/applicationset/blob/c574f5e0449e5a76d7c54918993474aebfe3c9e9/manifests/namespace-install-with-argo-cd/kustomization.yaml#L7). 
    - Are there any other `kustomization.yaml` files that we need to update? What about the `manifests/ha` folder?
- Update the Argo CD docs to indicate that ApplicationSet controller is now bundled.
- Update the ApplicationSet docs to remove the install instructions (or at least, to indicate that install is no longer required, once Argo CD v2.3 is released)
- Add the ApplicationSet E2E tests to GitHub actions (not stricly necessary since we are testing in the reverse direction from appset project, but can't hurt)

#### Future work, IMHO on a separate issue:
- Integrate the Argo CD and ApplicationSet documentation, or leave them separate? [This is how they are linked at the moment](https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/).
- UI work was mentioned, but I think that would be a separate issue from this one (which is focused strictly focused on migration)
    - And to answer the question of where this would be implemented, I would think it would live within the existing Argo CD UI code. I think Alex had some thoughts on how this would work.    
- @crenshaw-dev: re: _"Create ApplicationSet API (should this code live in the ApplicationSet or the Argo CD repo?)"_, which API is this?

**Comment by crenshaw-dev** [comment]
> * @crenshaw-dev: re: "Create ApplicationSet API (should this code live in the ApplicationSet or the Argo CD repo?)", which API is this?

@jgwest that item might be the result of bad note-taking on my part. I know that Argo CD has an API server. My impression was that there'd be a similar API specifically for AppSet. But that might be not at all a thing.

**Comment by crenshaw-dev** [comment]
@jgwest I've got some time to put into this. I put up a draft PR to start working through the items in the list. https://github.com/argoproj/argo-cd/pull/7841

**Comment by jgwest** [comment]
@alexmt @ishitasequeira 

We have a minor chicken-and-egg relationship (dependency cycle) between Argo CD and ApplicationSet controller:
- The Argo CD install manifests point to the ApplicationSet install manifests (see PR#8148)
- But, ApplicationSet depends on Argo CD, in ApplicationSet's `go.mod`

## My proposed solution is:

First, Argo CD 'master' branch should always points to ApplicationSet 'master' branch install.yaml: https://raw.githubusercontent.com/argoproj/applicationset/master/manifests/install.yaml (in Argo CD's `manifests/base/applicationset/kustomization.yaml`)

### Combined Argo CD + ApplicationSet release process:

#### 1) Before Argo CD puts out its RC, ApplicationSet should put out its RC:
- Ensure ApplicationSet go.mod has its dependencies pointing to latest commits on 'master' branch of Argo CD codebase
- Push this change to 'master' branch of ApplicationSet
- Make sure ApplicationSet continues to work with with this new dependencies (check that it compiles, check tests are green)
- Follow the ApplicationSet release instructions to put out a draft release ApplicationSet:
	- Create new 'release-0.X.0' branch, where X is the release number.
	- Likewise create new '0.X.0' tag on ApplicationSet repo
	- See [Release Process](https://argocd-applicationset.readthedocs.io/en/stable/Releasing/) and [Release Checklist](https://argocd-applicationset.readthedocs.io/en/stable/Release-Checklist-Template/) for details.

This will create a new install URL that the Argo CD RC will use: `https://raw.githubusercontent.com/argoproj-labs/applicationset/(tag)/manifests/install.yaml`

#### 2) Create the Argo CD RC branch and update it 
- Create the Argo CD RC as usual
- After the RC branch is created, update Argo CD's ApplicationSet reference (in `manifests/base/applicationset/kustomization.yaml`) to point to https://raw.githubusercontent.com/argoproj/applicationset/(tag)/manifests/install.yaml 
- example:  `https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.4.0/manifests/install.yaml`

#### 3) Before Argo CD GA:
- If any changes are merged into the Argo CD release RC branch that might affect ApplicationSet controller functionality (for example, Argo CD updates to how Git repository credentials or cluster secrets are stored), ensure that ApplicationSet release's go.mod is updated to point to the latest commits on the Argo CD RC branch
- Watch the [ApplicationSet nightly cron tests](https://github.com/argoproj/applicationset/pull/470) to make sure that new Argo CD changes don't regress the ApplicationSet controller.

#### 4) On ApplicationSet GA
- Publish the Argo CD GA as usual.
- Publish the ApplicationSet release (follow the ApplicationSet release process URLs above), based on the existing ApplicationSet 'v0.X.0' tag.

Overall, this process ensures that Argo CD GA will point to the latest ApplicationSet release, and that ApplicationSet will get as close a possible to the latest version of the Argo CD dependencies.

**Comment by ishitasequeira** [comment]
@jgwest This totally makes sense. I will update the URL pointing to the master. 
Should the process be documented somewhere in the docs?

**Comment by alexmt** [comment]
Thanks a lot for thinking about it, @jgwest ! Agree with your proposal - it makes total sense.
