### ISSUE TITLE
ACME support

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#743]
It would be great if ArgoCD supported ACME protocol so that it could automatically update it's own certs. This would be useful in environments which run without automated cert managers like cert-manager or Traefik w/ ssl passthrough.

Reference:
https://letsencrypt.org/docs/client-options/

**Comment by twz123** [comment]
Wouldn't it be wiser to just rely on a dedicated external tool to for
certs, like Jetstack's cert-manager?

**Comment by jessesuen** [comment]
Normally, yes that would be the recommended approach. But it seems we have some users who use traefik, which provides the same capabilities of cert-manager. We're still investigating Traefik + Argo CD, but it may require to use ssl passthrough, which means users might lose traefik's ACME support for the service. If Argo CD supported ACME natively, then they wouldn't have to use Traefik + Argo CD + cert-manager.

Another use case it would enable, is if a user exposes Argo CD with service type LoadBalancer, and does not use ingress or cert-manager.

Anyways, before implementing ACME support in Argo CD, I would like to explore if Traefik could be configured in a way where it can updating the Argo CD secret with the new certs. Also will leave this bug open for a while to see if there's even any interest in this before implementing anything.

**Comment by twz123** [comment]
I see, thanks for the explanation. I was just surprised about built-in ACME
support, given the fact that there are just too many ways to do an ACME
challenge. But Argo CD will supposedly most likely focus on HTTP challenges
then. This requires Argo CD to be exposed to public internet, but okay. If
that's an issue, the other options are still available. Just to mention,
TLS termination on pods using service type LoadBalancer works pretty
straight forward with cert-manager, since it just creates and updates TLS
Secrets in k8s. No ingress or public internet exposure required.

**Comment by jessesuen** [comment]
Having finally played with cert-manager, I agree this is way out of scope for Argo CD. Thanks for the insight.
