### ISSUE TITLE
Publish hyperkube-style image

### ISSUE THREAD

**Issue by wmedlar** [argoproj/argo-cd#762]
ArgoCD currently publishes several images that are all essentially the same, just named separately:
- argoproj/argocd-application-controller
- argoproj/argocd-repo-server
- argoproj/argocd-server

Additionally there's the ui container, argoproj/argocd-ui, that appears to follow the same versioning.

It would be great to publish a "hyperargocd" image that contains all of the above, to make running ArgoCD easier to manage versioning. You can achieve nearly the same thing right now by using any of the top three containers with different entrypoints, but that creates confusion for unfamiliar developers managing ArgoCD.

**Comment by jessesuen** [comment]
> ArgoCD currently publishes several images that are all essentially the same, just named separately
> You can achieve nearly the same thing right now by using any of the top three containers with different entrypoints, but that creates confusion for unfamiliar developers managing ArgoCD.

Very keen observation! You're right in that the images are basically the same with different entrypoints.

Some history about this. Before the current, consolidated version of the Dockerfile, it was actually the case that we had several Dockerfiles, one for each service. But, as it turns out, having/building several Dockerfiles with slightly different make targets, is way more inefficient than a single Dockerfile with all three binaries built in, which is what we have today.

Now that we simply have a single Dockerfile, you're exactly right in that we could consolidate it into one image, and forgo the management of separate images for each service. There's no real technical reason for having three images so I think having a single image for argocd backend makes sense to me.

That said, I don't think we want to rolling in the UI to the master image, since the UI is developed separately.

**Comment by jessesuen** [comment]
Fixed
