### ISSUE TITLE
Support Generic Webhook for Internal Repositories

### ISSUE THREAD

**Issue by cite** [argoproj/argo-cd#7685]
# Summary

Argo CD should provide us with a way to receive notifications about custom, internal git repositories.

# Motivation

For security reasons, we have to mirror all of our GitHub org to an internal mirror, so all our git sources point to that internal mirror. With several thousand of applications, and the need to react more quickly than the default polling period, we should have a way to trigger notifications.

Currently, support for receiving webhooks is limited to GitHub, Gitlab and some other products.

# Proposal

A new webhook could receive the affected repository and then pull changes.

**Comment by jessesuen** [comment]
The reason for specific GitHub, GitLab, BitBucket, etc... integrations is because they have well-defined, documented payloads in which we know where to extract the relevant git URL. To support this feature request, we would need to allow Argo CD configuration of how to interpret bespoke payloads.

Since you mentioned that you have mirrors of github, what is the custom git provider are you using that would webhook events? Is this something homegrown that you can control? If so, you should be able to mimic the GitHub/GitLab payloads as a workaround, but only send the structure that Argo CD cares about.

**Comment by jessesuen** [comment]
A second workaround is that instead of a Git webhook payload, your custom git provider could instead perform app refreshes of the affected apps. For example, list applications in a repo and calling refresh on each of them. This is in fact what Argo CD webhook is doing.

**Comment by cite** [comment]
We'd indeed write our own code to create the webhook, so yes, mimicking GitHub would be an option (and looking at the source, it seems we can indeed get away with a tiny subset of fields.

My idea was inspired by the way that Jenkins handles [push notifications|https://plugins.jenkins.io/git/#push-notification-from-repository], it's basically enough to `curl http://yourserver/git/notifyCommit?url=<URL of the Git repository>`, which is less work than generating our own webhook.

As for your second comment, how would I list all applications that use a specific repo? Thanks for your time so far, much appreciated.

**Comment by jannfis** [comment]
I think the Jenkins way (e.g. just having a GET request to an endpoint and specifying the repository URL as a parameter) would certainly not be enough, since we also inspect the payload for paths/files that have changes in the commit (plus possibly some other things), in order to do selective refreshes of apps source from the same repository & target revision.

**Comment by richardpj** [comment]
I have a monorepo hosted in AWS CodeCommit. It contains 400 applications deployed to 9 clusters. 

I'm running 4 argocd-repo-server replicas and 2 sharded argocd-application-server pods.

The argocd-application-server pods are consuming a lot of resources. I believe that they are performing a lot of unnecessary reconciliation due to the setup lacking webhooks.

Is AWS CodeCommit webhook support on the roadmap? If not then documentation on the required fields from the Github webhook payload would be really helpful so that I could fake a github webhook in a lambda. Re-implementing github webhooks completely is a huge waste of effort that I cannot afford.

**Comment by MPV** [comment]
We have also run into this (as it broke for us after upgrading to ArgoCD 2.0 due to https://github.com/argoproj/argo-cd/pull/5565/).

**Comment by MPV** [comment]
I imagine "faking GitHub" would mean chasing the tail of "which attributes do we set, due to them being used/depended on throughout the ArgoCD UI"?

**Comment by MPV** [comment]
If one would fake/mimic GitHub, here's what we've talked so far about trying:

HTTP headers:
`X-GitHub-Event: push`

HTTP body:
```json
{
  "ref": "refs/heads/master",
  "before": "git show --no-patch --pretty=%P",
  "after": "git show --no-patch --pretty=%H",
  "repository": {
    "html_url": "https://our-internal-repo-server/our-repository.git",
    "default_branch": "master"
  },
  "commits": [
    {
      "modified": ["git diff --name-only HEAD^1"]
    }
  ]
}
```

...but replacing the `git` commands with their actual output.

**Comment by richardpj** [comment]
> reate the webhook, so yes, mimicking GitHub would be an option (and looking at the source, it seems we can indeed get away with a tiny subset of fields.
> 
> My idea was inspired by the way that Jenki

After checking this section of [/util/webhook/webhook.go](https://github.com/argoproj/argo-cd/blob/df2d6497513630f873dc17452f5ad05aac4188d0/util/webhook/webhook.go#L102) it appears that's a good start. I may give it a try. Thanks!

**Comment by btrepp** [comment]
I was chasing this for sending a hook after sourcehut updates my image tags.

I think it would be great if rather than mocking GitHub, there was a minimal reference 'generic' one. That way you know exactly what fields are expected.

Will give it a shot mocking GitHub as above though

**Comment by marcelomendes** [comment]
> I think it would be great if rather than mocking GitHub, there was a minimal reference 'generic' one. That way you know exactly what fields are expected.
> 

I'm using gitea (gogs fork), this would be great.

**Comment by cite** [comment]
We settled on something very lightweight:

```bash
#!/bin/bash
 
USERNAME="$1"
PASSWORD="$2"
REPO="$3"
 
ARGOCD_ENDPOINT=https://<your endpoint>/api/v1
ARGOCD_TOKEN=$(curl -s -XPOST  $ARGOCD_ENDPOINT/session -d $'{"username":"'$USERNAME'","password":"'$PASSWORD'"}'  | jq -r .token)
ARGOCD_AUTH="Authorization: Bearer $ARGOCD_TOKEN"
 
for app in $(curl -s -H "$ARGOCD_AUTH" $ARGOCD_ENDPOINT/applications?repo=https://<your repo>/<stuff>/example.git | jq -r ".items[].metadata.name"); do
  curl -s -H "$ARGOCD_AUTH" $ARGOCD_ENDPOINT/applications/$app?refresh=true >/dev/null
done
```

**Comment by crabique** [comment]
This is even more relevant now that plugins can take over the templating, so the git paths don't mean as much because the plugins can have their internal view of the application sources. 

A generic webhook-based refresh trigger mechanism is required to make ArgoCD recognize a new push and begin reconciling the repo-server stuff, otherwise it becomes the slowest component of the CD pipeline.
