### ISSUE TITLE
argo-cd does not sync until 3 minutes after push.

### ISSUE THREAD

**Issue by pawandwivedi** [argoproj/argo-cd#7893]
**Describe the bug**

when there is change in the code. i sync argo-cd manually and after that i see the argo shows it is syncing but actually there is no change or nothing happens and then after 3 minute wait again auto sync happen automatically and all is up to date. So the thing is there is delay of 3 min in auto-sync. before there was no problem of auto-sync like this. i am facing this from last 2 days.

**To Reproduce**

1. push the changes to git.
2. go to argo-cd and sync the application.

**Expected behavior**

it should sync when we sync from argo-cd without 3 min delay.

**Comment by alias-rahil** [comment]
After pushing, you have to click on refresh.

Sync option checks if the desired state is same as actual state in the cluster. But argo-cd doesn't know yet that the desired state itself has changed.

**Comment by lavurohit** [comment]
ArgoCD polls configured git repositories every 3 minutes but if you want to bypass this delay you can setup a git webhook. Argo CD supports Git webhook notifications from GitHub, GitLab, Bitbucket, Bitbucket Server and Gogs. [Here](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/) is the documentation for setting up a webhook.

**Comment by blakepettersson** [comment]
This is not a bug, see [webhooks](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/).

**Comment by corneliusroemer** [comment]
To all those coming here, webhooks are a workaround. It does not seem possible (by design) to change the interval at which the sync happens.

The actual webhook message to send to your `/api/webhook` endpoint is:

```json
{
  "ref": "refs/heads/master",
  "project":{
    "web_url":"https://gitlab.my.domain/project/repo.git",
    "default_branch":"master"
  }
}
```

(from https://github.com/argoproj/argo-cd/issues/914#issuecomment-2033973679)

Github and Gitlab can be configured to send such webhook events in the UI, for other git servers one might need to send the webhooks through CI.
