### ISSUE TITLE
SSH agent requested but SSH_AUTH_SOCK not-specified

### ISSUE THREAD

**Issue by whyvez** [argoproj/argo-cd#8084]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
* [x] asked in slack argocd channel

**Describe the bug**

I am getting a SSH agent requested but SSH_AUTH_SOCK not-specified error every time I trigger a hard refresh from the ArgoCD UI. I only have one repo template credential configured, and the repo in question matches the template. The odd thing is that the refresh does work, and GitHub changes are pulled. I've deleted and recreated the template credentials but the problem persists. This seemed to have started around the time I added the new Github `ed25519` to known hosts cm. I also tried restarting the repo-server, argo-server and argo-controller. I've seen many references to this issue in the repo but none seem to be what I am experiencing. Anybody know what I could do to silence this error?

**To Reproduce**

The issue seems environmental and would be hard to describe steps to reproduce. It did start happening after the GitHub `ed25519` issue. At first, I added the known host manually to the ArgoCD known host ConfigMap, but after an ArgoCD update, I believe it was part of the update.

**Expected behavior**

No errors on hard refresh.

**Screenshots**

<img width="194" alt="Screen Shot 2022-01-04 at 7 56 48 AM" src="https://user-images.githubusercontent.com/1593907/148078075-90c73871-3f42-4727-bd2f-0a429a83d8f9.png">

**Version**

```shell
argocd: v2.2.1+122ecef.dirty
  BuildDate: 2021-12-17T16:09:59Z
  GitCommit: 122ecefc3abfe8b691a08d9f3cecf9a170cc8c37
  GitTreeState: dirty
  GoVersion: go1.17.5
  Compiler: gc
  Platform: darwin/arm64
```

**Logs**

```
"time="2022-01-03T21:56:40Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-01-03T21:56:40Z\",\"message\":\"rpc error: code = Unknown desc = error creating SSH agent: \\\"SSH agent requested but SSH_AUTH_SOCK not-specified\\\"\",\"type\":\"ComparisonError\"}]}}" application=iris-development"
```

**Comment by nicolastakashi** [comment]
Same here

**Comment by StephanSalas** [comment]
Same here!

**Comment by Jojoooo1** [comment]
same in v2.3.0-rc4+ed734fe

**Comment by mlerota** [comment]
I had the same error but when adding the application. Reinstalled everything, lost 10 hours, and then accidentally found out that I added the wrong repo :-).
Added:
 `argocd repo add ssh://AWS_SSH_KEY_ID@git-codecommit.eu-west-1.amazonaws.com/v1/repos/one-repo --ssh-private-key-path /path/to/id_rsa`

And in the manifest was
`spec`
  `  project: default`
      ` source:`
    `repoURL: 'ssh://AWS_SSH_KEY_ID@git-codecommit.eu-west-1.amazonaws.com/v1/repos/other-repo'`

It would be good that in error your have something meaningful like: "can't find repo-name"

**Comment by lud97x** [comment]
Same for me, after verification, the ssh repo url was wrong.
I think the error shown by argocd in that case is misleading.

**Comment by whyvez** [comment]
I was able to solve my issue after seeing this issue: https://github.com/argoproj/argo-cd/issues/4358

Specifically: https://github.com/argoproj/argo-cd/issues/4358#issuecomment-1031983396

Looks like the update to 2.2.3 changes the application controller from a `Deployment` to a `StatefulSet` and the old deployment is never deleted. 

I deleted the `application-controller` `Deployment` and all is well!

Thank you @jdmulloy !

**Comment by Orabig** [comment]
Same issue here, but : 
- I'm certain that the repo is right (proof below)
- I didn't upgrade argocd, thus I don't have the same issue than @whyvez 

I have this error message _**"error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"**_ when I try to use Credential Templates for my github server ([as documented here](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#credential-templates)).

So, when I push the private SSH key under the repo **ssh://git@my_scm_server/path/** I get the error message, but if I push the private key under each project, like **ssh://git@my_scm_server/path/project1.git**, **ssh://git@my_scm_server/path/project2.git** ..., then it works perfectly.

Thus I'm afraid that this case is NOT closed.

**Comment by qixiaobo** [comment]
Same here.

**Comment by ninja-** [comment]
same, I forgot I bootstrapped argocd by authenticating it to gitlab using an api token, and not the ssh key. so the fix is as simple to switch to a https url instead of git+ssh...

**Comment by mhvelplund** [comment]
> I had the same error but when adding the application. Reinstalled everything, lost 10 hours, and then accidentally found out that I added the wrong repo :-).
> <SNIP>
> It would be good that in error your have something meaningful like: "can't find repo-name"

This ... I added the correct repo but set the branch to "feature/fix_cicd" instead of the actual source branch "feature/fix-cicd".

The repo showed up as successfully created, but application sync failed with a weird error, and the log had "SSH agent requested but SSH_AUTH_SOCK not-specified". Neither of which make any sense. 

The correct error would be "can't find repo/branch combination" 😡

**Comment by AlRemes** [comment]
We had similar issue as well and wanted to share a possible cause and workaround that helped us:
 
In our case, the error:
 
error testing repository connectivity: unable to ls-remote HEAD on repository: failed to list refs: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
 
was caused by the repository being assigned to the wrong Argo CD project, when connecting a new repo. The SSH key was configured correctly, but Argo CD couldn't find it because the repo was associated with a different project than the application trying to use it.
 
Workaround:
When adding the repository in the Argo CD UI, we left the project field empty, which allowed the application to access the repo and resolved the error.
 
This might be worth documenting or improving in the error message, as it can be misleading and suggest an SSH agent issue when it's actually a project/repo visibility mismatch.
