### ISSUE TITLE
[UI] UI should convert UTC to local browser time

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#819]
It's annoying to try to resolve UTC to local time every time I'm trying to figure out what happened. We should display in local browser time. Also, having a "X time ago" context would help (e.g. 10 minutes ago)

**Comment by rowleyaj** [comment]
Please can this be configurable? We have servers configured as UTC so when comparing logs with the UI it would be helpful if they were in UTC also. I do see the benefit of local timezone support however.

Grafana handles this quite well we support for both local timezone and UTC.

**Comment by kwladyka** [comment]
I would like also see this times from main view of all Applications.
`/applications`

Just to enter there from time to time and see if everything is ok. Because green status doesn't really mean there are no failed resources in Application. Fo example extra resources generated from original one, like cert-manager resources. So I have to check it manually anyway even if it is green.

In other words I am checking Applications after changes manually, but at that moment I can't easy know which Applications changed.

**Comment by alexec** [comment]
This would be a great one for community contribution.

**Comment by kwladyka** [comment]
Unfortunately I am not GO developer, so I can't really help coding.

**Comment by alexec** [comment]
Fixed in https://github.com/argoproj/argo-cd/pull/1762.
