### ISSUE TITLE
Set admin password on install

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo-cd#829]
Is it possible to set the admin password decoratively as possible as installing the argo cd app?

For example, can we  use a K8s secret?

Right now it looks like there is an API and CLI to change the password.

Might also be useful to be able to set the password  via the UI.

**Comment by jessesuen** [comment]
As you observed, the argocd-secret Secret is where we store the password. However, we don't store plain-text password strings (base64 or otherwise). The password is bcrypted and the original value cannot be retrieved from the hash alone.

Since this is standard bcrypt, you can use any number of bcrypt tools to generate a bcrypt hash that will validate a preferred password string:
https://unix.stackexchange.com/questions/307994/compute-bcrypt-hash-from-command-line 

This will let you populate the `admin.password` key of the argocd-sercret with a preferred password.

**Comment by jlewi** [comment]
Thank you.

**Comment by reegnz** [comment]
For anyone stumbling on this question:
```
kubectl get secret -n argocd argocd-secret -o json | jq '.data|to_entries|map({key, value:.value|@base64d})|from_entries'
```

The default password is only working until the pod name is the same. Pod names are not stable, so having the pod name as the default password is bad. (Of course not using a proper OAuth provider is bad aswell..., so touche).
I ran into the issue of the pod name changing (did an update of the deployment) and couldn't log in anymore, so I had to have a way of changing the password.

**Comment by aroute** [comment]
I'd like to know how to use the user setup via htpasswd (UPI OpenShift install, ArgoCD setup via Operator). I tried the default admin account but was not able to setup an application (all kinds of permission/rbac issues). Is it possible to use htpasswd provider with ArgoCD?

**Comment by shibumi** [comment]
@reegnz  looks like this doesn't work anymore:

```
kubectl patch secret -n argocd argocd-secret \
  -p '{"stringData": { "admin.password": "'$(htpasswd -bnBC 10 "" newpassword | tr -d ':\n')'"}}'
```

For example I tried this:
```
kubectl patch secret -n argocd argocd-secret -p '{"stringData:": {"admin.password": "$2y$10$Kpni7oquu5ks6HqNdr5u4O1.EelHNUbe1tu19xAZaACPBnuJm4S7a"}}'
```
(do not worry.. the pw is not a secret ;) )

If I apply this kubectl tells me this:

secret/argocd-secret patched (no change)

but if I check the secret, it is still the old pw and not the new one oO
