### ISSUE TITLE
Deploying pods from local code

### ISSUE THREAD

**Issue by karkrish** [argoproj/argo-cd#846]
Hi Team,

We exploring argo CD to deploy the PODS in to our EKS cluster. As mentioned in the documentation, we see the deployment yamls are retrieved from git repo and it performs the deployment. 

As we are starting with the tool and for our testing purpose, Is there any other option/solution to refer the yaml templates from the local machine?

**Comment by jessesuen** [comment]
Hi @karkrish, this very same question came up in https://github.com/argoproj/argo-cd/issues/839. The short answer is that for local development, you should be able to do any of the following:

* `kubectl apply -f <directory of your manifests>`
* `kustomize build . | kubectl apply -f -`
* `ks show my-env | kubectl apply -f -`
* `helm template . | kubectl apply -f -`

Since Argo CD alo deploys everything using `kubectl apply`, we are are more or less compatible with this mode.

The caveat is that currently in v0.10, we rely on injecting labels into pod templates in deployment manifests, in order for the controller and UI to discover all the related objects of an application. Starting with our upcoming v0.11 release, we will no longer inject argocd labels inside deployment.spec.template.metadata, since we now have a more robust way of discovering child resources without relying on our injected labels.

NOTE: we will still inject labels at the top level objects, This is needed in order to support deletion and pruning.

**Comment by karkrish** [comment]
Thanks for the update @jessesuen

I am able to connect to the repos. While deploying, its not able to find the environment. Attached the screenshot and the yaml template for your reference. Can you please provide your thoughts on this?

![image](https://user-images.githubusercontent.com/22123955/49312311-ca95be00-f4b1-11e8-956d-d63e38299823.png)

Yaml

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: s3readonly
      labels:
        app: myapp
        version: 1.0.0
    spec:
      containers:
      - name: authn
        image: myregistry.com/authn:kms
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi

**Comment by jessesuen** [comment]
Duping this to https://github.com/argoproj/argo-cd/issues/839
