### ISSUE TITLE
UI warning about force sync option

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#8466]
# Summary

HI, 

Is it possible to disable Sync + Force via argocd RBAC ?

![image](https://user-images.githubusercontent.com/46923567/153551481-a3f9f0aa-b9ff-4a65-b509-be0fdeac2f62.png)

# Motivation

Our customers use argoCD to install and upgrade our software on top of kubernetes. Since "Force" being destructive in nature, one of our customer ended up in doing so i.e. "Sync + Force" and it resulted in few namespaces getting purged and resources getting deleted and it took quite a lot of time to debug the issue as we didn't thought argoCD could be the root of issue

**Comment by jessesuen** [comment]
It's unlikely we will add separate RBAC just for a sync option. Argo CD RBAC is granular to actions/resources and sync option is too granular of an action.

That said, I agree force needs a stronger warning (like replace) because it is potentially disruptive.

Also, what might help you in the future, is when we have user/serviceaccount impersonation, you would be able to use kubernetes RBAC so that deletes on namespaces prevented by kubernetes RBAC.

I'm converting this issue to be a UI improvement about force option, so users have a similar warning like replace about it potentially being a destructive action.

**Comment by rajivml** [comment]
@jessesuen thanks for looking into it, do you have any ticket tracking user/serviceaccount impersonation efforts ?

and btw if not RBAC, is it possible to add a flag through which "replace" and "force" option can be completely hidden from UI ?

**Comment by terrytangyuan** [comment]
BTW, I just submitted a PR to add the warning in https://github.com/argoproj/argo-cd/pull/8574. Feel free to review and leave any feedback there.

**Comment by rajivml** [comment]
@terrytangyuan thanks for taking it up, it looks good to me. Also want to know if it is technically possible to expose an flag through which force and replace can be disabled because even with warnings, I have seen users blindly syncing apps with replace or force resulting in un-expected behavior

Just for this functionality we don't want to clone the repo and maintain it
