### ISSUE TITLE
Access to the events in the LUA health checks

### ISSUE THREAD

**Issue by samm-git** [argoproj/argo-cd#8529]
# Summary

I would like to be able to access events data in the lua health checks. This would help to write a health check which knows better if resource is really healthy or not. 

# Motivation

I am writing health check for the `PersistentVolumeClaim`. It is expexted for this resource to be in the `Pending` state with `WaitForFirstConsumer` event. However, this `WaitForFirstConsumer` event is not expoted to the state object, so i had to write check like that:

```lua
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              hs.status = "Healthy"
              hs.message = "PersistentVolumeClaim is in pending state"
              return hs
            end
            if obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = "PersistentVolumeClaim is in bound state"
              return hs
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Status is not yet known"
        return hs
```

# Proposal
My proposal is to export not only `obj` event to the LUA, but also `events`. So code will be able to check it and set health check accordingly.

**Comment by jessesuen** [comment]
Health checks are intentionally limited to examining just the single resource it is assessing. It is required to happen quickly since Argo CD is assessing health of hundreds objects many times a second. Including other objects (including Events) would increase the complexity of the controller logic as well as impact the performance. We would need to start caching Kubernetes events (which we currently ignore because the high churn and volume).

Realistically, I don't see this ever happening.

**Comment by samm-git** [comment]
@jessesuen ok, thank you for reply and explanation. I will think, may be i can use hooks to update annotations and use them in the healthcheck
