### ISSUE TITLE
Argo-cd doesn't mark resources with additional field "spec.tolerations" as "Out of sync"

### ISSUE THREAD

**Issue by MalKeshar** [argoproj/argo-cd#8554]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Argo-cd doesn't mark resources with additional tolerations fields as "Out of sync"
Tested on daemonset and deployment

**To Reproduce**
* Use kubectl to add tolerations to daemonset or deployment of currently deployed app via argo-cd
For example
`$ kubectl -n logging patch daemonset.apps/fluent-bit -p='{"spec":{"template":{"spec":{"tolerations":[{"effect":"NoSchedule","operator":"Exists"}]}}}}'`
* Refresh and checkout app status in web interface.  
Argo-cd sees tolerations field in live manifest, but does not show any difference with desired manifest and don't mark resource as out of sync.

**Expected behavior**
I expect argo-cd  show differenct between manifests and mark resource as "out of sync"

**Screenshots**
Desired manifest
![Screenshot_20220217_220645](https://user-images.githubusercontent.com/13730780/154552977-b58468c4-e2be-4ca4-85be-5daef6dd7b56.png)

Cut from live manifest
![Screenshot_20220217_220650](https://user-images.githubusercontent.com/13730780/154552943-026f4a5f-e8f6-4ca0-ac16-ba1a1d5842ea.png)

Overall status of resource and empty diff
![Screenshot_20220217_220649](https://user-images.githubusercontent.com/13730780/154553081-3ebdc630-7ef5-4bab-9905-75aed6aa9514.png)

**Version**
```shell
v2.2.3+987f665
```

**Logs**

**Comment by jessesuen** [comment]
This is expected behavior when you are mixing imperative updates with declarative ones (kubectl apply). `kubectl apply` records your intent in the `last-applied-configuration` annotation, whereas `patch` and `kubectl edit` do not. The former is what allows diffing to be accurate. The patch you applied is treated like the normal behavior of kubernetes controllers defaulting fields of the object, which we ignore because Argo CD does not believe them to be managed by the user (since they were not `kubectl applied`).

**Comment by MalKeshar** [comment]
Thank you for explanation.
