### ISSUE TITLE
Ignore spaces in diff view

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#8561]
# Summary

Currently, spaces are always displayed in diff.

<img width="326" alt="Screen Shot 2022-02-18 at 3 19 10 PM" src="https://user-images.githubusercontent.com/6813397/154636275-5f193044-a443-45d3-abe1-b41a8c24afc1.png">

It would be nice to have an option to ignore spaces.

# Motivation

Ignoring spaces will help user focus on content changes that really matters.

# Proposal

git diff supports various option to ignore spaces
```
       --ignore-space-at-eol
           Ignore changes in whitespace at EOL.

       -b, --ignore-space-change
           Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all
           other sequences of one or more whitespace characters to be equivalent.

       -w, --ignore-all-space
           Ignore whitespace when comparing lines. This ignores differences even if one line has
           whitespace where the other line has none.
```

`--ignore-space-change` could be the most common case.

**Comment by jsoref** [comment]
This isn't the right strategy. Whitespace diffs in ArgoCD _often_ mean that ArgoCD will get stuck in a loop _trying_ to synchronize because the actual and desired values aren't identical. Instead, it's best to have a view that makes it easier for users to understand the differences so they can work to resolve them.
