### ISSUE TITLE
Add test for using private repos in AppSet tests

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-cd#8967]
# Summary

We need tests to show that the ApplicationSet controller can handle private repositories.

# Motivation

When ApplicationSet was merged with Argo CD, I think we upgraded to the new credentials passing mechanism without ensuring that it was working. I think we need the AppSet controller to run the git-ask-pass server.

# Proposal

Copy patterns from the already-existing Argo CD tests for private repos.

**Comment by iam-veeramalla** [comment]
@rishabh625 do you want to work on this or through some input for the tests ?

**Comment by rishabh625** [comment]
Oh yeah that I missed. thanks!!! @iam-veeramalla  for bringing it to my notice as i m not following argocd,

Yeah I'll add the tests tysm

**Comment by rishabh625** [comment]
Currently private repo in git generator is not working, as askpass method for credentials was used without starting server. If we start the askpass server , private repo in git generator works good. Problem is with e2e tests since e2e test share same os and filesystem starting a new server in appset overwrites the sock file and askpass mechanism doesn't work in repo server. m unsure of how to proceed on. Related [PR](https://github.com/argoproj/argo-cd/pull/9179)

**Comment by rishabh625** [comment]
closing as fixed
