### ISSUE TITLE
Connaisseur 

### ISSUE THREAD

**Issue by brackend** [argoproj/argo-cd#8990]
**Describe the bug**
Because connaisseur replaces the image's tag with a hash, Argocd views it as out-of-synch

**Expected behavior**
This is kind of expected.  But is there a way to turn off the warning without compromising ARgocd's ability to otherwise detect out of synch states

What change you think needs making.

An option to ignore image hash

Please give examples of your use case, e.g. when would you use this.

Connaisseur using admission hook to verify signature of image:tag.  If it succeeds it then converts tag to hash.  

How do you think this should be implemented?

**Comment by crenshaw-dev** [comment]
Could you [ignore differences](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs) for the image field, and set the tag in an annotation? That way it still goes out of sync for actual tag changes, but it doesn't go out of sync for hash changes?

Would be even nicer if Connaisseur had a way to push tags to git.

**Comment by iam-veeramalla** [comment]
@brackend have you tried to use [ignore differences](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs) for the image field as @crenshaw-dev suggested. Please let us know if the suggested solution does not work for you :)

**Comment by iam-veeramalla** [comment]
Hi @brackend any update on this ?

**Comment by gilgoodridge** [comment]
@crenshaw-dev I'm having this same issue.  In your suggestion, you said "...and set the tag in an annotation...".  Since I don't have control of most of the helm charts that I'm using, I'm creating annotations on the application manifests and setting those annotations to the tag used in the deployment/statefulset/daemonset.  That will, of course, show the application as out-of-sync whenever I update image tag(s).  But I'm worried that it won't automatically deploy the new image because it won't detect a difference in the deployment/statefulset/daemonset.  Or will it as long as I always use `RespectIgnoreDifferences=false`?

**Comment by frobones** [comment]
> @crenshaw-dev I'm having this same issue. In your suggestion, you said "...and set the tag in an annotation...". Since I don't have control of most of the helm charts that I'm using, I'm creating annotations on the application manifests and setting those annotations to the tag used in the deployment/statefulset/daemonset. That will, of course, show the application as out-of-sync whenever I update image tag(s). But I'm worried that it won't automatically deploy the new image because it won't detect a difference in the deployment/statefulset/daemonset. Or will it as long as I always use `RespectIgnoreDifferences=false`?

If `RespectIgnoreDifferences=false` it will work. I've had this issue that solved my problem.
