### ISSUE TITLE
Make Repos and other setting items editable in the Argo CD UI

### ISSUE THREAD

**Issue by ciiay** [argoproj/argo-cd#9108]
# Summary

We got feedback from an Argo CD user that it would be nice to have as many as the settings to be editable.

# Motivation

Currently it's possible to add/delete things in the repo list, but not update.

Clusters and Projects are editable in UI now, I would like to be able to update repos and other settings using the Argo CD UI

(https://cd.apps.argoproj.io/settings/repos) 

# Proposal

Create a repo details page which allows updating selected repo information.

**Comment by ciiay** [comment]
According to the discussion from April 14th Argo Contributor Experience Meeting, some of the settings are designed to be immutable, such as certificates and keys. 

For repositories, I confirmed with @rbreeze that there's already a CLI command `argocd repo add --upsert` to do so, so it should be an easy UI change to make repositories editable.

For account settings, we can open a discussion about what kind of information needs to be editable and worth the change.

**Comment by Morriz** [comment]
Alo, IMO, it would be poor design to render a resource uneditable simply because some fields in it are read-only or should be hidden based on authz. In otomi.io we use abac to filter out fields before PUT/POST data goes to storage, and after GET data leaves the service. We allow any resource and it's nested data structures to be edited based on authz.
