### ISSUE TITLE
When deploying a Helm chart via UI the values files is not persisted

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#952]
When addding a Helm chart via de UI the values file is not persisted 
![image](https://user-images.githubusercontent.com/9946020/50268087-bea27980-0429-11e9-84b1-d201808e8eb3.png)

A manual update is necessary to fix it:

argocd app set prd-generic-all-cluster --values values-prd-cluster.yaml

**Comment by alexmt** [comment]
Looks like UI is confusing. Helm values editing component consist of text input field, '+' button and list of values files labels which are already selected. So to add values file user has to click on input, select values file from dropdown and click '+' button. This behavior was implemented to support values files from URL or relative paths (e.g. ../common/values.yaml)

![screen shot 2018-12-26 at 10 48 54 am](https://user-images.githubusercontent.com/426437/50454462-abe1e600-08fc-11e9-8ff9-cad6fd1810e8.png)

It is confusing because user might think that values file is already added after selecting it from dropdown. The https://github.com/argoproj/argo-cd-ui/commit/d4e4d7e4b48c07f569abcd11774f6e601767f9b7 improves UI. Now if user select values file from dropdown it should be automatically added.

**Comment by peterbosalliandercom** [comment]
Thank you, it is clear indeed
