### ISSUE TITLE
Support conditions within ApplicationSet templating

### ISSUE THREAD

**Issue by DmitrySenin** [argoproj/argo-cd#9681]
# Summary

I would like to propose to make ApplicationSet templating include conditions or some sort of switch operator

# Motivation

In my use-case, ApplicationSet is part of a helm repo which already dictates which TargetRevision to use. The AppSet is based on Git Files Generator, and I would like to be able to optionally override TargetRevision in a file
So something like this

├── cluster-config
│       ├── dev
│       │ ──── config.json
│       └── prod
│        | ──── config.json

where `prod/cluster.config` is empty but `dev/cluster.config` has
```
argo:
  targetRevision: PR
```

# Proposal

In ApplicationSet, I would like to be able to do something like

```
...
source:
  repoURL: <url>
  targetRevision: {{argo.targetRevision}} or {{ .Values.argo.targetRevision }}
```
If `argo.targetRevision` is provided in the respective `config.json` then use the value from there, otherwise fallback to the helm variable

Seems like there is another problem which is `argo.targetRevision` may not be specified. In this case, templating should not fail and fall back to `{{ .Values.argo.targetRevision }}` as well

**Comment by crenshaw-dev** [comment]
This feature is what I'd call "field-wise" templating. I think it could be done by recursing through the template and running golang text template to substitute each field.

It would not support:
1) non-string fields or
2) conditionals/loops/etc. - i.e. operations that implicate more than one field

I'd love to see this feature, because I think it's a relatively secure alternative to just making the template one big templateable text field.

Would you have any interest in contributing? I'd be happy to help with dev env. setup and review.

**Comment by nerzhul** [comment]
hello, it's clearly a usecase we'd like to see, for example {{product.name | default 'undefined' }} or a similar syntax depending on the language you selected. It prevent appset failure when a label is not set :)
