### ISSUE TITLE
Resources are not deployed to the cluster

### ISSUE THREAD

**Issue by rshiva777** [argoproj/argo-cd#9915]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Resources created by application are not deploying to the cluster.

I have created application  which deploys kubernetes resources like deployments/secrets/configmaps/clusterrole/clusterrolebinding.

However i havent granted permission for cluster resources clusterrole/clusterrolebinding at project level.

When i try to deploy the application, none of the resources is creating on cluster even thought deployments/secrets/configmaps have permission inside the project.

**To Reproduce**

Create an application with git repo pointing to the deployment, configmap, secret, clusterrole and clusterrolebinding manifests
The project must have permissions only for deployment, configmap, secret and deny clusterrole and clusterrolebinding.
.
**Expected behavior**

deployment, configmap, secret must be created on the cluster, and  clusterrole, clusterrolebinding must be denied

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```
root@testserver:~/home$ argocd version
argocd: v2.3.1+b65c169
  BuildDate: 2022-03-11T00:01:03Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.1+b65c169
  BuildDate: 2022-03-10T22:51:09Z
  GitCommit: b65c1699fa2a2daa031483a3890e6911eac69068
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0

**Logs**

```
Paste any relevant application logs here.
```

**Comment by scalen** [comment]
This will be because there is a strict ordering in which kinds of resources are deployed in a Helm release, and if an earlier kind fails then later kinds don't even try. I believe already deployed resources should be deleted as part of an automated rollback, as Helm releases are supposed to be atomic... But even if some resources weren't rolled back, no "later" resources would be installed in the first place.

Roles, ServiceAccounts and RoleBindings are always deployed first, as they are needed to then deploy Deployments etc that rely on those ServiceAccounts.

If you are in control of this Helm chart, and the roles/bindings aren't strict requirements of the chart, I would recommend adding values that allow you to enable/disable the creation of those resources. Then you can set those values in your Application to disable those resources.

**Comment by rshiva777** [comment]
Hi @scalen,

Thanks for the quick response. That's correct when i deploy using helm charts. At present, i m deploying using manifest files directly without using helm, does  argocd follow same for pattern as helm chart  for directory?

More over, when i try to sync manually the other components deployment/configmap/secret from argocd application UI, they are getting synced, only issue happens during fully sync of entire application.

**Comment by scalen** [comment]
I haven't verified this anywhere, but I _believe_ ArgoCD follows the same (or a similar) pattern, because it doesn't actually use Helm to deploy, only to template. For the actual deployment to align, it must therefore implement the pattern itself.

Following such a pattern then only makes sense, as the assumption is that all resources in an Application are necessary, and (that being the case) certain kinds of resource will have hard dependencies on certain other kinds.

You can do partial manual syncs... Perhaps you want a way of specifying a partial sync in the autosync configuration block of the Application?

**Comment by rshiva777** [comment]
Yes, looks like argocd is following the helm pattern. Thanks for the inputs @scalen
